    RuleMetadata {
        rule_id: "LF-AGENT-CAPABILITY-INCOMPLETE",
        rule_version: 1,
        detector_family: "agent_security",
        title: "Agent capability analysis incomplete",
        meaning: "One or more agent, MCP or tool surfaces could not be fully enumerated from the inspected data.",
        why_it_matters: "Missing capability data must not be interpreted as evidence that a capability is unavailable.",
        remediation: "Provide a complete MCP/tool schema snapshot and repeat capability analysis before high-assurance admission.",
        limitations: "This finding records bounded static evidence and does not establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-AGENT-DANGEROUS-CAPABILITY-CHAIN",
        rule_version: 2,
        detector_family: "agent_security",
        title: "Dangerous agent capability chain",
        meaning: "The agent's capability graph contains a potential path from a source capability to a sink capability, mediated by the model, that the agent could exercise. The source and sink may belong to different MCP servers or tools: reachability does not require them to share a server. The finding reports which of three states applies — a path exists with no known mitigating control, a path exists but a control (such as mandatory confirmation) is known to sit in front of the sink, or reachability could not be determined because capability discovery for the source or sink was incomplete.",
        why_it_matters: "Capability combinations such as secret access plus internet egress can create impact that is not visible when permissions are reviewed in isolation, and that impact does not require both capabilities to come from the same tool or server.",
        remediation: "Constrain or remove one or more capabilities in the reported path, narrow scopes, or require an explicit approval boundary at the sink. For an indeterminate result, complete capability discovery for the affected server before relying on the absence of this finding.",
        limitations: "This finding records a graph-reachability claim from bounded static evidence, not proof that data has actually flowed from source to sink. An indeterminate result means insufficient evidence to decide, not that no path exists — it must not be read as a clean pass. A path already blocked by a known isolation barrier is not reported here at all.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TOOL-HIGH-IMPACT-UNCONFIRMED",
        rule_version: 1,
        detector_family: "agent_security",
        title: "High-impact tool lacks observed confirmation",
        meaning: "A broad high-impact tool capability has no confirmation requirement represented in the inspected configuration.",
        why_it_matters: "Model-driven invocation of broad destructive, credential or administrative actions can exceed the intended operator blast radius.",
        remediation: "Add a user confirmation/approval boundary or reduce the tool to narrowly scoped operations.",
        limitations: "This finding records bounded static evidence and does not establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-MCP-AUTH-ABSENT",
        rule_version: 1,
        detector_family: "mcp_security",
        title: "Remote MCP authentication absent",
        meaning: "A remote MCP server configuration has no authentication control represented in inspected static configuration.",
        why_it_matters: "Remote tools can expose sensitive data and actions to network clients, so missing authorization materially expands the trust boundary.",
        remediation: "Configure transport-appropriate authentication/authorization and verify the effective server posture.",
        limitations: "Static configuration cannot prove an upstream proxy or external identity layer is absent; verify deployment posture before concluding exposure.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-MCP-TLS-ABSENT",
        rule_version: 1,
        detector_family: "mcp_security",
        title: "Remote MCP transport is plaintext",
        meaning: "A remote MCP endpoint is configured with plaintext HTTP.",
        why_it_matters: "Credentials, tool arguments and returned data may traverse an unprotected network channel.",
        remediation: "Use HTTPS with certificate validation for remote MCP endpoints or keep the server on a local STDIO boundary.",
        limitations: "This finding records bounded static evidence and does not establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-MCP-DISCOVERY-INCOMPLETE",
        rule_version: 1,
        detector_family: "mcp_security",
        title: "MCP capability discovery incomplete",
        meaning: "Layerfault could not enumerate the complete tool surface for an MCP server from static configuration.",
        why_it_matters: "An unenumerated tool surface prevents a complete blast-radius and policy decision.",
        remediation: "Supply an exported tool-schema snapshot or other complete declarative inventory without executing the server.",
        limitations: "This finding records bounded static evidence and does not establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-MCP-CREDENTIAL-IN-URL",
        rule_version: 1,
        detector_family: "mcp_security",
        title: "MCP endpoint embeds credentials in the URL",
        meaning: "An MCP server's configured endpoint URL embeds userinfo credentials directly (https://user:pass@host/...).",
        remediation: "Move the credential out of the URL into a properly scoped header or environment reference and rotate it, since URLs are frequently logged, cached and stored in shell history.",
        why_it_matters: "Credentials embedded in a URL routinely leak through logs, browser history, proxy records and referrer headers, none of which are designed to protect secrets.",
        limitations: "This finding records bounded static evidence from the configured endpoint string and does not establish that the credential is still valid.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-MCP-CREDENTIAL-ENV-EXPOSURE",
        rule_version: 1,
        detector_family: "mcp_security",
        title: "MCP server configuration hardcodes a credential-like value",
        meaning: "An MCP server's `env`/`headers` configuration sets a credential-like variable to a literal value rather than an indirection reference (`${VAR}`, `$VAR`, `{{ ... }}`, or similar).",
        why_it_matters: "A hardcoded secret in a configuration file is exposed to anyone who can read that file, including through version control, backups and configuration-sharing.",
        remediation: "Replace the literal value with a reference resolved from a secrets manager or the operator's own environment at launch time.",
        limitations: "This is a heuristic over the value's shape, not secret detection; it does not attempt to validate whether the value is a real, currently active credential. Only the variable name is ever recorded, never the value.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-MCP-ORIGIN-UNRESTRICTED",
        rule_version: 1,
        detector_family: "mcp_security",
        title: "Local MCP server reachable without transport security",
        meaning: "An MCP server's endpoint resolves to a loopback/local address and uses plaintext HTTP with no declared origin restriction.",
        why_it_matters: "Local servers are reachable by any co-resident process, including a browser tab; without TLS or origin validation such a server is exposed to DNS-rebinding attacks that make an untrusted remote origin appear local.",
        remediation: "Bind local MCP servers to a loopback address with explicit origin validation, or require TLS even for local endpoints.",
        limitations: "This is a static, config-only check based on a literal local address in the configuration; it does not perform DNS resolution and cannot detect a hostname that only resolves to a local address at connection time.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-MCP-AUTH-METADATA-MISSING",
        rule_version: 1,
        detector_family: "mcp_security",
        title: "MCP OAuth configuration lacks protected-resource metadata",
        meaning: "An MCP server declares OAuth configuration without a declared resource indicator and authorization-server list.",
        why_it_matters: "Protected-resource metadata is what lets a client verify it is authenticating to the resource it intends to reach, rather than being redirected to a confused-deputy or mix-up target.",
        remediation: "Declare the resource indicator and authorization server(s) explicitly in the MCP server's OAuth configuration.",
        limitations: "Layerfault does not fetch a live `.well-known/oauth-protected-resource` document; this finding reflects only what the static configuration itself declares.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-MCP-TOKEN-AUDIENCE-UNBOUND",
        rule_version: 1,
        detector_family: "mcp_security",
        title: "MCP OAuth token has no declared audience binding",
        meaning: "An MCP server declares OAuth configuration without a declared token audience (RFC 8707 resource indicator) binding.",
        why_it_matters: "An unbound token can potentially be replayed against a different resource than the one it was issued for, which is the mechanism behind token-passthrough and confused-deputy attacks.",
        remediation: "Bind issued tokens to the specific MCP resource using a resource indicator, and reject tokens whose audience does not match.",
        limitations: "This finding reflects the static configuration's declared fields only and does not verify token behaviour at runtime.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-MCP-SCOPE-OVERBROAD",
        rule_version: 1,
        detector_family: "mcp_security",
        title: "MCP OAuth scope is overbroad",
        meaning: "An MCP server's declared OAuth scope contains a wildcard or an admin/all-shaped grant rather than a narrowly scoped permission.",
        why_it_matters: "A broad scope grant expands what a compromised or misbehaving MCP integration can do far beyond what the integration actually needs.",
        remediation: "Narrow the requested scope to the minimum the integration requires.",
        limitations: "This is a pattern match over a small set of known broad-scope tokens; a scope string that is broad in effect but does not match one of these patterns will not be flagged.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-MCP-TOKEN-PASSTHROUGH-RISK",
        rule_version: 1,
        detector_family: "mcp_security",
        title: "Credential name shared across distinct MCP servers",
        meaning: "The same credential-shaped variable name is declared for two or more MCP servers with different endpoints or executables.",
        why_it_matters: "Reusing one credential across distinct trust boundaries is the structural precondition for token-passthrough and confused-deputy attacks: a token obtained for one resource being presented to another.",
        remediation: "Use distinct, narrowly scoped credentials per server rather than one shared value.",
        limitations: "Name equality across servers is a coincidence-tolerant heuristic, not proof that the same credential value is reused; only variable names are compared, never values.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-MCP-CONTRADICTORY-ANNOTATION",
        rule_version: 1,
        detector_family: "mcp_security",
        title: "MCP tool annotation contradicts its inferred capability",
        meaning: "An MCP tool's self-declared `readOnlyHint`/`destructiveHint` annotation contradicts a capability Layerfault independently inferred from the tool's own schema.",
        why_it_matters: "Tool annotations are supplied by the MCP server itself and the MCP specification is explicit that clients must treat them as untrusted claims, not facts, unless the server is otherwise trusted. A contradiction is exactly the signal that trust would be misplaced.",
        remediation: "Review the tool's actual behaviour before relying on its self-declared annotations, and treat the schema-inferred capability as the more conservative assumption.",
        limitations: "The inferred capability side of this comparison is itself lexical/structural inference (see LF-AGENT-DANGEROUS-CAPABILITY-CHAIN's own limitations) and can be wrong in either direction; this finding reports a discrepancy worth reviewing, not a proven falsehood.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-MCP-SUPPLY-CHAIN-AUTO-DOWNLOAD",
        rule_version: 1,
        detector_family: "mcp_security",
        title: "MCP server launched via an unpinned ad-hoc package runner",
        meaning: "An MCP server's launch command uses an ad-hoc package runner (npx, uvx, pnpm dlx, yarn dlx, bunx, pipx run) that fetches the package on demand, and the package specifier does not pin an exact version.",
        why_it_matters: "Without a pinned version, the code actually executed at connection time is whatever the registry currently serves for that package name, which can change between runs without any change to the local configuration.",
        remediation: "Pin an exact version in the package specifier (e.g. `name@1.2.3`), or install the package ahead of time and reference the resulting executable directly.",
        limitations: "This is a static reading of the command line only; Layerfault does not query the package registry and cannot determine whether the pinned version, if present, is itself trustworthy.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-MCP-SUPPLY-CHAIN-AUTO-CONFIRM",
        rule_version: 1,
        detector_family: "mcp_security",
        title: "MCP server launch command suppresses install confirmation",
        meaning: "An MCP server's launch command passes an auto-confirm flag (`-y`/`--yes`) to its package runner.",
        why_it_matters: "This removes the last interactive checkpoint before the runner installs and executes package code, which matters most in combination with an unpinned package specifier.",
        remediation: "Remove the auto-confirm flag, or pin an exact version so the flag has nothing consequential left to silently confirm.",
        limitations: "The flag's presence is read directly from static configuration; this does not evaluate whether the flag was necessary for the launcher to function non-interactively in its deployment context.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-AGENT-CAPABILITY-EXPANSION",
        rule_version: 1,
        detector_family: "agent_security",
        title: "Agent capability graph expanded since baseline",
        meaning: "An agent/MCP capability graph, compared against a prior baseline observation of the same agent, gained a server, tool, capability grant, or newly reachable dangerous path.",
        why_it_matters: "A capability graph that grows silently between observations is exactly the drift a one-time admission review cannot catch; naming what specifically expanded lets an operator judge whether the change was expected.",
        remediation: "Review the added capability against the change that produced it (an MCP server update, a configuration edit) and re-admit deliberately if the expansion is intended.",
        limitations: "This compares two already-computed capability graphs; it does not itself determine which prior observation is the correct baseline to compare against, and a server or tool being removed and re-added under a different identity will appear as an addition, not a modification.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BEHAV-CANARY-ACCESS",
        rule_version: 1,
        detector_family: "behavioural",
        title: "Sandboxed runtime accessed a synthetic credential",
        meaning: "Syscall telemetry observed access to a Layerfault-created decoy secret or SSH credential path. No real host credential was exposed.",
        why_it_matters: "The runtime attempted an action against the host during a sandboxed probe, which is behaviour rather than mere capability.",
        remediation: "Treat this as high-risk credential-harvesting behavior and inspect the package/runtime code path before any deployment.",
        limitations: "Observations come from a bounded sandboxed probe with a fixed seed and configuration. Absence of an observation is not absence of the behaviour, and a single observation is not proof of consistent behaviour.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BEHAV-DANGEROUS-EXEC",
        rule_version: 1,
        detector_family: "behavioural",
        title: "Sandboxed runtime attempted shell/network utility execution",
        meaning: "The active sandbox observed an attempted shell or network utility child process, which is a high-confidence dynamic side-effect signal.",
        why_it_matters: "The runtime attempted an action against the host during a sandboxed probe, which is behaviour rather than mere capability.",
        remediation: "Block deployment and inspect the responsible loader/model package code. Reproduce only inside the isolated lab sandbox.",
        limitations: "Observations come from a bounded sandboxed probe with a fixed seed and configuration. Absence of an observation is not absence of the behaviour, and a single observation is not proof of consistent behaviour.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BEHAV-FILESYSTEM-MUTATION",
        rule_version: 1,
        detector_family: "behavioural",
        title: "Sandboxed runtime mutated the workspace",
        meaning: "The model/runtime created, modified, or deleted an unexpected file in Layerfault's synthetic writable workspace.",
        why_it_matters: "The runtime attempted an action against the host during a sandboxed probe, which is behaviour rather than mere capability.",
        remediation: "Review the mutation and originating package code. Ordinary inference should not persist unexpected executable/configuration artifacts.",
        limitations: "Observations come from a bounded sandboxed probe with a fixed seed and configuration. Absence of an observation is not absence of the behaviour, and a single observation is not proof of consistent behaviour.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BEHAV-FILESYSTEM-WRITE-ATTEMPT",
        rule_version: 1,
        detector_family: "behavioural",
        title: "Sandboxed runtime attempted a protected filesystem write",
        meaning: "Syscall telemetry observed an attempted write/mutation against a read-only model/base or other sensitive host-like mount. The sandbox prevented persistent modification.",
        why_it_matters: "The runtime attempted an action against the host during a sandboxed probe, which is behaviour rather than mere capability.",
        remediation: "Inspect the originating loader/runtime code and keep the model blocked or under review until the attempted write is explained.",
        limitations: "Observations come from a bounded sandboxed probe with a fixed seed and configuration. Absence of an observation is not absence of the behaviour, and a single observation is not proof of consistent behaviour.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BEHAV-NETWORK-ATTEMPT",
        rule_version: 1,
        detector_family: "behavioural",
        title: "Sandboxed runtime attempted network access",
        meaning: "Syscall telemetry observed the isolated model/runtime attempting an IPv4/IPv6 network operation. The sandbox prevented host/network exposure.",
        why_it_matters: "The runtime attempted an action against the host during a sandboxed probe, which is behaviour rather than mere capability.",
        remediation: "Treat unexpected network intent as high risk. Inspect package custom code and reproduce only in the strong sandbox before deployment.",
        limitations: "Observations come from a bounded sandboxed probe with a fixed seed and configuration. Absence of an observation is not absence of the behaviour, and a single observation is not proof of consistent behaviour.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BEHAV-PERSONA-PERSISTENCE",
        rule_version: 1,
        detector_family: "behavioural",
        title: "Behavioural security finding",
        meaning: "The bounded probe suite observed a security-relevant behaviour or base-versus-derived regression.",
        why_it_matters: "The runtime attempted an action against the host during a sandboxed probe, which is behaviour rather than mere capability.",
        remediation: "Do not deploy the derivative until the behaviour is understood and reproduced. A clean run would not prove absence of other hidden triggers.",
        limitations: "Observations come from a bounded sandboxed probe with a fixed seed and configuration. Absence of an observation is not absence of the behaviour, and a single observation is not proof of consistent behaviour.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BEHAV-PRIVILEGE-BOUNDARY",
        rule_version: 1,
        detector_family: "behavioural",
        title: "Behavioural security finding",
        meaning: "The bounded probe suite observed a security-relevant behaviour or base-versus-derived regression.",
        why_it_matters: "The runtime attempted an action against the host during a sandboxed probe, which is behaviour rather than mere capability.",
        remediation: "Do not deploy the derivative until the behaviour is understood and reproduced. A clean run would not prove absence of other hidden triggers.",
        limitations: "Observations come from a bounded sandboxed probe with a fixed seed and configuration. Absence of an observation is not absence of the behaviour, and a single observation is not proof of consistent behaviour.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BEHAV-RUNTIME-FAILURE",
        rule_version: 1,
        detector_family: "behavioural",
        title: "Sandboxed runtime failed during active analysis",
        meaning: "The isolated loader or inference runtime failed, timed out, or broke the Layerfault probe protocol. Any filesystem/process/network telemetry collected before failure is preserved.",
        why_it_matters: "The runtime attempted an action against the host during a sandboxed probe, which is behaviour rather than mere capability.",
        remediation: "Treat unexpected runtime failure as review evidence. Inspect the captured stderr and sandbox telemetry, then reproduce only inside the strong sandbox before deployment.",
        limitations: "Observations come from a bounded sandboxed probe with a fixed seed and configuration. Absence of an observation is not absence of the behaviour, and a single observation is not proof of consistent behaviour.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BEHAV-SECRET-DISCLOSURE",
        rule_version: 1,
        detector_family: "behavioural",
        title: "Behavioural security finding",
        meaning: "The bounded probe suite observed a security-relevant behaviour or base-versus-derived regression.",
        why_it_matters: "The runtime attempted an action against the host during a sandboxed probe, which is behaviour rather than mere capability.",
        remediation: "Do not deploy the derivative until the behaviour is understood and reproduced. A clean run would not prove absence of other hidden triggers.",
        limitations: "Observations come from a bounded sandboxed probe with a fixed seed and configuration. Absence of an observation is not absence of the behaviour, and a single observation is not proof of consistent behaviour.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BEHAV-SECURE-CODE-REGRESSION",
        rule_version: 1,
        detector_family: "behavioural",
        title: "Behavioural security finding",
        meaning: "The bounded probe suite observed a security-relevant behaviour or base-versus-derived regression.",
        why_it_matters: "The runtime attempted an action against the host during a sandboxed probe, which is behaviour rather than mere capability.",
        remediation: "Do not deploy the derivative until the behaviour is understood and reproduced. A clean run would not prove absence of other hidden triggers.",
        limitations: "Observations come from a bounded sandboxed probe with a fixed seed and configuration. Absence of an observation is not absence of the behaviour, and a single observation is not proof of consistent behaviour.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BEHAV-SENSITIVE-PATH-ACCESS",
        rule_version: 1,
        detector_family: "behavioural",
        title: "Sandboxed runtime attempted sensitive path access",
        meaning: "The active runtime attempted to access a sensitive path such as /etc/shadow, process environment data, or SSH material inside the isolated filesystem view.",
        why_it_matters: "The runtime attempted an action against the host during a sandboxed probe, which is behaviour rather than mere capability.",
        remediation: "Block deployment until the access is explained. Keep reproduction inside the strong sandbox.",
        limitations: "Observations come from a bounded sandboxed probe with a fixed seed and configuration. Absence of an observation is not absence of the behaviour, and a single observation is not proof of consistent behaviour.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BEHAV-TARGETED-CONTENT",
        rule_version: 1,
        detector_family: "behavioural",
        title: "Behavioural security finding",
        meaning: "The bounded probe suite observed a security-relevant behaviour or base-versus-derived regression.",
        why_it_matters: "The runtime attempted an action against the host during a sandboxed probe, which is behaviour rather than mere capability.",
        remediation: "Do not deploy the derivative until the behaviour is understood and reproduced. A clean run would not prove absence of other hidden triggers.",
        limitations: "Observations come from a bounded sandboxed probe with a fixed seed and configuration. Absence of an observation is not absence of the behaviour, and a single observation is not proof of consistent behaviour.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BEHAV-TOOL-EXFIL",
        rule_version: 1,
        detector_family: "behavioural",
        title: "Behavioural security finding",
        meaning: "The bounded probe suite observed a security-relevant behaviour or base-versus-derived regression.",
        why_it_matters: "The runtime attempted an action against the host during a sandboxed probe, which is behaviour rather than mere capability.",
        remediation: "Do not deploy the derivative until the behaviour is understood and reproduced. A clean run would not prove absence of other hidden triggers.",
        limitations: "Observations come from a bounded sandboxed probe with a fixed seed and configuration. Absence of an observation is not absence of the behaviour, and a single observation is not proof of consistent behaviour.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BEHAV-TRACE-TRUNCATED",
        rule_version: 1,
        detector_family: "behavioural",
        title: "Active-analysis syscall telemetry was truncated",
        meaning: "The sandboxed runtime produced more syscall trace data than Layerfault's bounded telemetry budget, so dynamic side-effect coverage is incomplete for this run.",
        why_it_matters: "The runtime attempted an action against the host during a sandboxed probe, which is behaviour rather than mere capability.",
        remediation: "Repeat with a narrower probe suite or inspect the retained trace evidence on a dedicated lab host; do not interpret this run as complete dynamic coverage.",
        limitations: "Observations come from a bounded sandboxed probe with a fixed seed and configuration. Absence of an observation is not absence of the behaviour, and a single observation is not proof of consistent behaviour.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BEHAV-UNEXPECTED-EXEC",
        rule_version: 1,
        detector_family: "behavioural",
        title: "Sandboxed runtime spawned a child process",
        meaning: "Syscall telemetry observed a process execution beyond the expected model runtime.",
        why_it_matters: "The runtime attempted an action against the host during a sandboxed probe, which is behaviour rather than mere capability.",
        remediation: "Review the exact attempted executable and package code. Child-process creation is not required for ordinary model inference in Layerfault's supported active paths.",
        limitations: "Observations come from a bounded sandboxed probe with a fixed seed and configuration. Absence of an observation is not absence of the behaviour, and a single observation is not proof of consistent behaviour.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-LAYERPOLICY",
        rule_version: 1,
        detector_family: "policy",
        title: "Layerfault security finding",
        meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the finding evidence and follow the configured policy before deployment.",
        limitations: "This is a policy decision about findings, not an independent technical observation. The underlying evidence belongs to the referenced findings.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BUDGET-EVIDENCE",
        rule_version: 1,
        detector_family: "resource-budget",
        title: "Static scan evidence budget exhausted",
        meaning: "The shared scan resource envelope could not retain all evidence produced by the bounded static analysis.",
        why_it_matters: "Unretained evidence leaves part of the security assessment incomplete and cannot be reported as a clean pass.",
        remediation: "Use a larger approved budget profile or review the artifact in a separately bounded workflow.",
        limitations: "This reports incomplete observation caused by a resource limit; it does not establish malicious intent.",
        evidence_requirement: EvidenceRequirement::StructuredOnly,
        requirement_reason: "The exhaustion record is structured budget evidence rather than a source excerpt.",
    },
    RuleMetadata {
        rule_id: "LF-TEMPLATE-CHANGED",
        rule_version: 1,
        detector_family: "template",
        title: "Derived-model integrity change",
        meaning: "A security-relevant component of the derived model differs from the supplied base or transformation claim.",
        why_it_matters: "A security-relevant component changed between revisions, so a prior assessment of this identity no longer describes what is on disk.",
        remediation: "Verify the claimed transformation and investigate the changed component before treating the derivative as equivalent to its base.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TEMPLATE-DYNAMIC-INCLUDE",
        rule_version: 2,
        detector_family: "template",
        title: "Dynamic template include/import",
        meaning: "High-priority prompt/template metadata dynamically imports/includes template content and requires review.",
        why_it_matters: "Dynamic template includes pull in content resolved at render time, which static review of the shipped template cannot cover.",
        remediation: "Verify the referenced template source is fixed and trusted before rendering.",
        limitations: "Layerfault never renders templates. Whether this expression is exploitable depends on the runtime rendering context, which static analysis cannot determine.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TEMPLATE-INTROSPECTION",
        rule_version: 2,
        detector_family: "template",
        title: "Template introspection primitives",
        meaning: "A model template contains Jinja/Python introspection primitives that can become dangerous in an overly permissive rendering environment.",
        why_it_matters: "Template object traversal reaches the Python object graph, which in a rendering context that evaluates it can lead to arbitrary code execution.",
        remediation: "Review the runtime template sandbox and remove introspection primitives unless they are required and demonstrably safe.",
        limitations: "Layerfault never renders templates. Whether this expression is exploitable depends on the runtime rendering context, which static analysis cannot determine.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TEMPLATE-SSTI",
        rule_version: 2,
        detector_family: "template",
        title: "Template object-graph traversal",
        meaning: "High-priority prompt/template metadata contains Jinja-style object graph or dunder traversal associated with server-side template injection primitives.",
        why_it_matters: "Template object traversal reaches the Python object graph, which in a rendering context that evaluates it can lead to arbitrary code execution.",
        remediation: "Block or remove the template and review it as code-capable input before any renderer processes it.",
        limitations: "Layerfault never renders templates. Whether this expression is exploitable depends on the runtime rendering context, which static analysis cannot determine.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-EXECUTORCH-TRUNCATED",
        rule_version: 1,
        detector_family: "executorch",
        title: "Truncated ExecuTorch artifact",
        meaning: "The ExecuTorch file is smaller than the minimum FlatBuffer header size.",
        why_it_matters: "Truncated models cause buffer read errors or unexpected execution failures.",
        remediation: "Re-export or re-download the ExecuTorch model.",
        limitations: "Static size and header check.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-EXECUTORCH-INVALID-MAGIC",
        rule_version: 1,
        detector_family: "executorch",
        title: "Invalid ExecuTorch magic header",
        meaning: "The artifact lacks the required 'ET' FlatBuffer file identifier.",
        why_it_matters: "Format claim mismatch or corrupted file header.",
        remediation: "Verify format and re-export ExecuTorch file.",
        limitations: "Pure-Rust header verification.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-EXECUTORCH-BOUNDS",
        rule_version: 1,
        detector_family: "executorch",
        title: "ExecuTorch table offset out of bounds",
        meaning: "FlatBuffer root table offset exceeds file boundaries.",
        why_it_matters: "Out of bounds offsets indicate memory corruption or malformed model binary.",
        remediation: "Block the file and rebuild ExecuTorch model.",
        limitations: "Bounded offset checks.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-EXECUTORCH-STRUCTURAL",
        rule_version: 1,
        detector_family: "executorch",
        title: "ExecuTorch capability-limited structural analysis",
        meaning: "ExecuTorch header and segment bounds were statically verified.",
        why_it_matters: "Confirms valid header bounds and lack of embedded executable delegates.",
        remediation: "No remediation required.",
        limitations: "Capability-limited structural parser.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-RUNTIME-POSTURE-NETWORK-EXPOSED",
        rule_version: 1,
        detector_family: "runtime_posture",
        title: "Runtime network exposure observed",
        meaning: "The runtime is configured to listen beyond loopback.",
        why_it_matters: "Runtime configuration changes whether a model-loading flaw is reachable and how safely a local service is exposed.",
        remediation: "Review the runtime bind, authentication, TLS and process configuration and re-run the posture assessment.",
        limitations: "Posture is based only on safely observable local process/configuration facts; unknown facts remain unknown.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-RUNTIME-POSTURE-AUTH-ABSENT",
        rule_version: 1,
        detector_family: "runtime_posture",
        title: "Runtime authentication absent",
        meaning: "A network-exposed runtime has no observed authentication control.",
        why_it_matters: "Runtime configuration changes whether a model-loading flaw is reachable and how safely a local service is exposed.",
        remediation: "Review the runtime bind, authentication, TLS and process configuration and re-run the posture assessment.",
        limitations: "Posture is based only on safely observable local process/configuration facts; unknown facts remain unknown.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-RUNTIME-POSTURE-TLS-ABSENT",
        rule_version: 1,
        detector_family: "runtime_posture",
        title: "Runtime TLS absent",
        meaning: "A network-exposed runtime has no observed TLS configuration.",
        why_it_matters: "Runtime configuration changes whether a model-loading flaw is reachable and how safely a local service is exposed.",
        remediation: "Review the runtime bind, authentication, TLS and process configuration and re-run the posture assessment.",
        limitations: "Posture is based only on safely observable local process/configuration facts; unknown facts remain unknown.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-RUNTIME-POSTURE-PYTHON-OPTIMIZED",
        rule_version: 1,
        detector_family: "runtime_posture",
        title: "Python optimization enabled",
        meaning: "Python optimization is enabled in a runtime where security behaviour may depend on assertions.",
        why_it_matters: "Runtime configuration changes whether a model-loading flaw is reachable and how safely a local service is exposed.",
        remediation: "Review the runtime bind, authentication, TLS and process configuration and re-run the posture assessment.",
        limitations: "Posture is based only on safely observable local process/configuration facts; unknown facts remain unknown.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-RUNTIME-POSTURE-CUSTOM-CODE-EXTENSION",
        rule_version: 1,
        detector_family: "runtime_posture",
        title: "Runtime loads an operator-supplied code extension",
        meaning: "The runtime's launch configuration points at an operator-supplied middleware or plugin module to be loaded and executed at startup.",
        why_it_matters: "This is code the launch command itself chooses to load, distinct from code bundled inside a downloaded model; if that code path is reachable to an untrusted operator or configuration source, it is a direct code-execution surface.",
        remediation: "Confirm the extension's source and content are trusted and pinned before this runtime is launched with it configured.",
        limitations: "Posture is based only on safely observable local process/configuration facts; the extension module's own content is not inspected here.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-RUNTIME-POSTURE-PICKLE-WEIGHT-LOADING",
        rule_version: 1,
        detector_family: "runtime_posture",
        title: "Runtime configured to load weights via pickle deserialization",
        meaning: "The runtime's load format configuration deserializes model weights through a pickle-based path rather than a safe tensor format.",
        why_it_matters: "Pickle deserialization can execute arbitrary code embedded in the weight file; this is the same class of risk Layerfault's pickle scanner exists to catch in the artifact itself, now present as a runtime-configuration choice.",
        remediation: "Convert the model to a safe tensor format (e.g. safetensors) and load format that does not deserialize via pickle.",
        limitations: "Posture is based only on safely observable local process/configuration facts; it does not itself scan the weight file this runtime would load.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-RUNTIME-POSTURE-CORS-WILDCARD",
        rule_version: 1,
        detector_family: "runtime_posture",
        title: "Network-exposed runtime allows any CORS origin",
        meaning: "A runtime reachable from a non-loopback address is configured to accept cross-origin requests from any origin.",
        why_it_matters: "Combined with network exposure, an unrestricted CORS policy lets any web page a user visits make authenticated requests against the runtime on the user's behalf.",
        remediation: "Restrict the allowed origins to the specific origins that need access, rather than a wildcard.",
        limitations: "Posture is based only on safely observable local process/configuration facts; unknown facts remain unknown.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-RUNTIME-POSTURE-CUSTOM-CHAT-TEMPLATE",
        rule_version: 1,
        detector_family: "runtime_posture",
        title: "Runtime uses an operator-supplied chat template",
        meaning: "The runtime is configured to use a chat template supplied outside the model's own bundled template.",
        why_it_matters: "The chat template controls how the runtime renders roles and boundaries into the prompt actually sent to the model; an overridden template is worth knowing about when reasoning about prompt-boundary security, even though this finding does not itself assess the template's content.",
        remediation: "Confirm the substituted template's source and content are trusted before relying on it in a security-relevant deployment.",
        limitations: "This is a presence signal only; the template's actual content is not analysed here (see the tokenizer/chat-template security programme item).",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-RUNTIME-POSTURE-REVISION-UNPINNED",
        rule_version: 1,
        detector_family: "runtime_posture",
        title: "Runtime loads a model from an unpinned revision",
        meaning: "The runtime is configured to load the model from a floating reference (a branch name, tag that can move, or no revision at all) rather than an immutable pinned revision.",
        why_it_matters: "A floating reference can resolve to different content on a later run than it did at admission time, without any change to the local launch configuration.",
        remediation: "Pin the runtime to a specific, immutable model revision.",
        limitations: "Posture is based only on safely observable local process/configuration facts; it does not verify that a pinned revision, where present, is itself trustworthy.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-RUNTIME-POSTURE-LOCAL-MEDIA-ACCESS",
        rule_version: 1,
        detector_family: "runtime_posture",
        title: "Network-exposed runtime accepts local filesystem media paths",
        meaning: "A runtime reachable from a non-loopback address is configured to read media (images/audio) from local filesystem paths supplied in requests.",
        why_it_matters: "A network-reachable service that can be pointed at an arbitrary local path is a local-file-read surface for any client able to reach it.",
        remediation: "Restrict accepted media sources to a specific allowlisted directory, or disable local path access for network-exposed deployments.",
        limitations: "Posture is based only on safely observable local process/configuration facts; unknown facts remain unknown.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-RUNTIME-POSTURE-CROSS-TENANT-STATE-EXPOSURE",
        rule_version: 1,
        detector_family: "runtime_posture",
        title: "Network-exposed runtime exposes per-request state across clients",
        meaning: "A runtime reachable from a non-loopback address has an endpoint or mode enabled that exposes per-request or per-slot internal state — potentially including another client's in-flight prompt — to any client able to reach it.",
        why_it_matters: "On a server shared by multiple clients, this endpoint is a direct cross-tenant data-leakage path: one client can read another client's request content.",
        remediation: "Disable the state-exposing endpoint for any deployment reachable by more than one trusted party, or restrict it to a private management network.",
        limitations: "Posture is based only on safely observable local process/configuration facts; unknown facts remain unknown.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-RUNTIME-POSTURE-INCOMPLETE",
        rule_version: 1,
        detector_family: "runtime_posture",
        title: "Runtime posture incomplete",
        meaning: "Layerfault could not establish all posture facts required for a complete assessment.",
        why_it_matters: "Runtime configuration changes whether a model-loading flaw is reachable and how safely a local service is exposed.",
        remediation: "Review the runtime bind, authentication, TLS and process configuration and re-run the posture assessment.",
        limitations: "Posture is based only on safely observable local process/configuration facts; unknown facts remain unknown.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-RUNTIME-EXPLOIT-PRECONDITIONS-MET",
        rule_version: 1,
        detector_family: "runtime_exploitability",
        title: "Runtime exploitability preconditions met",
        meaning: "An affected runtime version and all encoded exploitability preconditions were observed.",
        why_it_matters: "A vulnerable version is only one part of whether a model/runtime pair can reach a security flaw.",
        remediation: "Patch the runtime and remove or constrain the model/runtime preconditions identified in the evidence.",
        limitations: "The result is bounded to typed facts Layerfault can safely observe; unknown facts are not treated as false.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-RUNTIME-EXPLOIT-PRECONDITIONS-POSSIBLE",
        rule_version: 1,
        detector_family: "runtime_exploitability",
        title: "Runtime exploitability possible",
        meaning: "An affected or potentially affected runtime has incomplete or partially known exploitability preconditions.",
        why_it_matters: "A vulnerable version is only one part of whether a model/runtime pair can reach a security flaw.",
        remediation: "Patch the runtime and remove or constrain the model/runtime preconditions identified in the evidence.",
        limitations: "The result is bounded to typed facts Layerfault can safely observe; unknown facts are not treated as false.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-RUNTIME-EXPLOIT-INCOMPLETE",
        rule_version: 1,
        detector_family: "runtime_exploitability",
        title: "Runtime exploitability incomplete",
        meaning: "Layerfault could not establish all facts needed for contextual exploitability.",
        why_it_matters: "A vulnerable version is only one part of whether a model/runtime pair can reach a security flaw.",
        remediation: "Patch the runtime and remove or constrain the model/runtime preconditions identified in the evidence.",
        limitations: "The result is bounded to typed facts Layerfault can safely observe; unknown facts are not treated as false.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-CONFIG-ACTIVATION-IMPORT",
        rule_version: 1,
        detector_family: "declarative_execution",
        title: "Config Activation Import",
        meaning: "Layerfault observed the security condition represented by LF-CONFIG-ACTIVATION-IMPORT.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-CONFIG-CUSTOM-CLASS",
        rule_version: 1,
        detector_family: "declarative_execution",
        title: "Config Custom Class",
        meaning: "Layerfault observed the security condition represented by LF-CONFIG-CUSTOM-CLASS.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-CONFIG-DYNAMIC-IMPORT",
        rule_version: 1,
        detector_family: "declarative_execution",
        title: "Config Dynamic Import",
        meaning: "Layerfault observed the security condition represented by LF-CONFIG-DYNAMIC-IMPORT.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-CONFIG-EXECUTION-EDGE-INCOMPLETE",
        rule_version: 1,
        detector_family: "declarative_execution",
        title: "Config Execution Edge Incomplete",
        meaning: "Declarative execution-edge analysis could not resolve all relevant fields safely.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "Incomplete coverage means unobserved conditions remain unknown; it must not be interpreted as a clean result.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PREFLIGHT-INCOMPLETE",
        rule_version: 1,
        detector_family: "remote_preflight",
        title: "Preflight Incomplete",
        meaning: "Remote preflight could not inspect all security-relevant metadata within bounded fetch limits.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "Incomplete coverage means unobserved conditions remain unknown; it must not be interpreted as a clean result.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PREFLIGHT-INTEGRITY-UNAVAILABLE",
        rule_version: 1,
        detector_family: "remote_preflight",
        title: "Preflight Integrity Unavailable",
        meaning: "Layerfault observed the security condition represented by LF-PREFLIGHT-INTEGRITY-UNAVAILABLE.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PREFLIGHT-REVISION-RESOLVED",
        rule_version: 1,
        detector_family: "remote_preflight",
        title: "Preflight Revision Resolved",
        meaning: "Layerfault observed the security condition represented by LF-PREFLIGHT-REVISION-RESOLVED.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PREFLIGHT-UNPINNED-REVISION",
        rule_version: 1,
        detector_family: "remote_preflight",
        title: "Preflight Unpinned Revision",
        meaning: "Remote model inspection was requested without an immutable revision pin.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
