    RuleMetadata {
        rule_id: "LF-ADAPTER-ANALYSIS-INCOMPLETE",
        rule_version: 1,
        detector_family: "adapter",
        title: "Adapter analysis incomplete",
        meaning: "Independent bounded security analysis of an adapter could not be completed.",
        why_it_matters: "An adapter is part of the executable model composition and cannot inherit trust from the base model when its own analysis is incomplete.",
        remediation: "Resolve the adapter package or parser error and complete independent adapter inspection before admission.",
        limitations: "This finding preserves incomplete evidence and does not establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ADAPTER-UNEXPECTED-MODULE",
        rule_version: 1,
        detector_family: "adapter",
        title: "Adapter modifies undeclared module",
        meaning: "Observed adapter tensors affect modules outside the adapter configuration target-module set.",
        why_it_matters: "An adapter can change more of the model than its declaration suggests, invalidating assumptions made from configuration alone.",
        remediation: "Inspect the unexpected modules and require an independently scanned, provenance-bound adapter before admission.",
        limitations: "This finding records bounded static evidence and does not establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ADAPTER-BASE-MISMATCH",
        rule_version: 1,
        detector_family: "adapter",
        title: "LoRA adapter integrity finding",
        meaning: "The LoRA adapter configuration, base compatibility or weight distribution produced security-relevant evidence.",
        why_it_matters: "An adapter modifies a base model's behaviour, so anomalous adapter structure can change the safety properties the base model was assessed for.",
        remediation: "Verify the adapter/base relationship and inspect the affected modules; anomaly evidence does not by itself establish malicious intent.",
        limitations: "Numerical anomalies in adapter tensors are statistical signals, not evidence of a specific behavioural change.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ADAPTER-BASE-UNVERIFIED",
        rule_version: 1,
        detector_family: "adapter",
        title: "LoRA adapter integrity finding",
        meaning: "The LoRA adapter configuration, base compatibility or weight distribution produced security-relevant evidence.",
        why_it_matters: "An adapter modifies a base model's behaviour, so anomalous adapter structure can change the safety properties the base model was assessed for.",
        remediation: "Verify the adapter/base relationship and inspect the affected modules; anomaly evidence does not by itself establish malicious intent.",
        limitations: "Numerical anomalies in adapter tensors are statistical signals, not evidence of a specific behavioural change.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ADAPTER-MODULES-TO-SAVE",
        rule_version: 1,
        detector_family: "adapter",
        title: "LoRA saves full target modules",
        meaning: "The adapter configuration requests modules_to_save, which can carry full module parameters in addition to low-rank adapter deltas.",
        why_it_matters: "An adapter modifies a base model's behaviour, so anomalous adapter structure can change the safety properties the base model was assessed for.",
        remediation: "Inspect every saved module and require provenance for the complete adapter package before loading it.",
        limitations: "Numerical anomalies in adapter tensors are statistical signals, not evidence of a specific behavioural change.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ADAPTER-NORM-OUTLIER",
        rule_version: 1,
        detector_family: "adapter",
        title: "LoRA tensor norm outlier",
        meaning: "One or more adapter tensors have norms that are extreme relative to the adapter's median tensor norm.",
        why_it_matters: "An adapter modifies a base model's behaviour, so anomalous adapter structure can change the safety properties the base model was assessed for.",
        remediation: "Inspect the named adapter tensors, compare against a trusted adapter/control, and correlate with behavioural testing before deployment.",
        limitations: "Numerical anomalies in adapter tensors are statistical signals, not evidence of a specific behavioural change.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ADAPTER-RANK-ANOMALY",
        rule_version: 1,
        detector_family: "adapter",
        title: "LoRA adapter integrity finding",
        meaning: "The LoRA adapter configuration, base compatibility or weight distribution produced security-relevant evidence.",
        why_it_matters: "An adapter modifies a base model's behaviour, so anomalous adapter structure can change the safety properties the base model was assessed for.",
        remediation: "Verify the adapter/base relationship and inspect the affected modules; anomaly evidence does not by itself establish malicious intent.",
        limitations: "Numerical anomalies in adapter tensors are statistical signals, not evidence of a specific behavioural change.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ADAPTER-SCALING-ANOMALY",
        rule_version: 1,
        detector_family: "adapter",
        title: "LoRA scaling anomaly",
        meaning: "The adapter alpha/r scaling factor is far outside Layerfault's conservative review range.",
        why_it_matters: "An adapter modifies a base model's behaviour, so anomalous adapter structure can change the safety properties the base model was assessed for.",
        remediation: "Verify the adapter configuration and base-model compatibility. Treat this as anomaly evidence, not proof of malicious intent.",
        limitations: "Numerical anomalies in adapter tensors are statistical signals, not evidence of a specific behavioural change.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ADAPTER-SPECTRAL-CONCENTRATION",
        rule_version: 1,
        detector_family: "adapter",
        title: "LoRA spectral concentration",
        meaning: "A bounded adapter analysis found unusually concentrated singular-value energy in a tensor.",
        why_it_matters: "An adapter modifies a base model's behaviour, so anomalous adapter structure can change the safety properties the base model was assessed for.",
        remediation: "Review the affected tensor and compare with a clean/control adapter. Spectral concentration alone does not establish a backdoor.",
        limitations: "Numerical anomalies in adapter tensors are statistical signals, not evidence of a specific behavioural change.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ADAPTER-WEIGHT-ANOMALY",
        rule_version: 1,
        detector_family: "adapter",
        title: "LoRA adapter integrity finding",
        meaning: "The LoRA adapter configuration, base compatibility or weight distribution produced security-relevant evidence.",
        why_it_matters: "An adapter modifies a base model's behaviour, so anomalous adapter structure can change the safety properties the base model was assessed for.",
        remediation: "Verify the adapter/base relationship and inspect the affected modules; anomaly evidence does not by itself establish malicious intent.",
        limitations: "Numerical anomalies in adapter tensors are statistical signals, not evidence of a specific behavioural change.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ARCHIVE-BOMB",
        rule_version: 1,
        detector_family: "archive",
        title: "Decompression bomb detected",
        meaning: "An archive member produced an extreme compression ratio or streaming decompression byte cap violation during unpacking.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Block the archive as a denial-of-service attack payload.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ARCHIVE-DUPLICATE",
        rule_version: 1,
        detector_family: "archive",
        title: "Archive duplicate or case-colliding member",
        meaning: "An archive contains multiple entries resolving to the same normalized virtual path or case-insensitive collision.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Block or inspect the archive; loader behaviour across case-insensitive filesystems is ambiguous and unsafe.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ARCHIVE-ENCRYPTED",
        rule_version: 1,
        detector_family: "archive",
        title: "Encrypted archive member",
        meaning: "An archive member is encrypted and cannot be inspected without password cracking.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the origin of encrypted content. Layerfault does not attempt password cracking and marks coverage incomplete.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ARCHIVE-FORMAT-MISMATCH",
        rule_version: 1,
        detector_family: "archive",
        title: "Archive format smuggling mismatch",
        meaning: "An archive file extension disagrees with its magic container header signature.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Block the artifact and investigate format smuggling.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ARCHIVE-LIMIT",
        rule_version: 1,
        detector_family: "archive",
        title: "Archive resource limit exceeded",
        meaning: "An archive member or container exceeded bounded member count, uncompressed byte size, path byte limit, or recursion depth.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Treat analysis coverage as incomplete and review the oversized container in an isolated workspace.",
        limitations: "This records what Layerfault did not examine. Unexamined content is neither clean nor harmful; it is unreviewed.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ARCHIVE-LINK",
        rule_version: 1,
        detector_family: "archive",
        title: "Archive symbolic or hard link",
        meaning: "An archive member is a symbolic or hard link.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review link targets. Layerfault never follows archive links so extraction cannot escape intended boundaries.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ARCHIVE-MALFORMED",
        rule_version: 1,
        detector_family: "archive",
        title: "Malformed archive container",
        meaning: "The archive central directory, header structure, or compression stream is corrupted or truncated.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Reject the artifact and reacquire it from a verified source.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ARCHIVE-NESTED",
        rule_version: 1,
        detector_family: "archive",
        title: "Nested archive recursion limit",
        meaning: "A chain of nested archives reached maximum nesting depth or total nested archive count limits.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the nested container structure and verify inner payloads in an isolated lab.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ARCHIVE-SECURITY-MEMBER",
        rule_version: 1,
        detector_family: "archive",
        title: "Archive security-relevant member",
        meaning: "An archive member contains metadata or dependency specifications relevant to security inspection.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review member details and dependency claims.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ARCHIVE-TRAVERSAL",
        rule_version: 1,
        detector_family: "archive",
        title: "Archive path traversal",
        meaning: "An archive member path contains illegal absolute prefixes, parent directory traversal, backslashes, drive prefixes, or control characters.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Block the archive. Do not extract or process hostile member paths.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-CORR-CUSTOM-LOADER-NATIVE",
        rule_version: 1,
        detector_family: "binary-struct",
        title: "Python custom loader to native binary capability chain",
        meaning: "Python model code loads a native library that possesses process execution or network capability imports.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Inspect the Python loader invocation and target native library capabilities before admitting the model package.",
        limitations: "Layerfault correlated a Python loader call site with native library capabilities. It did not execute the model code or verify that the native function path is invoked automatically.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-FORMAT-APPENDED-ARCHIVE",
        rule_version: 1,
        detector_family: "format",
        title: "Appended archive payload",
        meaning: "A recognized model format contains an appended archive container after its valid logical end.",
        why_it_matters: "Appended container or serialization streams carry executable or unpackable payloads appended after nominal model weights.",
        remediation: "Block admission and inspect the appended archive; valid weight files should not carry appended archives.",
        limitations: "Layerfault measured the unmodeled trailing bytes after the primary format logical end. Static detection does not prove that a particular runtime will parse or execute the trailing bytes.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-FORMAT-APPENDED-SERIALIZATION",
        rule_version: 1,
        detector_family: "format",
        title: "Appended serialization payload",
        meaning: "A recognized model format contains an appended Pickle or PyTorch serialization stream after its valid logical end.",
        why_it_matters: "Appended container or serialization streams carry executable or unpackable payloads appended after nominal model weights.",
        remediation: "Block admission immediately. Appended serialization streams can execute arbitrary code upon deserialization.",
        limitations: "Layerfault measured the unmodeled trailing bytes after the primary format logical end. Static detection does not prove that a particular runtime will parse or execute the trailing bytes.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-FORMAT-CLAIM-MISMATCH",
        rule_version: 1,
        detector_family: "format",
        title: "Format claim mismatch",
        meaning: "The artifact filename or extension claims one format, but header magic bytes identify another.",
        why_it_matters: "A misdeclared extension or role is used to bypass role-based security filters or trick parsers into executing code-capable streams.",
        remediation: "Block admission and verify the artifact source. Misdeclared extensions are a common evasion mechanism.",
        limitations: "Layerfault observed the contradiction between filename and header magic. It does not establish whether the mismatch was intentional evasion or a renaming error.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-FORMAT-CONTENT-SMUGGLING",
        rule_version: 1,
        detector_family: "format",
        title: "Format content smuggling",
        meaning: "A package member or model weight file uses a benign or misleading role extension to hide code-capable serialization or container structures.",
        why_it_matters: "A misdeclared extension or role is used to bypass role-based security filters or trick parsers into executing code-capable streams.",
        remediation: "Block the artifact package. Ensure security dispatch inspects actual byte magic rather than relying on member filenames.",
        limitations: "Layerfault observed the contradiction between filename and header magic. It does not establish whether the mismatch was intentional evasion or a renaming error.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-FORMAT-POLYGLOT",
        rule_version: 1,
        detector_family: "format",
        title: "Polyglot artifact detected",
        meaning: "The artifact is simultaneously valid under multiple security-relevant interpretations, such as a model carrying a structurally valid appended executable.",
        why_it_matters: "Polyglot files satisfy structural validators for multiple formats, allowing execution by one system while appearing as benign data to another.",
        remediation: "Block execution and quarantine the artifact for investigation.",
        limitations: "Polyglot detection establishes structural validity for multiple parsers. Layerfault did not execute the secondary payload.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-FORMAT-TRAILING-DATA",
        rule_version: 1,
        detector_family: "format",
        title: "Unmodeled trailing payload",
        meaning: "A recognized model format contains non-zero trailing bytes after its valid logical end.",
        why_it_matters: "Unmodeled trailing bytes after a format's logical end can hide secondary payloads, steganographic content, or appended code.",
        remediation: "Inspect the trailing payload offset and quarantine the file if the extra data is unverified.",
        limitations: "Layerfault measured the unmodeled trailing bytes after the primary format logical end. Static detection does not prove that a particular runtime will parse or execute the trailing bytes.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-FORMAT-UNKNOWN",
        rule_version: 1,
        detector_family: "format",
        title: "Unknown artifact format",
        meaning: "Layerfault can hash the file but does not have a structural parser for this artifact format.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Use a supported GGUF/Safetensors artifact or an explicit policy that allows the unknown format only when this is intentional.",
        limitations: "This records what Layerfault did not examine. Unexamined content is neither clean nor harmful; it is unreviewed.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-GGUF-STRUCT-VALID",
        rule_version: 1,
        detector_family: "gguf-struct",
        title: "GGUF structure validated",
        meaning: "The GGUF header, tensor layout and metadata parsed without a structural warning.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "No action is required unless policy independently blocks the artifact.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-GGUF-TEXT-LIMIT",
        rule_version: 1,
        detector_family: "gguf-struct",
        title: "GGUF security-text collection limit",
        meaning: "Security-relevant GGUF metadata exceeded a bounded collection budget. Prompt/template/system text is isolated from descriptive metadata, but some lower-priority text was truncated.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Treat coverage as incomplete and review the oversized GGUF metadata before deployment; do not interpret the warning as a clean content scan.",
        limitations: "This records what Layerfault did not examine. Unexamined content is neither clean nor harmful; it is unreviewed.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-KERAS-ARCHIVE",
        rule_version: 1,
        detector_family: "keras-struct",
        title: "Keras model security finding",
        meaning: "The Keras container contains a structural, custom-object or capability-limited condition requiring review.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Do not import untrusted custom objects/Lambda code; prefer a weights-only safe representation when possible.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-KERAS-CUSTOM-OBJECT",
        rule_version: 1,
        detector_family: "keras-struct",
        title: "Keras model security finding",
        meaning: "The Keras container contains a structural, custom-object or capability-limited condition requiring review.",
        why_it_matters: "Custom operations and unrecognised types are resolved by the runtime at load time, often by importing publisher-supplied code.",
        remediation: "Do not import untrusted custom objects/Lambda code; prefer a weights-only safe representation when possible.",
        limitations: "An unrecognised operation or type is not inherently harmful; it means Layerfault cannot confirm it resolves to reviewed, data-only handling.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-KERAS-HDF5-LIMIT",
        rule_version: 1,
        detector_family: "keras-struct",
        title: "Keras model security finding",
        meaning: "The Keras container contains a structural, custom-object or capability-limited condition requiring review.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Do not import untrusted custom objects/Lambda code; prefer a weights-only safe representation when possible.",
        limitations: "This records what Layerfault did not examine. Unexamined content is neither clean nor harmful; it is unreviewed.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-KERAS-STRUCT-VALID",
        rule_version: 1,
        detector_family: "keras-struct",
        title: "Keras archive validated",
        meaning: "The Keras archive parsed without a structural warning and referenced no custom/Lambda-like objects.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "No action is required unless policy independently blocks the artifact.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-NATIVE-DYNAMIC-LOAD",
        rule_version: 1,
        detector_family: "binary-struct",
        title: "Native binary dynamic loader capability",
        meaning: "Static analysis identified imports for dynamic library loading functions (e.g. dlopen, LoadLibrary, GetProcAddress).",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the native extension to ensure dynamic loading target paths are bounded and verified.",
        limitations: "Static detection of RPATH or dynamic loader symbols is capability evidence. It does not prove that unverified libraries are loaded at runtime or that the path is exploitable.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-NATIVE-EXEC-CAPABILITY",
        rule_version: 1,
        detector_family: "binary-struct",
        title: "Native binary process execution capability",
        meaning: "Static analysis identified imports for process execution functions (e.g. execve, system, CreateProcess).",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the native extension capability evidence and verify why process execution functions are imported.",
        limitations: "Static detection of process or network symbol imports is capability evidence, not proof of malicious intent. Layerfault did not execute the native binary.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-NATIVE-NETWORK-CAPABILITY",
        rule_version: 1,
        detector_family: "binary-struct",
        title: "Native binary network capability",
        meaning: "Static analysis identified imports for network socket or HTTP functions (e.g. connect, send, WinHttpOpen).",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the native extension capability evidence and verify why network socket/HTTP functions are imported.",
        limitations: "Static detection of process or network symbol imports is capability evidence, not proof of malicious intent. Layerfault did not execute the native binary.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-NATIVE-RPATH",
        rule_version: 1,
        detector_family: "binary-struct",
        title: "Native binary RPATH header",
        meaning: "A native executable or library contains explicit RPATH or RUNPATH search path headers.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Verify that runtime dynamic library search paths are fixed and restricted to trusted system or package boundaries.",
        limitations: "Static detection of RPATH or dynamic loader symbols is capability evidence. It does not prove that unverified libraries are loaded at runtime or that the path is exploitable.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-NATIVE-WX-SECTION",
        rule_version: 1,
        detector_family: "binary-struct",
        title: "Writable and executable native binary section",
        meaning: "A native binary member or segment contains memory flags marked both writable and executable (WX).",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Inspect the native binary build options and disable WX sections/stack before loading.",
        limitations: "Layerfault identified writable and executable memory flags statically. It did not execute the binary, and WX permissions may be caused by legacy linker settings.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ONNX-CUSTOM-OP",
        rule_version: 1,
        detector_family: "onnx-struct",
        title: "ONNX security finding",
        meaning: "The ONNX graph/container contains a structural, custom-operator or external-data condition requiring review.",
        why_it_matters: "Custom operations and unrecognised types are resolved by the runtime at load time, often by importing publisher-supplied code.",
        remediation: "Do not execute custom operators from an untrusted model; validate external data and use a supported bounded runtime only after admission.",
        limitations: "An unrecognised operation or type is not inherently harmful; it means Layerfault cannot confirm it resolves to reviewed, data-only handling.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ONNX-EXTERNAL-DATA",
        rule_version: 1,
        detector_family: "onnx-struct",
        title: "ONNX security finding",
        meaning: "The ONNX graph/container contains a structural, custom-operator or external-data condition requiring review.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Do not execute custom operators from an untrusted model; validate external data and use a supported bounded runtime only after admission.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ONNX-EXTERNAL-HARDLINK",
        rule_version: 1,
        detector_family: "onnx-struct",
        title: "ONNX external tensor has hardlink aliases",
        meaning: "An external ONNX tensor sidecar has more than one filesystem hardlink. Another pathname can mutate the same inode outside the admitted model-directory boundary.",
        why_it_matters: "External tensor references make the loaded bytes depend on files outside the artifact that was reviewed and fingerprinted.",
        remediation: "Replace the sidecar with a single-link immutable copy inside the admitted package and rescan the compound ONNX identity before loading it.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ONNX-EXTERNAL-INTEGRITY",
        rule_version: 1,
        detector_family: "onnx-struct",
        title: "ONNX external tensor integrity failure",
        meaning: "An ONNX model references external tensor data that Layerfault could not safely contain, range-check, open, or bind into the model's compound identity.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Block the model and restore the complete sidecar set from a trusted source. Do not load the protobuf without the exact verified external tensor files.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ONNX-EXTERNAL-RANGE",
        rule_version: 1,
        detector_family: "onnx-struct",
        title: "ONNX external tensor range violation",
        meaning: "An ONNX external-data offset/length points outside its integrity-bound sidecar.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Block the model and restore the exact protobuf/sidecar set from a trusted source.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ONNX-STRUCT",
        rule_version: 1,
        detector_family: "onnx-struct",
        title: "ONNX security finding",
        meaning: "The ONNX graph/container contains a structural, custom-operator or external-data condition requiring review.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Do not execute custom operators from an untrusted model; validate external data and use a supported bounded runtime only after admission.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ONNX-STRUCT-VALID",
        rule_version: 1,
        detector_family: "onnx-struct",
        title: "ONNX structure validated",
        meaning: "The ONNX ModelProto parsed without a structural, custom-domain or external-data warning.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "No action is required unless policy independently blocks the artifact.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-SAFE-DTYPE",
        rule_version: 1,
        detector_family: "safetensors-struct",
        title: "Safetensors finding",
        meaning: "The Safetensors artifact contains a structural, dtype or shard-index condition requiring review.",
        why_it_matters: "Custom operations and unrecognised types are resolved by the runtime at load time, often by importing publisher-supplied code.",
        remediation: "Reject malformed artifacts or use a supported dtype/shard set from a trusted source.",
        limitations: "An unrecognised operation or type is not inherently harmful; it means Layerfault cannot confirm it resolves to reviewed, data-only handling.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-SAFE-INDEX",
        rule_version: 1,
        detector_family: "safetensors-struct",
        title: "Safetensors index validated",
        meaning: "The sharded Safetensors index uses safe relative shard references and every referenced shard passed structural validation.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "No action is required unless policy independently blocks the artifact.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-SAFE-INDEX-INVALID",
        rule_version: 1,
        detector_family: "safetensors-struct",
        title: "Invalid Safetensors sharded index",
        meaning: "A sharded Safetensors index is malformed, references an unsafe/missing shard, or points to a shard that failed structural validation.",
        why_it_matters: "Malformed structure passed to a model runtime can cause out-of-bounds reads, excessive allocation, parser confusion or a crash in the loading process.",
        remediation: "Block the model and reacquire the complete shard set from a trusted source.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-SAFE-STRUCT",
        rule_version: 1,
        detector_family: "safetensors-struct",
        title: "Invalid Safetensors structure",
        meaning: "The Safetensors header, tensor ranges, shape sizes, or data-buffer coverage is malformed or unsafe.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Reject the file and reacquire it from a trusted source. Do not load it into an inference/runtime process.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-NPY-STRUCT",
        rule_version: 1,
        detector_family: "npy-struct",
        title: "Invalid NumPy NPY structure",
        meaning: "The NPY header, magic signature, shape dimensions or payload buffer size is malformed or truncated.",
        why_it_matters: "Layerfault observed a structural anomaly in a NumPy NPY file that may lead to parser confusion or out-of-bounds array reads.",
        remediation: "Reject the file and reacquire it from a trusted source. Do not load it into a NumPy runtime.",
        limitations: "Static analysis checks header bounds and expected byte lengths without executing NumPy.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-NPY-DTYPE-UNSUPPORTED",
        rule_version: 1,
        detector_family: "npy-struct",
        title: "Unsupported NumPy dtype descriptor",
        meaning: "The NPY header contains a complex or unrecognized dtype descriptor that static inspection cannot compute bounds for.",
        why_it_matters: "Static element size calculation is incomplete for this dtype format, reducing analysis precision.",
        remediation: "Verify the dtype specification and review the source of the array file.",
        limitations: "Layerfault reports compatibility bounds for unknown complex descriptors rather than guessing element size.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-NPY-OBJECT-DTYPE",
        rule_version: 1,
        detector_family: "npy-struct",
        title: "NumPy object dtype array detected",
        meaning: "The NumPy array uses Python object dtype ('O'), which relies on Pickle serialization when loaded with allow_pickle=True.",
        why_it_matters: "Object dtype arrays can carry code-capable Pickle payloads capable of executing arbitrary code when deserialized.",
        remediation: "Avoid loading object arrays with allow_pickle=True. Prefer standard numeric, unicode, or structured dtypes.",
        limitations: "Static analysis identifies object dtype presence without executing deserialization.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-NPY-PICKLE",
        rule_version: 1,
        detector_family: "npy-struct",
        title: "Dangerous Pickle payload in NumPy object array",
        meaning: "Bounded static opcode analysis resolved dangerous globals or callables in the Pickle stream of a NumPy object array.",
        why_it_matters: "Deserializing this object array with allow_pickle=True will execute attacker-controlled Python code or system commands.",
        remediation: "Do not unpickle or load this file with allow_pickle=True.",
        limitations: "Layerfault disassembles the opcode stream without unpickling or executing code.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-CORR-NUMPY-ALLOW-PICKLE",
        rule_version: 1,
        detector_family: "npy-correlation",
        title: "NumPy load permits Pickle for object array artifact",
        meaning: "Python code explicitly calls numpy.load with allow_pickle=True targeting an object-dtype NPY/NPZ package member.",
        why_it_matters: "Combining allow_pickle=True with an object-dtype array opens an active code execution vector when the file is loaded.",
        remediation: "Remove allow_pickle=True from numpy.load invocations or convert object dtypes to safe numeric/structured dtypes.",
        limitations: "Static analysis correlates resolved loader parameters and package member dtypes.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-SAFE-STRUCT-VALID",
        rule_version: 1,
        detector_family: "safetensors-struct",
        title: "Safetensors structure validated",
        meaning: "The Safetensors header and tensor layout parsed without an unknown-dtype warning.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "No action is required unless policy independently blocks the artifact.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TF-CHECKPOINT-LIMIT",
        rule_version: 1,
        detector_family: "tensorflow-struct",
        title: "TensorFlow model security finding",
        meaning: "The TensorFlow package contains a structural, executable/custom-operation or capability-limited condition.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Inspect the exact graph/package and do not execute untrusted custom operations during model loading.",
        limitations: "This records what Layerfault did not examine. Unexamined content is neither clean nor harmful; it is unreviewed.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TF-CHECKPOINT-STRUCT",
        rule_version: 1,
        detector_family: "tensorflow-struct",
        title: "TensorFlow model security finding",
        meaning: "The TensorFlow package contains a structural, executable/custom-operation or capability-limited condition.",
        why_it_matters: "Malformed structure passed to a model runtime can cause out-of-bounds reads, excessive allocation, parser confusion or a crash in the loading process.",
        remediation: "Inspect the exact graph/package and do not execute untrusted custom operations during model loading.",
        limitations: "A violated invariant shows the file is unsafe to parse. It does not establish that the malformation is deliberate or that a specific runtime is exploitable.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TF-EXECUTION-OP",
        rule_version: 1,
        detector_family: "tensorflow-struct",
        title: "TensorFlow model security finding",
        meaning: "The TensorFlow package contains a structural, executable/custom-operation or capability-limited condition.",
        why_it_matters: "Custom operations and unrecognised types are resolved by the runtime at load time, often by importing publisher-supplied code.",
        remediation: "Inspect the exact graph/package and do not execute untrusted custom operations during model loading.",
        limitations: "Detection is a bounded byte-substring search over the serialized graph, not a protobuf parse. Layerfault cannot attribute the marker to a specific node, confirm the operation is reachable, or rule out an incidental match.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TF-FILESYSTEM-WRITE",
        rule_version: 1,
        detector_family: "tensorflow-struct",
        title: "TensorFlow graph file-write capability",
        meaning: "The SavedModel contains a high-confidence filesystem-write primitive: PrintV2 is directed at a file URI.",
        why_it_matters: "A graph that writes to the filesystem acts on the host during inference rather than only producing model output.",
        remediation: "Block untrusted execution and inspect the graph attributes and destination paths before any TensorFlow load/invocation.",
        limitations: "Detection is a bounded byte-substring search over the serialized graph, not a protobuf parse. Layerfault cannot attribute the marker to a specific node, confirm the operation is reachable, or rule out an incidental match.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TF-SCAN-LIMIT",
        rule_version: 1,
        detector_family: "tensorflow-struct",
        title: "TensorFlow bounded scan limit",
        meaning: "The SavedModel exceeded the bounded protobuf marker scan window, so Layerfault cannot claim complete static marker coverage.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the oversized SavedModel under an isolated workflow or increase analysis capability before deployment.",
        limitations: "This records what Layerfault did not examine. Unexamined content is neither clean nor harmful; it is unreviewed.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TF-STRUCT",
        rule_version: 1,
        detector_family: "tensorflow-struct",
        title: "TensorFlow model security finding",
        meaning: "The TensorFlow package contains a structural, executable/custom-operation or capability-limited condition.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Inspect the exact graph/package and do not execute untrusted custom operations during model loading.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TF-STRUCT-VALID",
        rule_version: 1,
        detector_family: "tensorflow-struct",
        title: "TensorFlow marker scan clear",
        meaning: "The bounded protobuf marker scan of the SavedModel found no execution/filesystem-capable op-name markers.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "No action is required unless policy independently blocks the artifact.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TFLITE-ASSOCIATED-FILE",
        rule_version: 1,
        detector_family: "tflite-struct",
        title: "TFLite associated-file integrity boundary",
        meaning: "The TFLite artifact contains ZIP-appended metadata such as labels whose modification can alter application-level interpretation without changing tensor values.",
        why_it_matters: "Files carried alongside the model are extracted by tooling that consumes the artifact, widening what the artifact delivers.",
        remediation: "Integrity-bind and verify the complete TFLite file, including all associated files, against a trusted publisher artifact.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TFLITE-STRUCT",
        rule_version: 1,
        detector_family: "tflite-struct",
        title: "TensorFlow model security finding",
        meaning: "The TensorFlow package contains a structural, executable/custom-operation or capability-limited condition.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Inspect the exact graph/package and do not execute untrusted custom operations during model loading.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TFLITE-STRUCT-VALID",
        rule_version: 1,
        detector_family: "tflite-struct",
        title: "TFLite structure validated",
        meaning: "The TFLite FlatBuffer parsed without a structural warning and carries no ZIP-appended associated files.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "No action is required unless policy independently blocks the artifact.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-WHEEL-RECORD-MISMATCH",
        rule_version: 1,
        detector_family: "archive",
        title: "Python Wheel RECORD hash mismatch",
        meaning: "A Python Wheel entry digest or size differs from the values recorded in .dist-info/RECORD.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Block the wheel. Tampering or incomplete packaging was detected.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "T12-001",
        rule_version: 1,
        detector_family: "binary-struct",
        title: "Embedded ELF object",
        meaning: "A structurally plausible ELF executable object exists inside model bytes.",
        why_it_matters: "Executable machine code embedded inside a model artifact is not model data; it exists to be extracted and run.",
        remediation: "Quarantine the artifact and investigate its source. Do not infer malicious intent from magic bytes alone; Layerfault only emits this after structural checks.",
        limitations: "Layerfault parsed the executable's headers only. It did not disassemble, emulate or otherwise characterise the code, and embedded executables can have legitimate uses.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "T12-002",
        rule_version: 1,
        detector_family: "binary-struct",
        title: "Embedded PE object",
        meaning: "A structurally plausible PE executable object exists inside model bytes.",
        why_it_matters: "Executable machine code embedded inside a model artifact is not model data; it exists to be extracted and run.",
        remediation: "Quarantine the artifact and investigate its source before allowing execution.",
        limitations: "Layerfault parsed the executable's headers only. It did not disassemble, emulate or otherwise characterise the code, and embedded executables can have legitimate uses.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "T12-003",
        rule_version: 1,
        detector_family: "binary-struct",
        title: "Embedded Mach-O object",
        meaning: "A structurally plausible Mach-O executable object exists inside model bytes.",
        why_it_matters: "Executable machine code embedded inside a model artifact is not model data; it exists to be extracted and run.",
        remediation: "Quarantine the artifact and investigate its source before allowing execution on macOS or another Mach-O-capable host.",
        limitations: "Layerfault parsed the executable's headers only. It did not disassemble, emulate or otherwise characterise the code, and embedded executables can have legitimate uses.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "T12-004",
        rule_version: 1,
        detector_family: "binary-struct",
        title: "Embedded WebAssembly module",
        meaning: "A valid WebAssembly module header exists inside model bytes.",
        why_it_matters: "Executable machine code embedded inside a model artifact is not model data; it exists to be extracted and run.",
        remediation: "Quarantine the artifact and determine why executable WebAssembly content is embedded before allowing it into a runtime that can instantiate WASM.",
        limitations: "Layerfault parsed the executable's headers only. It did not disassemble, emulate or otherwise characterise the code, and embedded executables can have legitimate uses.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "T12-CLEAR",
        rule_version: 1,
        detector_family: "binary-struct",
        title: "No embedded executable object found",
        meaning: "The bounded binary object scan found no structurally valid embedded ELF/PE/Mach-O/WASM object.",
        why_it_matters: "Instruction-shaped text embedded in model data can be interpreted as instructions by a model or an agent that reads it.",
        remediation: "No action is required unless policy independently blocks the artifact.",
        limitations: "Pattern matching over text cannot distinguish an attack payload from documentation, test data or discussion of the same technique. Review the excerpt in context.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "T15-STRUCT",
        rule_version: 1,
        detector_family: "gguf-struct",
        title: "Invalid GGUF structure",
        meaning: "The GGUF structure failed bounded validation.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Reject and reacquire the model. Structural failures are not suppressible admission warnings.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
