    RuleMetadata {
        rule_id: "LF-COMPOSITION-INCOMPLETE",
        rule_version: 1,
        detector_family: "model_composition",
        title: "Model composition identity incomplete",
        meaning: "One or more executable model components could not be resolved to complete immutable identity evidence.",
        why_it_matters: "Admission of only the base artifact does not cover adapters, tokenizer/template changes or other material composition components.",
        remediation: "Resolve every executable component to immutable local bytes or a verified identity and rebuild the composition identity.",
        limitations: "This finding records bounded static evidence and does not establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-COMPOSITION-DUPLICATE-ADAPTER",
        rule_version: 1,
        detector_family: "model_composition",
        title: "Duplicate adapter in composition",
        meaning: "The same immutable adapter identity appears more than once in the ordered adapter list.",
        why_it_matters: "Duplicate application can change effective model behaviour and may indicate an accidental or ambiguous loading configuration.",
        remediation: "Confirm the intended adapter order and remove duplicate entries unless repeated application is explicitly required.",
        limitations: "This finding records bounded static evidence and does not establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-SHELL-EVAL",
        rule_version: 1,
        detector_family: "heuristics",
        title: "Shell eval invocation",
        meaning: "Streaming textual scanning found an `eval` invocation in a shell script.",
        why_it_matters: "Shell `eval` builds and runs a command from a string at run time, letting code that is not visible in the shipped source execute during script execution.",
        remediation: "Review the finding evidence and follow the configured policy before deployment.",
        limitations: "This is a textual substring match, not a shell parse: it cannot tell whether the match sits inside a comment, string literal or unreachable branch. The shell semantic frontend provides higher-fidelity analysis where supported.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-SHELL-EXEC",
        rule_version: 1,
        detector_family: "heuristics",
        title: "Shell exec invocation",
        meaning: "Streaming textual scanning found an `exec` invocation in a shell script.",
        why_it_matters: "Shell `exec` replaces the current process image, which can hand control to an attacker-supplied command with the running script's privileges.",
        remediation: "Review the finding evidence and follow the configured policy before deployment.",
        limitations: "This is a textual substring match, not a shell parse: it cannot tell whether the match sits inside a comment, string literal or unreachable branch. The shell semantic frontend provides higher-fidelity analysis where supported.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-SHELL-DOT-SOURCE",
        rule_version: 1,
        detector_family: "heuristics",
        title: "Shell dot-source invocation",
        meaning: "Streaming textual scanning found a dot-source (`. /path`) invocation in a shell script.",
        why_it_matters: "Dot-sourcing executes another file's contents in the current shell context, so its effects are not visible by reading only the sourcing script.",
        remediation: "Review the finding evidence and follow the configured policy before deployment.",
        limitations: "This is a textual substring match, not a shell parse: it cannot tell whether the match sits inside a comment, string literal or unreachable branch. The shell semantic frontend provides higher-fidelity analysis where supported.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-SHELL-CURL-PIPE",
        rule_version: 1,
        detector_family: "heuristics",
        title: "Download piped to a shell",
        meaning: "Streaming textual scanning found output piped into `sh`/`bash`, a common install-script supply-chain pattern.",
        why_it_matters: "Piping a remote download directly into a shell executes unreviewed, potentially time-varying content with no opportunity for local inspection first.",
        remediation: "Review the finding evidence and follow the configured policy before deployment.",
        limitations: "This is a textual substring match, not a shell parse: it cannot tell whether the match sits inside a comment, string literal or unreachable branch. The shell semantic frontend provides higher-fidelity analysis where supported.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PS-INVOKE-EXPRESSION",
        rule_version: 1,
        detector_family: "heuristics",
        title: "PowerShell Invoke-Expression",
        meaning: "Streaming textual scanning found `Invoke-Expression`/`iex`, PowerShell's dynamic-evaluation primitive.",
        why_it_matters: "`Invoke-Expression` builds and runs a command from a string at run time, letting code that is not visible in the shipped source execute during script execution.",
        remediation: "Review the finding evidence and follow the configured policy before deployment.",
        limitations: "This is a textual substring match, not a PowerShell parse: it cannot tell whether the match sits inside a comment, string literal or unreachable branch. The PowerShell semantic frontend provides higher-fidelity analysis where supported.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PS-ENCODED-COMMAND",
        rule_version: 1,
        detector_family: "heuristics",
        title: "PowerShell -EncodedCommand",
        meaning: "Streaming textual scanning found the `-EncodedCommand` flag, PowerShell's base64-encoded command-line evasion idiom.",
        why_it_matters: "`-EncodedCommand` runs a base64-encoded script body, which is a signature technique for hiding command content from casual review and simple string-based defenses.",
        remediation: "Review the finding evidence and follow the configured policy before deployment.",
        limitations: "This is a textual substring match, not a PowerShell parse: it cannot tell whether the match sits inside a comment, string literal or unreachable branch. The PowerShell semantic frontend provides higher-fidelity analysis where supported.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PS-DOWNLOAD",
        rule_version: 1,
        detector_family: "heuristics",
        title: "PowerShell remote download",
        meaning: "Streaming textual scanning found a PowerShell remote-download primitive (`DownloadString`, `DownloadFile`, `Invoke-WebRequest`).",
        why_it_matters: "These primitives fetch remote content during script execution, which can retrieve a payload not present in the shipped package.",
        remediation: "Review the finding evidence and follow the configured policy before deployment.",
        limitations: "This is a textual substring match, not a PowerShell parse: it cannot tell whether the match sits inside a comment, string literal or unreachable branch. The PowerShell semantic frontend provides higher-fidelity analysis where supported.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-JS-CHILD-PROCESS",
        rule_version: 1,
        detector_family: "heuristics",
        title: "JavaScript child_process usage",
        meaning: "Streaming textual scanning found Node's `child_process` module or `execSync` in JavaScript/TypeScript source.",
        why_it_matters: "Code executed during package loading with process-execution capability inherits the privileges of the host process and can reach the surrounding system.",
        remediation: "Review the finding evidence and follow the configured policy before deployment.",
        limitations: "This is a textual substring match, not a JavaScript parse: it cannot tell whether the match sits inside a comment, string literal or unreachable branch. The JavaScript semantic frontend provides higher-fidelity analysis where supported.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-JS-REQUIRE-CHILD-PROCESS",
        rule_version: 1,
        detector_family: "heuristics",
        title: "JavaScript require('child_process')",
        meaning: "Streaming textual scanning found an explicit `require('child_process')` import in JavaScript source.",
        why_it_matters: "Importing `child_process` is the direct entry point to spawning arbitrary host processes from JavaScript, commonly seen in npm postinstall-hook supply-chain attacks.",
        remediation: "Review the finding evidence and follow the configured policy before deployment.",
        limitations: "This is a textual substring match, not a JavaScript parse: it cannot tell whether the match sits inside a comment, string literal or unreachable branch. The JavaScript semantic frontend provides higher-fidelity analysis where supported.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-HEUR-CLEAR",
        rule_version: 1,
        detector_family: "heuristics",
        title: "Heuristic content scan clear",
        meaning: "No heuristic content/prompt-injection signature matched the scanned text.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "No action is required unless policy independently blocks the artifact.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-HEUR-DECODED-MATCH",
        rule_version: 1,
        detector_family: "heuristics",
        title: "Decoded hidden instruction match",
        meaning: "A bounded Base64, hex or ROT13 decode exposed a content-security signature that was not directly visible in the source text.",
        why_it_matters: "Instruction-shaped text embedded in model data can be interpreted as instructions by a model or an agent that reads it.",
        remediation: "Review the decoded evidence and surrounding template/configuration; do not trust obfuscation to be inert.",
        limitations: "Pattern matching over text cannot distinguish an attack payload from documentation, test data or discussion of the same technique. Review the excerpt in context.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BACKDOOR-BEHAVIOUR-DIVERGENCE",
        rule_version: 1,
        detector_family: "backdoor_forensics",
        title: "Backdoor Behaviour Divergence",
        meaning: "Bounded differential testing observed a security-relevant behavioural divergence.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This is empirical anomalous/backdoor-like evidence, not proof of malicious intent or a complete absence/presence claim.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BACKDOOR-HUNT-INCOMPLETE",
        rule_version: 1,
        detector_family: "backdoor_forensics",
        title: "Backdoor Hunt Incomplete",
        meaning: "The bounded trigger hunt ended without complete requested coverage.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "Incomplete coverage means unobserved conditions remain unknown; it must not be interpreted as a clean result.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BACKDOOR-STATIC-DELTA-CONCENTRATION",
        rule_version: 1,
        detector_family: "backdoor_forensics",
        title: "Backdoor Static Delta Concentration",
        meaning: "Layerfault observed the security condition represented by LF-BACKDOOR-STATIC-DELTA-CONCENTRATION.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This is empirical anomalous/backdoor-like evidence, not proof of malicious intent or a complete absence/presence claim.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BACKDOOR-STATIC-EMBEDDING-OUTLIER",
        rule_version: 1,
        detector_family: "backdoor_forensics",
        title: "Backdoor Static Embedding Outlier",
        meaning: "Layerfault observed the security condition represented by LF-BACKDOOR-STATIC-EMBEDDING-OUTLIER.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This is empirical anomalous/backdoor-like evidence, not proof of malicious intent or a complete absence/presence claim.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BACKDOOR-STATIC-NONFINITE",
        rule_version: 1,
        detector_family: "backdoor_forensics",
        title: "Backdoor Static Nonfinite",
        meaning: "Layerfault observed the security condition represented by LF-BACKDOOR-STATIC-NONFINITE.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This is empirical anomalous/backdoor-like evidence, not proof of malicious intent or a complete absence/presence claim.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BACKDOOR-TRIGGER-REPRODUCIBLE",
        rule_version: 1,
        detector_family: "backdoor_forensics",
        title: "Backdoor Trigger Reproducible",
        meaning: "Layerfault observed the security condition represented by LF-BACKDOOR-TRIGGER-REPRODUCIBLE.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This is empirical anomalous/backdoor-like evidence, not proof of malicious intent or a complete absence/presence claim.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-CORR-BACKDOOR-MULTI-SIGNAL",
        rule_version: 1,
        detector_family: "backdoor_forensics",
        title: "Corr Backdoor Multi Signal",
        meaning: "Layerfault observed the security condition represented by LF-CORR-BACKDOOR-MULTI-SIGNAL.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This is empirical anomalous/backdoor-like evidence, not proof of malicious intent or a complete absence/presence claim.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-FORENSIC-COVERAGE-INCOMPLETE",
        rule_version: 1,
        detector_family: "model_security",
        title: "Forensic Coverage Incomplete",
        meaning: "Layerfault observed the security condition represented by LF-FORENSIC-COVERAGE-INCOMPLETE.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "Incomplete coverage means unobserved conditions remain unknown; it must not be interpreted as a clean result.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-FORENSIC-TENSOR-EMBEDDED-OBJECT",
        rule_version: 1,
        detector_family: "model_security",
        title: "Forensic Tensor Embedded Object",
        meaning: "Layerfault observed the security condition represented by LF-FORENSIC-TENSOR-EMBEDDED-OBJECT.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-FORENSIC-UNCLAIMED-ARCHIVE",
        rule_version: 1,
        detector_family: "model_security",
        title: "Forensic Unclaimed Archive",
        meaning: "Layerfault observed the security condition represented by LF-FORENSIC-UNCLAIMED-ARCHIVE.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-FORENSIC-UNCLAIMED-EXECUTABLE",
        rule_version: 1,
        detector_family: "model_security",
        title: "Forensic Unclaimed Executable",
        meaning: "Layerfault observed the security condition represented by LF-FORENSIC-UNCLAIMED-EXECUTABLE.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-IDENTITY-CLAIM-INCONSISTENT",
        rule_version: 1,
        detector_family: "model_identity",
        title: "Identity Claim Inconsistent",
        meaning: "A supplied identity or relationship claim contradicts Layerfault-observed identity evidence.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-IDENTITY-INCOMPLETE",
        rule_version: 1,
        detector_family: "model_identity",
        title: "Identity Incomplete",
        meaning: "Layerfault could not construct all requested identity layers.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "Incomplete coverage means unobserved conditions remain unknown; it must not be interpreted as a clean result.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-IDENTITY-STRUCTURAL-DIVERGENCE",
        rule_version: 1,
        detector_family: "model_identity",
        title: "Identity Structural Divergence",
        meaning: "Compared artifacts diverge structurally despite an asserted or expected relationship.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-RUNTIME-COMPAT-CONDITIONAL",
        rule_version: 1,
        detector_family: "model_security",
        title: "Runtime Compat Conditional",
        meaning: "Layerfault observed the security condition represented by LF-RUNTIME-COMPAT-CONDITIONAL.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-RUNTIME-COMPAT-INCOMPATIBLE",
        rule_version: 1,
        detector_family: "model_security",
        title: "Runtime Compat Incompatible",
        meaning: "Layerfault observed the security condition represented by LF-RUNTIME-COMPAT-INCOMPATIBLE.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-RUNTIME-COMPAT-UNKNOWN",
        rule_version: 1,
        detector_family: "model_security",
        title: "Runtime Compat Unknown",
        meaning: "Layerfault observed the security condition represented by LF-RUNTIME-COMPAT-UNKNOWN.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
