    RuleMetadata {
        rule_id: "LF-PARAM-CLEAR",
        rule_version: 1,
        detector_family: "parameter",
        title: "Inference parameters within policy",
        meaning: "No inference-parameter anomaly was found against the configured thresholds.",
        why_it_matters: "Generation parameters shipped with a model influence runtime behaviour and resource consumption without any code being involved.",
        remediation: "No action is required unless policy independently blocks the artifact.",
        limitations: "A parameter outside the configured threshold is a policy observation, not evidence of malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PARAM-NUM-CTX",
        rule_version: 1,
        detector_family: "parameter",
        title: "Context window outside policy",
        meaning: "The configured context length exceeds the operator policy maximum or merits resource-capacity review.",
        why_it_matters: "Generation parameters shipped with a model influence runtime behaviour and resource consumption without any code being involved.",
        remediation: "Confirm the value is intentional given available memory/compute; adjust configuration or policy as appropriate.",
        limitations: "A parameter outside the configured threshold is a policy observation, not evidence of malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PARAM-NUM-PREDICT",
        rule_version: 1,
        detector_family: "parameter",
        title: "Prediction length outside policy",
        meaning: "The configured maximum output length exceeds the operator policy maximum.",
        why_it_matters: "Generation parameters shipped with a model influence runtime behaviour and resource consumption without any code being involved.",
        remediation: "Confirm the value is intentional; adjust configuration or policy as appropriate.",
        limitations: "A parameter outside the configured threshold is a policy observation, not evidence of malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PARAM-REPEAT-PENALTY",
        rule_version: 1,
        detector_family: "parameter",
        title: "Repeat penalty may increase repetition risk",
        meaning: "The configured repeat penalty is low enough that output repetition loops are more likely.",
        why_it_matters: "Generation parameters shipped with a model influence runtime behaviour and resource consumption without any code being involved.",
        remediation: "Confirm this is intentional; low repeat penalty can degrade output quality under some workloads.",
        limitations: "A parameter outside the configured threshold is a policy observation, not evidence of malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PARAM-SEED",
        rule_version: 1,
        detector_family: "parameter",
        title: "Fixed generation seed present",
        meaning: "A fixed seed is configured alongside another policy anomaly.",
        why_it_matters: "Generation parameters shipped with a model influence runtime behaviour and resource consumption without any code being involved.",
        remediation: "A fixed seed is a reproducibility setting; it is recorded here only as context alongside the other flagged parameter.",
        limitations: "A parameter outside the configured threshold is a policy observation, not evidence of malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PARAM-STOP-DELIMITER",
        rule_version: 1,
        detector_family: "parameter",
        title: "Stop sequence resembles a prompt-role delimiter",
        meaning: "A configured stop sequence resembles a system/user/assistant role delimiter or an instruction-override phrase.",
        why_it_matters: "Generation parameters shipped with a model influence runtime behaviour and resource consumption without any code being involved.",
        remediation: "Review whether this stop sequence is designed to manipulate prompt structure in a hosting application.",
        limitations: "A parameter outside the configured threshold is a policy observation, not evidence of malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PARAM-TEMPERATURE",
        rule_version: 1,
        detector_family: "parameter",
        title: "Sampling temperature outside policy",
        meaning: "The configured generation temperature exceeds the operator policy maximum or review threshold.",
        why_it_matters: "Generation parameters shipped with a model influence runtime behaviour and resource consumption without any code being involved.",
        remediation: "Confirm the value is intentional; adjust the model configuration or operator policy as appropriate.",
        limitations: "A parameter outside the configured threshold is a policy observation, not evidence of malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PARAM-TOP-K",
        rule_version: 1,
        detector_family: "parameter",
        title: "Sampling top_k disables filtering",
        meaning: "top_k is set to 0, which disables top-k sampling filtering entirely.",
        why_it_matters: "Generation parameters shipped with a model influence runtime behaviour and resource consumption without any code being involved.",
        remediation: "Confirm this is intentional for the deployment's sampling strategy.",
        limitations: "A parameter outside the configured threshold is a policy observation, not evidence of malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PARAM-TOP-P",
        rule_version: 1,
        detector_family: "parameter",
        title: "Sampling top_p minimally restrictive",
        meaning: "top_p is configured close to 1.0, making nucleus filtering minimally restrictive.",
        why_it_matters: "Generation parameters shipped with a model influence runtime behaviour and resource consumption without any code being involved.",
        remediation: "Confirm this is intentional for the deployment's sampling strategy.",
        limitations: "A parameter outside the configured threshold is a policy observation, not evidence of malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PYTORCH-MALFORMED",
        rule_version: 1,
        detector_family: "pytorch",
        title: "Malformed PyTorch ZIP container",
        meaning: "The PyTorch ZIP container structure could not be parsed safely.",
        why_it_matters: "A corrupted or tampered ZIP header prevents static analysis of model weights and metadata.",
        remediation: "Re-acquire the model container from a verified source.",
        limitations: "Layerfault performs static ZIP validation without running PyTorch C++ or Python code.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PYTORCH-CORRUPT-ENTRY",
        rule_version: 1,
        detector_family: "pytorch",
        title: "Corrupted PyTorch ZIP entry",
        meaning: "An entry within the PyTorch ZIP container failed index resolution or decompressed header checks.",
        why_it_matters: "Internal archive corruption may hide malicious code or payload data.",
        remediation: "Verify container integrity with sha256 checksums and re-download.",
        limitations: "Static analysis only.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PYTORCH-ZIP-STRUCTURAL",
        rule_version: 1,
        detector_family: "pytorch",
        title: "PyTorch ZIP container structural analysis",
        meaning: "PyTorch ZIP container members and pickle metadata were inspected statically.",
        why_it_matters: "Confirms that PyTorch model weight storage layout is valid and static analysis completed cleanly.",
        remediation: "No remediation required.",
        limitations: "Static analysis without code execution.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TORCHSCRIPT-CODE",
        rule_version: 1,
        detector_family: "pytorch",
        title: "Dangerous call in TorchScript code",
        meaning: "Embedded TorchScript code or Python IR contains code execution or subprocess invocations.",
        why_it_matters: "TorchScript models can contain executable script code that executes upon loading if jit code execution is triggered.",
        remediation: "Quarantine the model and audit the embedded code.",
        limitations: "Static AST analysis of Python/TorchScript code.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TORCHSCRIPT-STRUCTURAL",
        rule_version: 1,
        detector_family: "pytorch",
        title: "TorchScript model structural analysis",
        meaning: "TorchScript code members, constants, and IR structures were inspected statically.",
        why_it_matters: "Confirms TorchScript container structure without invoking torch.jit.load.",
        remediation: "No remediation required.",
        limitations: "Zero runtime execution.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TORCHPACKAGE-EXEC",
        rule_version: 1,
        detector_family: "pytorch",
        title: "Dangerous call in torch.package",
        meaning: "Embedded Python code in a torch.package container invokes subprocesses, eval, or OS execution.",
        why_it_matters: "torch.package bundles complete Python modules that execute when imported.",
        remediation: "Quarantine package and audit embedded modules before importing.",
        limitations: "Static AST analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TORCHPACKAGE-STRUCTURAL",
        rule_version: 1,
        detector_family: "pytorch",
        title: "torch.package structural analysis",
        meaning: "torch.package importer layout and embedded Python resources were statically analyzed.",
        why_it_matters: "Validates package layout without importing untrusted Python modules.",
        remediation: "No remediation required.",
        limitations: "Zero runtime execution.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-OPENVINO-MALFORMED",
        rule_version: 1,
        detector_family: "openvino",
        title: "Malformed OpenVINO XML graph",
        meaning: "OpenVINO IR XML graph failed parsing or lacks root '<net>' element.",
        why_it_matters: "Invalid XML prevents model loading and graph validation.",
        remediation: "Re-export OpenVINO IR model.",
        limitations: "Static XML parsing.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-OPENVINO-XXE",
        rule_version: 1,
        detector_family: "openvino",
        title: "OpenVINO XML DTD or ENTITY construct",
        meaning: "OpenVINO XML graph contains DTD or ENTITY definitions.",
        why_it_matters: "XML external entity expansion (XXE) can cause arbitrary file read or SSRF attacks.",
        remediation: "Strip DTD and ENTITY definitions from XML graph.",
        limitations: "Static XML scanning.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-OPENVINO-SIDECAR-VALID",
        rule_version: 1,
        detector_family: "openvino",
        title: "OpenVINO weight sidecar verified",
        meaning: "OpenVINO weight sidecar .bin file was located and verified.",
        why_it_matters: "Confirms weight sidecar presence and valid file access.",
        remediation: "No remediation required.",
        limitations: "Path and size verification.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-OPENVINO-SIDECAR-UNSAFE",
        rule_version: 1,
        detector_family: "openvino",
        title: "Unsafe OpenVINO weight sidecar access",
        meaning: "Weight sidecar file failed safe opening checks (e.g. symlink escape or unsafe permissions).",
        why_it_matters: "Symlinks or path traversal can lead to unauthorized file reads.",
        remediation: "Fix sidecar path and permissions.",
        limitations: "Safe IO inspection.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-OPENVINO-SIDECAR-MISSING",
        rule_version: 1,
        detector_family: "openvino",
        title: "OpenVINO weight sidecar missing",
        meaning: "The expected weight sidecar .bin file was not found alongside the XML graph.",
        why_it_matters: "Incomplete OpenVINO IR compound package cannot be loaded.",
        remediation: "Supply the missing .bin weight sidecar file.",
        limitations: "Directory existence check.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-OPENVINO-STRUCTURAL",
        rule_version: 1,
        detector_family: "openvino",
        title: "OpenVINO IR structural analysis",
        meaning: "OpenVINO IR XML graph was verified statically with XXE protection.",
        why_it_matters: "Confirms graph XML structure and safe sidecar linkage.",
        remediation: "No remediation required.",
        limitations: "Static XML parsing.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TENSORRT-TRUNCATED",
        rule_version: 1,
        detector_family: "tensorrt",
        title: "Truncated TensorRT engine",
        meaning: "The TensorRT engine file is smaller than minimum header size.",
        why_it_matters: "Truncated serialized engines fail initialization.",
        remediation: "Re-serialize the TensorRT engine.",
        limitations: "Header length check.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TENSORRT-INVALID-MAGIC",
        rule_version: 1,
        detector_family: "tensorrt",
        title: "Unrecognized TensorRT engine header magic",
        meaning: "The file extension claims TensorRT engine but header magic is missing or non-standard.",
        why_it_matters: "Format claim mismatch or custom serialization version.",
        remediation: "Verify TensorRT engine export settings.",
        limitations: "Defensible header check.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TENSORRT-OPAQUE",
        rule_version: 1,
        detector_family: "tensorrt",
        title: "TensorRT engine explicit capability limitation",
        meaning: "TensorRT engine header and executable payload were verified; execution graph remains opaque.",
        why_it_matters: "TensorRT engine layout is non-public; Layerfault states explicitly what is verified.",
        remediation: "No remediation required.",
        limitations: "Defensible checks only; graph logic opaque.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-COREML-PATH-TRAVERSAL",
        rule_version: 1,
        detector_family: "coreml",
        title: "Core ML path traversal reference",
        meaning: "Core ML .mlmodel contains absolute or parent directory path references.",
        why_it_matters: "Unsafe path references can allow directory traversal when weights are loaded.",
        remediation: "Sanitize weight paths in Core ML model export.",
        limitations: "Protobuf string field extraction.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-COREML-CUSTOM",
        rule_version: 1,
        detector_family: "coreml",
        title: "Core ML custom layer/plugin reference",
        meaning: "Core ML model references custom layer or C++ plugin implementations.",
        why_it_matters: "Custom layers require external code execution.",
        remediation: "Audit custom layer implementations before deployment.",
        limitations: "Static Protobuf parsing.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-COREML-STRUCTURAL",
        rule_version: 1,
        detector_family: "coreml",
        title: "Core ML structural analysis",
        meaning: "Core ML model Protobuf fields were statically parsed.",
        why_it_matters: "Validates model structure with zero runtime execution.",
        remediation: "No remediation required.",
        limitations: "Zero runtime execution.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-COREML-PACKAGE-VALID",
        rule_version: 1,
        detector_family: "coreml",
        title: "Core ML package Manifest.json verified",
        meaning: "Core ML .mlpackage Manifest.json was safely opened and verified.",
        why_it_matters: "Confirms package structure and manifest integrity.",
        remediation: "No remediation required.",
        limitations: "Package metadata inspection.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-COREML-PACKAGE-UNSAFE",
        rule_version: 1,
        detector_family: "coreml",
        title: "Unsafe Core ML package Manifest.json",
        meaning: "Core ML package Manifest.json failed safe opening checks.",
        why_it_matters: "Unsafe permissions or symlink escapes in package manifests.",
        remediation: "Fix manifest file permissions.",
        limitations: "Safe IO inspection.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-COREML-PACKAGE-MISSING-MANIFEST",
        rule_version: 1,
        detector_family: "coreml",
        title: "Core ML package missing Manifest.json",
        meaning: "Core ML .mlpackage directory lacks mandatory Manifest.json file.",
        why_it_matters: "Incomplete package structure.",
        remediation: "Re-create Core ML package manifest.",
        limitations: "Directory existence check.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-MLX-CUSTOM-CODE",
        rule_version: 1,
        detector_family: "mlx",
        title: "MLX package custom Python code",
        meaning: "MLX model package contains custom architecture Python code.",
        why_it_matters: "Custom modeling code executes when the model is loaded in Python.",
        remediation: "Audit custom modeling Python files.",
        limitations: "Static file discovery.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-MLX-PROFILE-VALID",
        rule_version: 1,
        detector_family: "mlx",
        title: "MLX package profile verified",
        meaning: "MLX package structure contains required Safetensors weights and JSON config.",
        why_it_matters: "Confirms valid MLX model package convention.",
        remediation: "No remediation required.",
        limitations: "Package profile check.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-MLX-PROFILE-INCOMPLETE",
        rule_version: 1,
        detector_family: "mlx",
        title: "Incomplete MLX package profile",
        meaning: "MLX package directory is missing model.safetensors or config.json.",
        why_it_matters: "Incomplete model package profile.",
        remediation: "Supply missing weight or config files.",
        limitations: "Package file check.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TOKENIZER-EOS-BOS-CONFLICT",
        rule_version: 1,
        detector_family: "tokenizer_security",
        title: "Tokenizer Eos Bos Conflict",
        meaning: "Tokenizer BOS/EOS definitions conflict in a way that can alter prompt or role boundaries.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TOKENIZER-HIDDEN-PROMPT",
        rule_version: 1,
        detector_family: "tokenizer_security",
        title: "Tokenizer Hidden Prompt",
        meaning: "Layerfault observed the security condition represented by LF-TOKENIZER-HIDDEN-PROMPT.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TOKENIZER-ROLE-BOUNDARY-CONTROL",
        rule_version: 1,
        detector_family: "tokenizer_security",
        title: "Tokenizer Role Boundary Control",
        meaning: "Layerfault observed the security condition represented by LF-TOKENIZER-ROLE-BOUNDARY-CONTROL.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TOKENIZER-ROLE-REMAP",
        rule_version: 1,
        detector_family: "tokenizer_security",
        title: "Tokenizer Role Remap",
        meaning: "Tokenizer or chat-template semantics remap a security-relevant conversation role.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TOKENIZER-SECURITY-DELTA",
        rule_version: 1,
        detector_family: "tokenizer_security",
        title: "Tokenizer Security Delta",
        meaning: "Security-relevant tokenizer semantics differ between compared artifacts.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TOKENIZER-SPECIAL-TOKEN-CONFLICT",
        rule_version: 1,
        detector_family: "tokenizer_security",
        title: "Tokenizer Special Token Conflict",
        meaning: "Layerfault observed the security condition represented by LF-TOKENIZER-SPECIAL-TOKEN-CONFLICT.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TOKENIZER-SPECIAL-TOKEN-SPOOFABLE",
        rule_version: 1,
        detector_family: "tokenizer_security",
        title: "Special token smuggling via plain vocabulary entry",
        meaning: "A plain (non-special) vocabulary entry's literal string exactly matches a declared role-boundary special token (e.g. a turn/role marker like a chat-template delimiter).",
        why_it_matters: "If the runtime's prompt assembly does not otherwise prevent it, content that decodes to this ordinary token can render identically to a genuine role-boundary marker, letting untrusted input forge what looks like a new conversation turn — 'special token smuggling'.",
        remediation: "Remove the colliding plain-vocabulary entry, or ensure the runtime's prompt assembly escapes/rejects role-boundary literal strings appearing in untrusted content regardless of which token id produced them.",
        limitations: "This is an exact literal-string match only; Unicode-confusable or homoglyph near-matches of the special token's string are not detected here.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TOKENIZER-TOOL-TEMPLATE-RISK",
        rule_version: 1,
        detector_family: "tokenizer_security",
        title: "Tokenizer Tool Template Risk",
        meaning: "Layerfault observed the security condition represented by LF-TOKENIZER-TOOL-TEMPLATE-RISK.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TOKENIZER-UNICODE-CONTROL",
        rule_version: 1,
        detector_family: "tokenizer_security",
        title: "Tokenizer Unicode Control",
        meaning: "Layerfault observed the security condition represented by LF-TOKENIZER-UNICODE-CONTROL.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
