    RuleMetadata {
        rule_id: "LF-ADMISSION-RECEIPT-COMPOSITION-MISMATCH",
        rule_version: 1,
        detector_family: "admission",
        title: "Model composition differs from signed admission receipt",
        meaning: "Current execution identity does not match the security-relevant context bound into a signed admission receipt.",
        why_it_matters: "Admission authorizes an exact executable context; a material identity change invalidates the prior decision.",
        remediation: "Re-scan the changed component and issue a new admission receipt only after current policy permits the new execution context.",
        limitations: "Identity mismatch establishes drift from the approved context but does not determine why the change occurred.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ADMISSION-RECEIPT-RUNTIME-CONFIG-MISMATCH",
        rule_version: 1,
        detector_family: "admission",
        title: "Runtime configuration differs from signed admission receipt",
        meaning: "Current execution identity does not match the security-relevant context bound into a signed admission receipt.",
        why_it_matters: "Admission authorizes an exact executable context; a material identity change invalidates the prior decision.",
        remediation: "Re-scan the changed component and issue a new admission receipt only after current policy permits the new execution context.",
        limitations: "Identity mismatch establishes drift from the approved context but does not determine why the change occurred.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ADMISSION-RECEIPT-AGENT-MISMATCH",
        rule_version: 1,
        detector_family: "admission",
        title: "Agent identity differs from signed admission receipt",
        meaning: "Current execution identity does not match the security-relevant context bound into a signed admission receipt.",
        why_it_matters: "Admission authorizes an exact executable context; a material identity change invalidates the prior decision.",
        remediation: "Re-scan the changed component and issue a new admission receipt only after current policy permits the new execution context.",
        limitations: "Identity mismatch establishes drift from the approved context but does not determine why the change occurred.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ADMISSION-RECEIPT-CAPABILITY-MISMATCH",
        rule_version: 1,
        detector_family: "admission",
        title: "Capability graph differs from signed admission receipt",
        meaning: "Current execution identity does not match the security-relevant context bound into a signed admission receipt.",
        why_it_matters: "Admission authorizes an exact executable context; a material identity change invalidates the prior decision.",
        remediation: "Re-scan the changed component and issue a new admission receipt only after current policy permits the new execution context.",
        limitations: "Identity mismatch establishes drift from the approved context but does not determine why the change occurred.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ADMISSION-RECEIPT-MCP-MISMATCH",
        rule_version: 1,
        detector_family: "admission",
        title: "MCP server set differs from signed admission receipt",
        meaning: "Current execution identity does not match the security-relevant context bound into a signed admission receipt.",
        why_it_matters: "Admission authorizes an exact executable context; a material identity change invalidates the prior decision.",
        remediation: "Re-scan the changed component and issue a new admission receipt only after current policy permits the new execution context.",
        limitations: "Identity mismatch establishes drift from the approved context but does not determine why the change occurred.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TRUST-SECURITY-DRIFT",
        rule_version: 1,
        detector_family: "continuous_trust",
        title: "Security-relevant execution drift",
        meaning: "One or more identity-bound execution components changed after a prior snapshot.",
        why_it_matters: "A previous decision applies only to the exact composition, runtime and capability state it evaluated.",
        remediation: "Re-evaluate only the evidence domains invalidated by the changed components before continuing execution.",
        limitations: "This finding records bounded static evidence and does not establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TRUST-EVIDENCE-STALE",
        rule_version: 1,
        detector_family: "continuous_trust",
        title: "Approved evidence became stale",
        meaning: "A previously approved or conditionally approved execution state now depends on evidence invalidated by drift.",
        why_it_matters: "Continuing to rely on stale evidence can authorize a materially different executable system.",
        remediation: "Move the subject to review and regenerate the invalidated evidence before restoring approval.",
        limitations: "This finding records bounded static evidence and does not establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-HF-LFS-DIGEST-MISMATCH",
        rule_version: 1,
        detector_family: "integrity",
        title: "Hugging Face LFS digest mismatch",
        meaning: "Observed download SHA-256 does not match the content-addressed LFS OID declared in the Hugging Face Hub revision metadata.",
        why_it_matters: "The bytes on disk do not match the content-addressed LFS object declared by the Hugging Face Hub revision, indicating corrupted transmission or server-side tampering.",
        remediation: "Block the member and reacquire from a trusted revision. Do not use the staged bytes.",
        limitations: "Layerfault verifies content against the Hub's declared LFS metadata. It does not establish how or why the remote metadata or downloaded bytes differed.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-HF-LFS-INTEGRITY",
        rule_version: 1,
        detector_family: "integrity",
        title: "Hugging Face LFS integrity verified",
        meaning: "Downloaded Hugging Face Hub member matched the exact expected size and cryptographic OID declared in the revision metadata.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "No action required for remote LFS integrity; proceed with static package scanning.",
        limitations: "Remote LFS verification establishes byte identity against the Hub revision metadata; it does not attest to the safety or functionality of tensor weights or code.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-HF-LFS-METADATA-INVALID",
        rule_version: 1,
        detector_family: "integrity",
        title: "Hugging Face LFS metadata invalid",
        meaning: "Hugging Face Hub LFS metadata is malformed, uses an invalid hex digest, or conflicts with repository file metadata.",
        why_it_matters: "Malformed or contradictory LFS metadata prevents cryptographic validation of remote repository members prior to execution/analysis.",
        remediation: "Reject the metadata and re-inspect the remote revision before attempting acquisition.",
        limitations: "Layerfault verifies content against the Hub's declared LFS metadata. It does not establish how or why the remote metadata or downloaded bytes differed.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-HF-LFS-SIZE-MISMATCH",
        rule_version: 1,
        detector_family: "integrity",
        title: "Hugging Face LFS size mismatch",
        meaning: "Observed byte count differs from the declared size in the Hugging Face Hub LFS metadata.",
        why_it_matters: "The bytes on disk do not match the content-addressed LFS object declared by the Hugging Face Hub revision, indicating corrupted transmission or server-side tampering.",
        remediation: "Block the member and reacquire the file. Verify network integrity and download limits.",
        limitations: "Layerfault verifies content against the Hub's declared LFS metadata. It does not establish how or why the remote metadata or downloaded bytes differed.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-HF-REMOTE-HASH-UNAVAILABLE",
        rule_version: 1,
        detector_family: "integrity",
        title: "Hugging Face remote hash expectation unavailable",
        meaning: "The Hugging Face Hub repository member does not carry Git LFS metadata or an explicit remote object hash expectation in the Hub API response.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Verify the member against local package security policy and commit SHA bindings.",
        limitations: "Remote LFS verification establishes byte identity against the Hub revision metadata; it does not attest to the safety or functionality of tensor weights or code.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-INTEGRITY-DIGEST-MISMATCH",
        rule_version: 1,
        detector_family: "integrity",
        title: "Content digest mismatch",
        meaning: "The digest recomputed while streaming the blob does not match the digest declared in the manifest.",
        why_it_matters: "The bytes on disk are not the bytes the manifest declares, so no signature, review or prior assessment applies to them.",
        remediation: "Reject the artifact and reacquire it from a trusted source; do not trust prior assessments of the declared digest.",
        limitations: "Layerfault reports only the values it measured. It does not establish how or why the artifact differs from its declaration.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-INTEGRITY-SIZE-MISMATCH",
        rule_version: 1,
        detector_family: "integrity",
        title: "Content size mismatch",
        meaning: "The blob's actual byte length does not match the size declared in the manifest.",
        why_it_matters: "The bytes on disk are not the bytes the manifest declares, so no signature, review or prior assessment applies to them.",
        remediation: "Reject the artifact and reacquire it from a trusted source.",
        limitations: "Layerfault reports only the values it measured. It does not establish how or why the artifact differs from its declaration.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-INTEGRITY-VERIFIED",
        rule_version: 1,
        detector_family: "integrity",
        title: "Content digest verified",
        meaning: "The recomputed digest matches the manifest's declared digest for this blob.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "No action is required unless policy independently blocks the artifact.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BINDING-PACKAGE-MUTATED",
        rule_version: 1,
        detector_family: "binding",
        title: "Package member mutated during staging",
        meaning: "A package member file changed in size or Sha256 digest between admission inspection and staging copy creation.",
        why_it_matters: "A file modification during staging violates TOCTOU guarantees and indicates package tampering or active host mutation.",
        remediation: "Investigate processes writing to the package directory and ensure package source files remain immutable during admission.",
        limitations: "Detects mutations occurring between admission inspection and safe copy streaming; does not prevent host OS root kernel modifications.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BINDING-REVALIDATION-FAILED",
        rule_version: 1,
        detector_family: "binding",
        title: "Staged package pre-launch revalidation failed",
        meaning: "The staged package fingerprint or member digest check failed immediately before runtime launch.",
        why_it_matters: "An altered staged package would allow unverified bytes to be loaded into the sandboxed model execution environment.",
        remediation: "Re-admit the package and check for host process interference in staging directories.",
        limitations: "Revalidation verifies staged member hashes and package fingerprint; it relies on filesystem read-only permissions.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BINDING-SYMLINK-REFUSED",
        rule_version: 1,
        detector_family: "binding",
        title: "Symlink package member refused",
        meaning: "A package member or root is a symbolic link, which is refused by strong verify-to-execute package binding.",
        why_it_matters: "Symlinks introduce path substitution and filesystem escape vulnerabilities that break static verify-to-execute guarantees.",
        remediation: "Provide real package directories and files without symlinks for strong execution binding.",
        limitations: "Package staging strictly refuses symlinks to guarantee immutable byte binding.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-BINDING-UNBOUND-RESOURCE",
        rule_version: 1,
        detector_family: "binding",
        title: "Unbound package resource attempt",
        meaning: "An active runtime attempted to fetch or access un-staged network/cache paths during execution.",
        why_it_matters: "Unbound resources bypass static package admission and could introduce uninspected code or weight payloads.",
        remediation: "Ensure all required model, config, tokenizer, and adapter components are fully included in the staged package.",
        limitations: "Enforced via network isolation and local-only environment variables inside the strong sandbox.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-RUNTIME-ADVISORY-CLEAR",
        rule_version: 1,
        detector_family: "advisory",
        title: "Runtime security finding",
        meaning: "The configured runtime version/advisory state could not be established as clear under the local security catalog.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Upgrade or verify the runtime before using it to execute untrusted models.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-RUNTIME-ADVISORY-MATCH",
        rule_version: 1,
        detector_family: "advisory",
        title: "Runtime affected by a known advisory",
        meaning: "The detected runtime version falls within a bundled advisory's affected version range.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Upgrade the runtime to or beyond the advisory's fixed boundary before use.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-RUNTIME-ADVISORY-STALE",
        rule_version: 1,
        detector_family: "advisory",
        title: "Runtime security finding",
        meaning: "The configured runtime version/advisory state could not be established as clear under the local security catalog.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Upgrade or verify the runtime before using it to execute untrusted models.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-RUNTIME-VERSION-UNKNOWN",
        rule_version: 1,
        detector_family: "advisory",
        title: "Runtime version could not be compared",
        meaning: "Layerfault could not derive a version/build identifier suitable for its offline vulnerability catalog.",
        why_it_matters: "A model artifact is parsed by a runtime; a runtime with a known parsing vulnerability turns a malformed artifact into an exploit primitive.",
        remediation: "Use an official runtime build with machine-readable version output or verify the runtime version manually before admitting untrusted models.",
        limitations: "Version comparison against an advisory range does not establish that the vulnerable code path is reachable in your configuration.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-SCAN-ERROR",
        rule_version: 1,
        detector_family: "scanner",
        title: "Scanner error",
        meaning: "Layerfault could not safely complete inspection of an artifact.",
        why_it_matters: "An inspection that did not complete cannot support an admission decision, and failing open would let unexamined content through.",
        remediation: "Treat the model as blocked. Preserve the artifact and investigate the parser/I/O error rather than suppressing it.",
        limitations: "This reports a failure to inspect, not a property of the artifact. The artifact may be benign.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-UNCLASSIFIED",
        rule_version: 1,
        detector_family: "scanner",
        title: "Layerfault security finding",
        meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the finding evidence and follow the configured policy before deployment.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-INTEL-IDENTITY-REVOKED",
        rule_version: 1,
        detector_family: "intelligence",
        title: "Security identity revoked",
        meaning: "Signed security intelligence explicitly revokes an identity used by the current execution context.",
        why_it_matters: "A previously trusted model, adapter, signer, passport, runtime release or builder can become unacceptable after compromise or withdrawal.",
        remediation: "Stop using the revoked identity, obtain a non-revoked replacement, refresh intelligence and repeat admission.",
        limitations: "The finding establishes that the signed intelligence record applies to the observed identity; it does not determine the underlying incident cause.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-INTEL-ADAPTER-INDICATOR",
        rule_version: 1,
        detector_family: "intelligence",
        title: "Adapter security intelligence match",
        meaning: "The exact adapter digest matches a signed security intelligence record with a suspicious, malicious, revoked or compromised disposition.",
        why_it_matters: "Adapters are executable model-composition inputs and can invalidate trust in an otherwise approved base model.",
        remediation: "Remove or replace the indicated adapter and repeat composition analysis and admission with current intelligence.",
        limitations: "The finding is scoped to the exact adapter digest represented by the intelligence record.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-INTEL-BUILDER-INDICATOR",
        rule_version: 1,
        detector_family: "intelligence",
        title: "Builder security intelligence match",
        meaning: "A transformation builder identity matches a signed security intelligence record with a suspicious, malicious, revoked or compromised disposition.",
        why_it_matters: "A compromised or malicious builder can invalidate otherwise well-formed provenance for transformed model artifacts.",
        remediation: "Reproduce the artifact through an approved builder and verify the complete signed transformation chain before admission.",
        limitations: "The finding evaluates the builder identity represented in provenance; it does not independently inspect the builder environment.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-INTEL-PACK-EXPIRED",
        rule_version: 1,
        detector_family: "intelligence",
        title: "Intelligence pack expired",
        meaning: "The selected security intelligence pack is past its explicit expiry.",
        why_it_matters: "Admission decisions must use authenticated, non-rollback security intelligence.",
        remediation: "Use a current signed Layerfault intelligence pack from the expected signer and re-run admission.",
        limitations: "This finding describes intelligence trust/freshness state; it does not by itself prove a model is malicious.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-INTEL-PACK-STALE",
        rule_version: 1,
        detector_family: "intelligence",
        title: "Intelligence pack stale",
        meaning: "The selected security intelligence pack is older than Layerfault freshness expectations.",
        why_it_matters: "Admission decisions must use authenticated, non-rollback security intelligence.",
        remediation: "Use a current signed Layerfault intelligence pack from the expected signer and re-run admission.",
        limitations: "This finding describes intelligence trust/freshness state; it does not by itself prove a model is malicious.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-INTEL-PACK-ROLLBACK",
        rule_version: 1,
        detector_family: "intelligence",
        title: "Intelligence rollback detected",
        meaning: "The selected intelligence pack sequence or digest conflicts with a previously accepted pack.",
        why_it_matters: "Admission decisions must use authenticated, non-rollback security intelligence.",
        remediation: "Use a current signed Layerfault intelligence pack from the expected signer and re-run admission.",
        limitations: "This finding describes intelligence trust/freshness state; it does not by itself prove a model is malicious.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-INTEL-PACK-SIGNATURE",
        rule_version: 1,
        detector_family: "intelligence",
        title: "Intelligence signature invalid",
        meaning: "The external intelligence pack did not pass detached Ed25519 signature verification.",
        why_it_matters: "Admission decisions must use authenticated, non-rollback security intelligence.",
        remediation: "Use a current signed Layerfault intelligence pack from the expected signer and re-run admission.",
        limitations: "This finding describes intelligence trust/freshness state; it does not by itself prove a model is malicious.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ADMISSION-RECEIPT-ARTIFACT-MISMATCH",
        rule_version: 1,
        detector_family: "admission_gate",
        title: "Admission Receipt Artifact Mismatch",
        meaning: "The artifact presented for execution does not match the identity bound into the signed admission receipt.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ADMISSION-RECEIPT-INTELLIGENCE-MISMATCH",
        rule_version: 1,
        detector_family: "admission_gate",
        title: "Admission Receipt Intelligence Mismatch",
        meaning: "The selected security intelligence differs from the intelligence bound into the admission receipt.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ADMISSION-RECEIPT-RULESET-MISMATCH",
        rule_version: 1,
        detector_family: "admission_gate",
        title: "Admission Receipt Ruleset Mismatch",
        meaning: "The current Layerfault ruleset differs from the ruleset bound into the admission receipt.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ADMISSION-RECEIPT-RUNTIME-MISMATCH",
        rule_version: 1,
        detector_family: "admission_gate",
        title: "Admission Receipt Runtime Mismatch",
        meaning: "The runtime executable presented for execution does not match the signed admission receipt.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ASSURANCE-PICKLE-DIFFERENTIAL",
        rule_version: 1,
        detector_family: "scanner_assurance",
        title: "Assurance Pickle Differential",
        meaning: "Independent Pickle structural parsers disagreed on the opcode stream or parse boundary.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-ASSURANCE-PICKLE-UNRESOLVED-EXECUTION",
        rule_version: 1,
        detector_family: "scanner_assurance",
        title: "Assurance Pickle Unresolved Execution",
        meaning: "Layerfault observed the security condition represented by LF-ASSURANCE-PICKLE-UNRESOLVED-EXECUTION.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PASSPORT-INCOMPLETE",
        rule_version: 1,
        detector_family: "security_passport",
        title: "Passport Incomplete",
        meaning: "The model security passport is missing one or more requested assurance components.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "Incomplete coverage means unobserved conditions remain unknown; it must not be interpreted as a clean result.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PICKLE-PERSISTENT-ID",
        rule_version: 1,
        detector_family: "scanner_assurance",
        title: "Pickle Persistent Id",
        meaning: "Pickle persistent-ID semantics were observed and require resolver-aware review.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
