    RuleMetadata {
        rule_id: "LF-CODE-AUTO-MAP",
        rule_version: 1,
        detector_family: "python-static",
        title: "Custom Hugging Face model code mapping",
        meaning: "Model metadata contains auto_map, which can route model loading through custom Python implementations.",
        why_it_matters: "Model metadata can route compatible Hugging Face loading paths through publisher-supplied Python that executes with the permissions of the inference process.",
        remediation: "Review the referenced source files and avoid trust_remote_code unless the package publisher and exact package identity are trusted.",
        limitations: "The presence of a custom-code mapping does not establish that the referenced code is malicious, nor that any particular loader will execute it.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-CODE-CTYPES",
        rule_version: 1,
        detector_family: "python-static",
        title: "Layerfault security finding",
        meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.",
        why_it_matters: "Loading native libraries moves execution outside Python's inspection surface, where neither Layerfault nor a Python-level reviewer can follow it.",
        remediation: "Review the finding evidence and follow the configured policy before deployment.",
        limitations: "Static presence of this primitive does not prove that the code path is reachable, that it executes during model loading, or that its use is malicious. Layerfault did not execute the code.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-CODE-EVAL",
        rule_version: 1,
        detector_family: "python-static",
        title: "Layerfault security finding",
        meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.",
        why_it_matters: "Dynamic evaluation lets code that is not visible in the shipped source be constructed and run at load time, defeating static review of the package.",
        remediation: "Review the finding evidence and follow the configured policy before deployment.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-CODE-EXEC",
        rule_version: 1,
        detector_family: "python-static",
        title: "Layerfault security finding",
        meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.",
        why_it_matters: "Dynamic evaluation lets code that is not visible in the shipped source be constructed and run at load time, defeating static review of the package.",
        remediation: "Review the finding evidence and follow the configured policy before deployment.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-CODE-IMPORT-SIDE-EFFECT",
        rule_version: 1,
        detector_family: "python-static",
        title: "Layerfault security finding",
        meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.",
        why_it_matters: "Module-level statements run on import, so the code executes merely by loading the model rather than by an explicit call.",
        remediation: "Review the finding evidence and follow the configured policy before deployment.",
        limitations: "Static presence of this primitive does not prove that the code path is reachable, that it executes during model loading, or that its use is malicious. Layerfault did not execute the code.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-CODE-NETWORK",
        rule_version: 1,
        detector_family: "python-static",
        title: "Layerfault security finding",
        meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.",
        why_it_matters: "Outbound network capability in loading-path code can fetch further payloads or send local data off the host during model loading.",
        remediation: "Review the finding evidence and follow the configured policy before deployment.",
        limitations: "Static presence of this primitive does not prove that the code path is reachable, that it executes during model loading, or that its use is malicious. Layerfault did not execute the code.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-CODE-OS-SYSTEM",
        rule_version: 1,
        detector_family: "python-static",
        title: "Layerfault security finding",
        meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.",
        why_it_matters: "Code executed during model loading with process-execution capability inherits the privileges of the inference process and can reach the surrounding host.",
        remediation: "Review the finding evidence and follow the configured policy before deployment.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-CODE-REMOTE-TRUST",
        rule_version: 1,
        detector_family: "python-static",
        title: "Remote/custom code trust enabled",
        meaning: "The package explicitly enables a custom-code trust path.",
        why_it_matters: "Enabling remote code removes the loader's refusal to execute publisher-supplied Python, so package code runs as part of loading the model.",
        remediation: "Disable remote-code trust where possible and inspect/sign the full model package before loading custom implementations.",
        limitations: "The presence of a custom-code mapping does not establish that the referenced code is malicious, nor that any particular loader will execute it.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-CODE-SUBPROCESS",
        rule_version: 1,
        detector_family: "python-static",
        title: "Layerfault security finding",
        meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.",
        why_it_matters: "Code executed during model loading with process-execution capability inherits the privileges of the inference process and can reach the surrounding host.",
        remediation: "Review the finding evidence and follow the configured policy before deployment.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-CORR-HF-LOADER-CREDENTIALS",
        rule_version: 1,
        detector_family: "python-static",
        title: "Custom loader routes to credential access",
        meaning: "Hugging Face auto_map metadata resolves to a module that a reachability-aware call-site analysis confirms accesses credentials/environment.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the referenced loading path before allowing custom code.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-CORR-HF-LOADER-DYNAMIC-CODE",
        rule_version: 1,
        detector_family: "python-static",
        title: "Custom loader routes to dynamic code evaluation",
        meaning: "Hugging Face auto_map metadata resolves to a module that a reachability-aware call-site analysis confirms contains dynamic code evaluation.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the referenced loading path before allowing custom code.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-CORR-HF-LOADER-FILESYSTEM",
        rule_version: 1,
        detector_family: "python-static",
        title: "Custom loader routes to filesystem mutation",
        meaning: "Hugging Face auto_map metadata resolves to a module that a reachability-aware call-site analysis confirms mutates the filesystem.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the referenced loading path before allowing custom code.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-CORR-HF-LOADER-INSTALL",
        rule_version: 1,
        detector_family: "python-static",
        title: "Custom loader routes to package installation",
        meaning: "Hugging Face auto_map metadata resolves to a module that a reachability-aware call-site analysis confirms installs additional code.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the referenced loading path before allowing custom code.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-CORR-HF-LOADER-NATIVE-LOAD",
        rule_version: 1,
        detector_family: "python-static",
        title: "Custom loader routes to native library loading",
        meaning: "Hugging Face auto_map metadata resolves to a module that a reachability-aware call-site analysis confirms loads native libraries.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the referenced loading path before allowing custom code.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-CORR-HF-LOADER-NETWORK",
        rule_version: 1,
        detector_family: "python-static",
        title: "Custom loader routes to network access",
        meaning: "Hugging Face auto_map metadata resolves to a module that a reachability-aware call-site analysis confirms contains network access.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the referenced loading path before allowing custom code.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-CORR-HF-LOADER-PROCESS",
        rule_version: 1,
        detector_family: "python-static",
        title: "Custom loader routes to process execution",
        meaning: "Hugging Face auto_map metadata resolves to a module that a reachability-aware call-site analysis confirms contains process-execution capability.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the referenced loading path before allowing custom code.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PICKLE-DANGEROUS-GLOBAL",
        rule_version: 1,
        detector_family: "pickle-static",
        title: "Dangerous pickle callable",
        meaning: "Static opcode analysis resolved a pickle global/callable associated with code execution or another explicitly dangerous primitive.",
        why_it_matters: "A pickle stream that references a code-execution callable will invoke it when an unsafe loader reconstructs the object graph.",
        remediation: "Block the artifact. Review the named global and provenance without deserializing the pickle.",
        limitations: "Evidence comes solely from bounded static opcode disassembly; Layerfault never deserialized the stream. A resolved reference does not prove any loader reaches it.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PICKLE-MALFORMED",
        rule_version: 1,
        detector_family: "pickle-static",
        title: "Malformed pickle opcode stream",
        meaning: "The bounded protocol 0-5 opcode disassembler could not safely parse the pickle stream or container.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Reject the artifact and reacquire it from a trusted source; do not attempt to unpickle it to diagnose the failure.",
        limitations: "Layerfault stopped at the first unsafe condition rather than attempting recovery, so the remainder of the stream is uncharacterised.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PICKLE-PARSER-DISAGREEMENT",
        rule_version: 1,
        detector_family: "pickle-static",
        title: "Pickle parser differential disagreement",
        meaning: "The primary pickle opcode disassembler and an independently authored structural reader produced different results for the same byte stream: one accepted where the other rejected, or their accepted transcripts diverge.",
        why_it_matters: "Two correctly implemented readers that fully understand a byte stream should describe it identically. A disagreement can indicate a parser-confusion or evasion attempt targeting the primary disassembler, or a byte stream deliberately structured to be ambiguous.",
        remediation: "Review the artifact and its provenance before admission. Do not attempt to resolve the disagreement by unpickling the stream.",
        limitations: "This finding does not determine which reader is correct, only that they disagree. It is bounded static structural comparison and does not establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PICKLE-PARSER-ASSURANCE-INCOMPLETE",
        rule_version: 1,
        detector_family: "pickle-static",
        title: "Pickle parser differential assurance incomplete",
        meaning: "The parser-differential comparison for this pickle stream could not reach a verdict, because the primary parser, the independent structural reader, or both encountered an unsupported construct, an unsupported protocol version, an exhausted analysis budget, or a configured bound.",
        why_it_matters: "This describes a limitation of Layerfault's own assurance coverage, not a property of the artifact. It must not be read as evidence of malformed, evasive, or unsafe content.",
        remediation: "No artifact action is implied. Operators requiring complete differential assurance before admission should configure policy to treat incomplete coverage as a review condition.",
        limitations: "This finding intentionally carries no claim about the artifact. It reports only that Layerfault's differential assurance pass did not complete for this stream.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PICKLE-OPAQUE-COMPRESSED",
        rule_version: 1,
        detector_family: "pickle-static",
        title: "Opaque compressed pickle",
        meaning: "A pickle/joblib/PyTorch serialization name is hidden behind compression Layerfault does not transparently decode in this pass.",
        why_it_matters: "Code-capable serialization formats execute code during deserialization by design, so their contents are as trusted as the publisher.",
        remediation: "Review or unpack it only in an isolated workflow, then scan the decompressed artifact before loading.",
        limitations: "Opacity is the finding: Layerfault establishes that it could not review the content, not that the content is harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PICKLE-OPAQUE-CONTAINER",
        rule_version: 1,
        detector_family: "pickle-static",
        title: "Opaque pickle container",
        meaning: "A PyTorch-style ZIP container was recognized but contained no analyzable pickle member.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the container layout and provenance before loading it.",
        limitations: "Opacity is the finding: Layerfault establishes that it could not review the content, not that the content is harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PICKLE-SAFE-GLOBALS",
        rule_version: 1,
        detector_family: "pickle-static",
        title: "Allowlisted pickle globals",
        meaning: "The pickle opcode stream parsed successfully and every resolved global matched the reviewed checkpoint allowlist.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Preserve the audit evidence. This structural PASS does not make Python pickle a generally safe deserialization mechanism.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PICKLE-UNKNOWN-GLOBAL",
        rule_version: 1,
        detector_family: "pickle-static",
        title: "Unknown pickle global",
        meaning: "Static opcode analysis resolved a module/class global that is neither on Layerfault's reviewed checkpoint allowlist nor its explicit danger list.",
        why_it_matters: "An unreviewed global means Layerfault cannot establish that reconstructing the object graph is limited to data.",
        remediation: "Treat the artifact as opaque and review the exact named class/module and publisher before loading it.",
        limitations: "Evidence comes solely from bounded static opcode disassembly; Layerfault never deserialized the stream. A resolved reference does not prove any loader reaches it.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PY-CALL-DYNAMIC-CODE",
        rule_version: 1,
        detector_family: "python-static",
        title: "Semantic dynamic-code-evaluation call site",
        meaning: "AST-level analysis resolved a call to eval/exec or an equivalent dynamic-evaluation primitive.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the referenced call site; dynamic evaluation defeats static review of what code actually runs.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PY-CALL-NETWORK",
        rule_version: 1,
        detector_family: "python-static",
        title: "Semantic network-access call site",
        meaning: "AST-level analysis resolved a call to a network primitive at a specific line and execution context.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the referenced call site and destination before permitting custom code.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PY-CALL-PROCESS",
        rule_version: 1,
        detector_family: "python-static",
        title: "Semantic process-execution call site",
        meaning: "AST-level analysis resolved a call to a process-execution primitive at a specific line and execution context.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the referenced call site and its execution context before permitting custom code.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PY-CREDENTIAL-ACCESS",
        rule_version: 1,
        detector_family: "python-static",
        title: "Semantic credential/environment access call site",
        meaning: "AST-level analysis resolved a call that reads environment variables or credential-shaped data.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review why custom loading code needs credential/environment access.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PY-FILESYSTEM-MUTATION",
        rule_version: 1,
        detector_family: "python-static",
        title: "Semantic filesystem-mutation call site",
        meaning: "AST-level analysis resolved a call that writes, moves, or deletes filesystem content.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the referenced call site and target path before permitting custom code.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PY-FLOW-CREDENTIAL-NETWORK",
        rule_version: 1,
        detector_family: "python-static",
        title: "Data flow: Sensitive credential to network sink",
        meaning: "Bounded Python data-flow analysis traced sensitive environment credentials or API tokens into a network request body, query, or header.",
        why_it_matters: "Credentials exfiltrated over network calls allow unauthorized access or identity compromise.",
        remediation: "Audit the source credential access and network sink to ensure credentials are not transmitted to untrusted endpoints.",
        limitations: "Static flow analysis is bounded; complex dynamic aliasing or unsupported data structures may be reported as incomplete.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PY-FLOW-FILE-NETWORK",
        rule_version: 1,
        detector_family: "python-static",
        title: "Data flow: Sensitive file read to network sink",
        meaning: "Bounded Python data-flow analysis traced content read from sensitive files (such as SSH keys, cloud credentials, or system configs) into a network transmission sink.",
        why_it_matters: "Exfiltrating sensitive local files poses an immediate security and confidentiality risk.",
        remediation: "Remove network calls that send file content, or restrict file reading permissions.",
        limitations: "Static flow analysis is bounded; complex dynamic aliasing or unsupported data structures may be reported as incomplete.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PY-FLOW-INPUT-EXEC",
        rule_version: 1,
        detector_family: "python-static",
        title: "Data flow: Untrusted parameter to execution sink",
        meaning: "Bounded Python data-flow analysis traced untrusted function parameters into dynamic code evaluation (eval/exec) or process execution sinks.",
        why_it_matters: "Passing untrusted input directly to execution primitives enables arbitrary code execution or command injection.",
        remediation: "Validate, sanitize, or avoid passing untrusted parameters directly to code or process execution functions.",
        limitations: "Static flow analysis is bounded; complex dynamic aliasing or unsupported data structures may be reported as incomplete.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PY-FLOW-NETWORK-EXEC",
        rule_version: 1,
        detector_family: "python-static",
        title: "Data flow: Network input to execution sink",
        meaning: "Bounded Python data-flow analysis traced data received from network calls directly into eval/exec or process execution sinks.",
        why_it_matters: "Executing unvalidated code or commands received over the network allows remote code execution.",
        remediation: "Do not execute remote payloads dynamically; validate and sign all downloaded assets before execution.",
        limitations: "Static flow analysis is bounded; complex dynamic aliasing or unsupported data structures may be reported as incomplete.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PY-NATIVE-LOAD",
        rule_version: 1,
        detector_family: "python-static",
        title: "Semantic native-library-loading call site",
        meaning: "AST-level analysis resolved a call that loads a native library (ctypes/cdll or equivalent).",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the referenced call site; native code runs outside Python-level inspection.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PY-PACKAGE-INSTALL",
        rule_version: 1,
        detector_family: "python-static",
        title: "Semantic package-installation call site",
        meaning: "AST-level analysis resolved a call that installs or acquires additional code (pip/package manager invocation).",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the referenced call site; installing additional code at load time defeats package review.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PY-SEMANTIC-INCOMPLETE",
        rule_version: 1,
        detector_family: "python-static",
        title: "Semantic Python analysis incomplete",
        meaning: "The AST-level analyzer could not parse the file or exceeded its bounded analysis limits; a streaming textual fallback scan was used instead.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the file manually; semantic call-site/reachability findings for it are unavailable.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PY-TAINT-INCOMPLETE",
        rule_version: 1,
        detector_family: "python-static",
        title: "Python data-flow taint analysis incomplete",
        meaning: "Python data-flow analysis reached depth limits, recursion cycles, state merge bounds, or encountered dynamic call dispatch.",
        why_it_matters: "Static flow analysis could not guarantee complete data-flow coverage for a sensitive source or sink call.",
        remediation: "Review code paths involving dynamic dispatch or deep call hierarchies manually.",
        limitations: "Bounded analysis intentionally stops at configured budget thresholds to remain deterministic and safe.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-SHELL-SEMANTIC-PROCESS",
        rule_version: 1,
        detector_family: "shell-static",
        title: "Semantic shell process-execution call site",
        meaning: "Bounded shell tokenizer analysis resolved a simple command invocation at a specific line and scope (script top-level or function body).",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the referenced command and its execution scope before permitting this script to run.",
        limitations: "The shell tokenizer is bounded and not a full POSIX grammar (see shell_static::parser); confidence is capped lower than the equivalent Python finding.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-SHELL-SEMANTIC-DYNAMIC-CODE",
        rule_version: 1,
        detector_family: "shell-static",
        title: "Semantic shell dynamic-code call site",
        meaning: "Bounded shell tokenizer analysis resolved a call to eval, exec, or source/dot-sourcing (`.`).",
        why_it_matters: "Dynamic evaluation or dot-sourcing runs code that is not visible by reading only the enclosing script.",
        remediation: "Review the referenced call site; dynamic evaluation defeats static review of what code actually runs.",
        limitations: "The shell tokenizer is bounded and not a full POSIX grammar (see shell_static::parser); confidence is capped lower than the equivalent Python finding.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-SHELL-SEMANTIC-CURL-PIPE-SH",
        rule_version: 1,
        detector_family: "shell-static",
        title: "Download piped directly into a shell interpreter",
        meaning: "Bounded shell tokenizer analysis resolved a pipeline where curl/wget output is piped into sh/bash/eval, a well-known supply-chain-attack signature.",
        why_it_matters: "Piping a remote download directly into a shell interpreter executes unreviewed, potentially time-varying content with no opportunity for local inspection first.",
        remediation: "Download and inspect the script before executing it; avoid piping network output directly into a shell.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-SHELL-SEMANTIC-CREDENTIAL-ACCESS",
        rule_version: 1,
        detector_family: "shell-static",
        title: "Semantic shell credential/environment access call site",
        meaning: "Bounded shell tokenizer analysis resolved a command reading a credential-shaped path (SSH keys, AWS credentials, .netrc, /etc/shadow) or a credential-shaped environment variable.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review why this script needs credential/environment access.",
        limitations: "The shell tokenizer is bounded and not a full POSIX grammar (see shell_static::parser); confidence is capped lower than the equivalent Python finding.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-SHELL-SEMANTIC-PACKAGE-INSTALL",
        rule_version: 1,
        detector_family: "shell-static",
        title: "Semantic shell package-installation call site",
        meaning: "Bounded shell tokenizer analysis resolved an invocation of a package manager (pip/npm/apt/yum/conda/etc.) with an install-shaped argument.",
        why_it_matters: "Installing additional code at run time defeats package review.",
        remediation: "Review the referenced call site; pin and vet installed packages ahead of time instead.",
        limitations: "The shell tokenizer is bounded and not a full POSIX grammar (see shell_static::parser); confidence is capped lower than the equivalent Python finding.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-SHELL-SEMANTIC-FILESYSTEM-WRITE",
        rule_version: 1,
        detector_family: "shell-static",
        title: "Semantic shell filesystem-mutation call site",
        meaning: "Bounded shell tokenizer analysis resolved a command that recursively force-removes files, marks a file executable, or writes/appends to a sensitive path.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the referenced call site and target path before permitting this script to run.",
        limitations: "The shell tokenizer is bounded and not a full POSIX grammar (see shell_static::parser); confidence is capped lower than the equivalent Python finding.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-SHELL-SEMANTIC-NATIVE-LOAD",
        rule_version: 1,
        detector_family: "shell-static",
        title: "Semantic shell native-library-load call site",
        meaning: "Bounded shell tokenizer analysis resolved an `LD_PRELOAD=...`-prefixed command invocation, which loads a native library into the invoked process.",
        why_it_matters: "Native code loaded this way runs outside any interpreter-level inspection.",
        remediation: "Review the referenced call site and the preloaded library.",
        limitations: "Shell has essentially no native-load concept beyond LD_PRELOAD-style env-var prefixing; this category is intentionally thin.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-SHELL-SEMANTIC-INCOMPLETE",
        rule_version: 1,
        detector_family: "shell-static",
        title: "Semantic shell analysis incomplete",
        meaning: "The bounded shell tokenizer could not tokenize the file or exceeded its bounded analysis limits; a streaming textual fallback scan was used instead.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the file manually; semantic call-site findings for it are unavailable.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PS-SEMANTIC-DYNAMIC-CODE",
        rule_version: 1,
        detector_family: "powershell-static",
        title: "Semantic PowerShell dynamic-code call site",
        meaning: "Bounded PowerShell tokenizer analysis resolved a call to Invoke-Expression/iex, Add-Type, or Set-ExecutionPolicy with a Bypass/Unrestricted policy.",
        why_it_matters: "Dynamic evaluation, dynamic assembly compilation, and execution-policy bypass all run or enable code that is not visible by reading only the enclosing script.",
        remediation: "Review the referenced call site; dynamic evaluation and policy bypass defeat static review of what code actually runs.",
        limitations: "The PowerShell tokenizer is bounded and not a full PowerShell grammar (see powershell_static::parser); confidence is capped lower than the equivalent Python finding.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PS-SEMANTIC-DOWNLOAD-EXECUTE",
        rule_version: 1,
        detector_family: "powershell-static",
        title: "Remote content downloaded and piped into Invoke-Expression",
        meaning: "Bounded PowerShell tokenizer analysis resolved a pipeline where Invoke-WebRequest/iwr or Invoke-RestMethod/irm output is piped into Invoke-Expression/iex, a well-known supply-chain-attack signature (PowerShell's analog of `curl | bash`).",
        why_it_matters: "Piping a remote download directly into Invoke-Expression executes unreviewed, potentially time-varying content with no opportunity for local inspection first.",
        remediation: "Download and inspect the script before executing it; avoid piping network output directly into Invoke-Expression.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PS-SEMANTIC-NETWORK",
        rule_version: 1,
        detector_family: "powershell-static",
        title: "Semantic PowerShell network call site",
        meaning: "Bounded PowerShell tokenizer analysis resolved a network call (Invoke-WebRequest/iwr, Invoke-RestMethod/irm, or a `New-Object System.Net.WebClient` instance's DownloadString/DownloadFile) that is not part of the download-and-execute composite.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the referenced call site and the remote endpoint before permitting this script to run.",
        limitations: "The PowerShell tokenizer is bounded and not a full PowerShell grammar (see powershell_static::parser); confidence is capped lower than the equivalent Python finding.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PS-SEMANTIC-PROCESS",
        rule_version: 1,
        detector_family: "powershell-static",
        title: "Semantic PowerShell process-execution call site",
        meaning: "Bounded PowerShell tokenizer analysis resolved Start-Process, [System.Diagnostics.Process]::Start(...), or a direct executable invocation (e.g. powershell.exe, cmd.exe, *.exe) at a specific line and scope.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the referenced process invocation and its execution scope before permitting this script to run.",
        limitations: "The PowerShell tokenizer is bounded and not a full PowerShell grammar (see powershell_static::parser); confidence is capped lower than the equivalent Python finding.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PS-SEMANTIC-NATIVE-LOAD",
        rule_version: 1,
        detector_family: "powershell-static",
        title: "Semantic PowerShell native-assembly-load call site",
        meaning: "Bounded PowerShell tokenizer analysis resolved an Add-Type call, which compiles and loads a new .NET assembly at run time.",
        why_it_matters: "Code loaded this way runs outside any static review of the script's visible source and outside interpreter-level inspection.",
        remediation: "Review the referenced call site and the type/source being compiled.",
        limitations: "Add-Type is also classified as LF-PS-SEMANTIC-DYNAMIC-CODE from the same call site; both findings are expected to coexist by design.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PS-SEMANTIC-CREDENTIAL-ACCESS",
        rule_version: 1,
        detector_family: "powershell-static",
        title: "Semantic PowerShell credential/environment access call site",
        meaning: "Bounded PowerShell tokenizer analysis resolved Get-Credential, ConvertTo-SecureString (esp. with -AsPlainText), a `$env:` read of a credential-shaped variable name, or a registry read of a credential-shaped path.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review why this script needs credential/environment access.",
        limitations: "The PowerShell tokenizer is bounded and not a full PowerShell grammar (see powershell_static::parser); confidence is capped lower than the equivalent Python finding.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PS-SEMANTIC-PACKAGE-INSTALL",
        rule_version: 1,
        detector_family: "powershell-static",
        title: "Semantic PowerShell package-installation call site",
        meaning: "Bounded PowerShell tokenizer analysis resolved Install-Module, Install-Package, or `choco install`.",
        why_it_matters: "Installing additional code at run time defeats package review.",
        remediation: "Review the referenced call site; pin and vet installed packages ahead of time instead.",
        limitations: "The PowerShell tokenizer is bounded and not a full PowerShell grammar (see powershell_static::parser); confidence is capped lower than the equivalent Python finding.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PS-SEMANTIC-INCOMPLETE",
        rule_version: 1,
        detector_family: "powershell-static",
        title: "Semantic PowerShell analysis incomplete",
        meaning: "The bounded PowerShell tokenizer could not tokenize the file or exceeded its bounded analysis limits; a streaming textual fallback scan was used instead.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the file manually; semantic call-site findings for it are unavailable.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-JS-SEMANTIC-PROCESS",
        rule_version: 1,
        detector_family: "javascript-static",
        title: "Semantic JavaScript/TypeScript process-execution call site",
        meaning: "AST-based analysis resolved a call to child_process.exec/execSync/spawn/spawnSync/fork/execFile/execFileSync, with import-alias resolution (require/import destructuring, namespace imports, one-hop rebinding).",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the referenced command and its execution scope before permitting this script to run.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-JS-SEMANTIC-DYNAMIC-CODE",
        rule_version: 1,
        detector_family: "javascript-static",
        title: "Semantic JavaScript/TypeScript dynamic-code call site",
        meaning: "AST-based analysis resolved a call to eval(...), new Function(...), or Node's vm module (vm.runInThisContext/vm.runInNewContext/vm.Script).",
        why_it_matters: "Dynamic evaluation runs code that is not visible by reading only the enclosing script.",
        remediation: "Review the referenced call site; dynamic evaluation defeats static review of what code actually runs.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-JS-SEMANTIC-FILESYSTEM-WRITE",
        rule_version: 1,
        detector_family: "javascript-static",
        title: "Semantic JavaScript/TypeScript filesystem-mutation call site",
        meaning: "AST-based analysis resolved a call to fs.writeFile/writeFileSync/appendFile/appendFileSync/chmod/chmodSync, with `fs` and `node:fs` import forms normalized to the same target.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the referenced call site and target path before permitting this script to run.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-JS-SEMANTIC-NETWORK",
        rule_version: 1,
        detector_family: "javascript-static",
        title: "Semantic JavaScript/TypeScript network call site",
        meaning: "AST-based analysis resolved a call to fetch(...), http(s).request, net.connect/new net.Socket(...), or the common third-party pattern axios.get/axios.post/axios(...).",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the referenced call site and the remote endpoint before permitting this script to run.",
        limitations: "axios matching is a best-effort `axios`/`axios.` prefix match on the resolved call target, not a full resolution of axios's actual export shape.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-JS-SEMANTIC-CREDENTIAL-ACCESS",
        rule_version: 1,
        detector_family: "javascript-static",
        title: "Semantic JavaScript/TypeScript credential/environment access",
        meaning: "AST-based analysis resolved a read of process.env.<NAME> where <NAME> case-insensitively contains a credential-shaped substring (SECRET, TOKEN, PASSWORD, KEY, CREDENTIAL).",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review why this script needs credential/environment access.",
        limitations: "This is a heuristic on the accessed property name, not full taint tracking of where the value subsequently flows.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-JS-SEMANTIC-NATIVE-LOAD",
        rule_version: 1,
        detector_family: "javascript-static",
        title: "Semantic JavaScript/TypeScript native-code-load call site",
        meaning: "AST-based analysis resolved a require(...) call naming a known native-binding-loader package (e.g. ffi-napi) or a `.node`-suffixed module path, or a call to process.dlopen(...).",
        why_it_matters: "Native code loaded this way runs outside any interpreter-level inspection.",
        remediation: "Review the referenced call site and the native module being loaded.",
        limitations: "The native-binding-loader package list is a small, explicit allowlist; a native-loading package not on that list and not `.node`-suffixed will not be flagged.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-JS-SEMANTIC-PACKAGE-INSTALL",
        rule_version: 1,
        detector_family: "javascript-static",
        title: "Semantic JavaScript/TypeScript package-installation call site",
        meaning: "AST-based analysis resolved a process-execution call site (child_process.exec/execSync/spawn/...) whose first string-literal argument's first word names a package manager (npm/pip/yarn/pnpm/git/curl/wget).",
        why_it_matters: "Installing additional code at run time defeats package review.",
        remediation: "Review the referenced call site; pin and vet installed packages ahead of time instead.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-JS-SEMANTIC-INCOMPLETE",
        rule_version: 1,
        detector_family: "javascript-static",
        title: "Semantic JavaScript/TypeScript analysis incomplete",
        meaning: "The oxc-based AST analyzer could not parse the file or exceeded its bounded analysis limits; a streaming textual fallback scan was used instead.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the file manually; semantic call-site findings for it are unavailable.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PY-NUMPY-ALLOW-PICKLE",
        rule_version: 1,
        detector_family: "python-static",
        title: "NumPy load call explicitly sets allow_pickle=True",
        meaning: "Python static analysis detected a call to numpy.load with allow_pickle=True explicitly enabled.",
        why_it_matters: "Enabling allow_pickle=True permits arbitrary code execution if an object-dtype array is loaded.",
        remediation: "Remove allow_pickle=True or sanitize incoming array sources.",
        limitations: "Static analysis detects the call site and keyword parameter without executing Python.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-SERIALIZATION-BIN",
        rule_version: 1,
        detector_family: "pickle-static",
        title: "Layerfault security finding",
        meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the finding evidence and follow the configured policy before deployment.",
        limitations: "The format's capability is the finding. This says nothing about the specific contents of this artifact beyond what other findings report.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-SERIALIZATION-UNSAFE",
        rule_version: 1,
        detector_family: "pickle-static",
        title: "Code-capable serialization",
        meaning: "The package contains a Pickle/PyTorch/joblib-style artifact that may execute code when deserialized by an unsafe loader.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Prefer Safetensors/GGUF or a weights-only loading path. Do not deserialize untrusted artifacts merely to inspect them; Layerfault intentionally never loads the object graph.",
        limitations: "The format's capability is the finding. This says nothing about the specific contents of this artifact beyond what other findings report.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
