    RuleMetadata {
        rule_id: "LF-DATASET-COVERAGE-LIMIT",
        rule_version: 1,
        detector_family: "dataset",
        title: "Dataset analysis coverage limit",
        meaning: "Layerfault fingerprinted one or more dataset members but could not safely record-parse them with the current bounded dataset parser.",
        why_it_matters: "Content Layerfault did not examine cannot be reported as clean; incomplete coverage must be visible in the decision.",
        remediation: "Treat the poisoning review as incomplete. Convert or inspect opaque dataset members with a trusted, isolated workflow before relying on a clean result.",
        limitations: "Corpus statistics describe a distribution, not a specific harmful record, and legitimate corpora can exhibit the same shapes.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DATASET-CREDENTIAL-LIKE",
        rule_version: 1,
        detector_family: "dataset",
        title: "Dataset poisoning indicator",
        meaning: "The supplied dataset contains a bounded statistical/content indicator associated with poisoning risk.",
        why_it_matters: "Training-corpus content shapes model behaviour, so corpus-level anomalies can persist into the trained artifact.",
        remediation: "Review the flagged records and correlate them with model behaviour. This evidence does not prove malicious poisoning.",
        limitations: "Corpus statistics describe a distribution, not a specific harmful record, and legitimate corpora can exhibit the same shapes.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DATASET-DUPLICATE-CONCENTRATION",
        rule_version: 1,
        detector_family: "dataset",
        title: "Dataset poisoning indicator",
        meaning: "The supplied dataset contains a bounded statistical/content indicator associated with poisoning risk.",
        why_it_matters: "Training-corpus content shapes model behaviour, so corpus-level anomalies can persist into the trained artifact.",
        remediation: "Review the flagged records and correlate them with model behaviour. This evidence does not prove malicious poisoning.",
        limitations: "Corpus statistics describe a distribution, not a specific harmful record, and legitimate corpora can exhibit the same shapes.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DATASET-NEAR-DUPLICATE-CONCENTRATION",
        rule_version: 1,
        detector_family: "dataset",
        title: "Near-duplicate record concentration",
        meaning: "Records that are not byte-identical, but whose token content is near-identical (a bounded SimHash comparison), were observed in the dataset.",
        why_it_matters: "A templated or lightly varied insertion repeated across a corpus is a poisoning technique exact-duplicate hashing cannot see; near-duplicate clustering catches the case where an attacker varies a field between otherwise-identical repeated records.",
        remediation: "Review the flagged records and correlate them with model behaviour. This evidence does not prove malicious poisoning.",
        limitations: "This is a bounded sorted-window heuristic, not exhaustive pairwise comparison: near-duplicate pairs whose fingerprints happen to sort far apart are not caught. Legitimate corpora with templated content can exhibit the same shape.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DATASET-RARE-TRIGGER-CORRELATION",
        rule_version: 1,
        detector_family: "dataset",
        title: "Dataset poisoning indicator",
        meaning: "The supplied dataset contains a bounded statistical/content indicator associated with poisoning risk.",
        why_it_matters: "Training-corpus content shapes model behaviour, so corpus-level anomalies can persist into the trained artifact.",
        remediation: "Review the flagged records and correlate them with model behaviour. This evidence does not prove malicious poisoning.",
        limitations: "Corpus statistics describe a distribution, not a specific harmful record, and legitimate corpora can exhibit the same shapes.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DATASET-UNSAFE-CODE-PATTERN",
        rule_version: 1,
        detector_family: "dataset",
        title: "Dataset poisoning indicator",
        meaning: "The supplied dataset contains a bounded statistical/content indicator associated with poisoning risk.",
        why_it_matters: "Training-corpus content shapes model behaviour, so corpus-level anomalies can persist into the trained artifact.",
        remediation: "Review the flagged records and correlate them with model behaviour. This evidence does not prove malicious poisoning.",
        limitations: "Corpus statistics describe a distribution, not a specific harmful record, and legitimate corpora can exhibit the same shapes.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DATASET-URL-CONCENTRATION",
        rule_version: 1,
        detector_family: "dataset",
        title: "Dataset poisoning indicator",
        meaning: "The supplied dataset contains a bounded statistical/content indicator associated with poisoning risk.",
        why_it_matters: "Training-corpus content shapes model behaviour, so corpus-level anomalies can persist into the trained artifact.",
        remediation: "Review the flagged records and correlate them with model behaviour. This evidence does not prove malicious poisoning.",
        limitations: "Corpus statistics describe a distribution, not a specific harmful record, and legitimate corpora can exhibit the same shapes.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DATASET-ZERO-WIDTH",
        rule_version: 1,
        detector_family: "dataset",
        title: "Dataset poisoning indicator",
        meaning: "The supplied dataset contains a bounded statistical/content indicator associated with poisoning risk.",
        why_it_matters: "Training-corpus content shapes model behaviour, so corpus-level anomalies can persist into the trained artifact.",
        remediation: "Review the flagged records and correlate them with model behaviour. This evidence does not prove malicious poisoning.",
        limitations: "Corpus statistics describe a distribution, not a specific harmful record, and legitimate corpora can exhibit the same shapes.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DEP-ALT-INDEX",
        rule_version: 1,
        detector_family: "dependency",
        title: "Alternate package index or channel",
        meaning: "A manifest declares a package index, extra index, find-links source, or Conda channel other than the ecosystem default.",
        why_it_matters: "An alternate index or channel controls what bytes 'requests' or 'numpy' actually resolves to, independent of the well-known public index's namespace protections.",
        remediation: "Confirm the alternate source is an intentional, trusted mirror or private index.",
        limitations: "A non-default index or channel is not inherently unsafe; many organizations run legitimate private mirrors. This does not establish that the alternate source is compromised.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DEP-ANALYSIS-INCOMPLETE",
        rule_version: 1,
        detector_family: "dependency",
        title: "Dependency manifest analysis incomplete",
        meaning: "A dependency manifest or lockfile could not be fully parsed, or a bounded parsing limit was reached.",
        why_it_matters: "A manifest Layerfault could not parse contributes no dependency-risk evidence at all, which must not be mistaken for a clean result.",
        remediation: "Review the manifest manually; treat its declared dependency list as incomplete until it parses cleanly.",
        limitations: "This is a parser-failure or budget-limit fact. It does not characterize the manifest's actual dependency risk, which remains unexamined.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DEP-BUILD-BACKEND",
        rule_version: 1,
        detector_family: "dependency",
        title: "Custom build backend",
        meaning: "pyproject.toml declares a build backend other than the standard setuptools backend. A build backend is code that runs during package install/build.",
        why_it_matters: "A build backend is code that runs during 'pip install'/'python -m build', before the package's own runtime code is ever imported.",
        remediation: "Review the declared build backend package and its build-system.requires before installing from source.",
        limitations: "A non-default build backend is not inherently unsafe; this records that install-time code exists and names it, without evaluating its behaviour.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DEP-DIRECT-URL",
        rule_version: 1,
        detector_family: "dependency",
        title: "Direct URL dependency",
        meaning: "A dependency is fetched from a direct URL rather than the configured package index.",
        why_it_matters: "A direct URL bypasses the package index's namespace and review conventions, so the fetched content depends entirely on the URL's host staying trustworthy.",
        remediation: "Prefer index-resolved packages, or verify the direct URL is a trusted, hash-pinned source.",
        limitations: "Layerfault records the declared source shape. It does not contact the index, VCS host, or filesystem path, and does not establish that the referenced content is unsafe.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DEP-FLOATING",
        rule_version: 1,
        detector_family: "dependency",
        title: "Unpinned dependency",
        meaning: "A declared dependency has no exact version pin, hash constraint, or fully-qualified VCS commit, so the exact code that will be installed is not fixed by the manifest alone.",
        why_it_matters: "An unpinned dependency can silently resolve to a newer, compromised, or unexpected release between installs, changing what code actually runs without a corresponding manifest change.",
        remediation: "Pin an exact version or content hash, or use a lockfile with hash enforcement, for dependencies that affect a security-relevant build.",
        limitations: "Absence of a pin is a manifest-level fact. It does not establish that the currently resolvable version is compromised, nor predict what a future resolution will select.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DEP-INCLUDE-MISSING",
        rule_version: 1,
        detector_family: "dependency",
        title: "Dependency manifest include could not be resolved",
        meaning: "A requirements-file -r/-c include reference could not be found, read, or safely resolved within the package.",
        why_it_matters: "A dependency manifest that references an unresolvable include is incomplete: some declared dependencies are unknown to this scan.",
        remediation: "Restore the missing include file, or confirm its absence is expected before trusting this manifest as complete.",
        limitations: "This describes a gap in Layerfault's view of the manifest tree, not a property of the (unresolved) included file's content.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DEP-INSECURE-TRANSPORT",
        rule_version: 1,
        detector_family: "dependency",
        title: "Insecure dependency transport",
        meaning: "A dependency source, index, or channel uses plaintext HTTP, a localhost/file scheme, or an explicit certificate-verification bypass (--trusted-host).",
        why_it_matters: "Plaintext HTTP or a disabled certificate check lets a network-position attacker substitute the package content in transit.",
        remediation: "Use HTTPS with certificate verification for all package acquisition sources.",
        limitations: "Layerfault observes the declared transport scheme only. It does not confirm whether a network-position attack actually occurred for this specific install.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DEP-INSTALL-HOOK",
        rule_version: 1,
        detector_family: "dependency",
        title: "Custom install/build hook",
        meaning: "setup.py defines a class subclassing a setuptools/distutils Command (or a common subclass such as install/build_ext/develop/egg_info) whose methods run during package installation or build, before any application code runs.",
        why_it_matters: "Install/build hooks execute automatically during 'pip install' or 'python setup.py build', before a reviewer would normally inspect runtime application code, and can carry process-execution or network capability at that stage.",
        remediation: "Review the exact hook body for process execution, network access, or dynamic code evaluation. Treat install-time code as equivalent in trust to the package's runtime code.",
        limitations: "Static detection of a custom Command subclass and a capability inside its body does not establish that pip actually invokes this exact hook for a given install command, that the capability executes unconditionally, or that the base class was correctly resolved without import analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DEP-NPM-INSTALL-HOOK",
        rule_version: 1,
        detector_family: "dependency",
        title: "npm install-hook script",
        meaning: "package.json declares a scripts.preinstall/install/postinstall entry, which npm runs automatically during `npm install`, before a reviewer would normally inspect runtime application code.",
        why_it_matters: "Install-hook scripts execute automatically during `npm install`, and are a well-documented supply-chain-attack vector for npm packages.",
        remediation: "Review the referenced hook script for process execution, network access, or dynamic code evaluation before running `npm install` against this package.",
        limitations: "Static detection of the declared hook command and a best-effort extracted script filename does not establish that npm actually invokes this exact script for a given install command, or that a referenced script exists at that exact path within the package.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DEP-LOCAL-PATH",
        rule_version: 1,
        detector_family: "dependency",
        title: "Local/editable path dependency",
        meaning: "A dependency is declared as a local filesystem path or editable install rather than a versioned package.",
        why_it_matters: "A local/editable dependency ties the package's identity to filesystem content outside what was fingerprinted, so the same manifest can resolve differently depending on what happens to sit at that path.",
        remediation: "Confirm the referenced path is part of the reviewed package tree and is not an ambiguous external reference.",
        limitations: "Layerfault records the declared source shape. It does not contact the index, VCS host, or filesystem path, and does not establish that the referenced content is unsafe.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DEP-PATH-ESCAPE",
        rule_version: 1,
        detector_family: "dependency",
        title: "Local dependency path escapes the package root",
        meaning: "A local/editable dependency path resolves outside the directory tree of the manifest that declared it.",
        why_it_matters: "A dependency path that leaves the package directory tree can reference content the reviewer never saw, while still being installed as part of this package.",
        remediation: "Correct the dependency path so it stays within the reviewed package, or vendor the external content into the package.",
        limitations: "Layerfault detects the declared path shape only; it does not open or verify content at the escaped location.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DEP-RUNTIME-INSTALL",
        rule_version: 1,
        detector_family: "dependency",
        title: "Package manager invoked from an install hook",
        meaning: "A setup.py install/build hook invokes a package manager (pip/uv/conda/poetry/npm/git/curl/wget) to acquire additional code at install time.",
        why_it_matters: "A package-manager invocation from an install hook can acquire and run code that is not declared anywhere in the package's own dependency manifest.",
        remediation: "Review exactly what is installed and from where; installs triggered from a hook are not visible in the package's declared dependency list.",
        limitations: "Layerfault records the literal invocation it found; it does not execute the hook and cannot confirm the install command runs in every configuration or actually succeeds.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DEP-VCS",
        rule_version: 1,
        detector_family: "dependency",
        title: "VCS dependency pinned to a commit",
        meaning: "A dependency is fetched from a version-control repository, pinned to a full commit hash.",
        why_it_matters: "A VCS dependency installs code straight from a repository rather than a published, indexed release, widening what the manifest actually pulls in.",
        remediation: "Review the referenced repository and commit before treating it as equivalent to a reviewed release.",
        limitations: "Layerfault records the declared source shape. It does not contact the index, VCS host, or filesystem path, and does not establish that the referenced content is unsafe.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DEP-VCS-MUTABLE-REF",
        rule_version: 1,
        detector_family: "dependency",
        title: "Dependency pinned to a mutable VCS reference",
        meaning: "A VCS dependency is pinned to a branch or tag name rather than a full commit hash, so the referenced content can change without the manifest changing.",
        why_it_matters: "A branch or tag can be force-pushed or retargeted by anyone with write access to the referenced repository, so the manifest's declared source does not fix the installed content the way a commit hash would.",
        remediation: "Pin the dependency to a full commit SHA, or vendor/mirror the exact commit if a stable review target is required.",
        limitations: "Layerfault does not contact the VCS host and cannot determine what the reference currently resolves to, whether it has changed historically, or whether the hosting repository enforces branch protection.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DERIVE-SCHEMA-CROSS-FORMAT",
        rule_version: 1,
        detector_family: "lineage",
        title: "Cross-format tensor schema uncertainty",
        meaning: "Raw tensor names/layout differ across serialization formats and are not directly comparable as a security invariant.",
        why_it_matters: "A derivation claim that cannot be verified means the trust attached to the claimed base model does not transfer to this artifact.",
        remediation: "Use reproducible quantization/provenance evidence rather than treating format-specific tensor naming drift as a contradiction.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DERIVE-SCHEMA-MISMATCH",
        rule_version: 1,
        detector_family: "lineage",
        title: "Derived-model integrity change",
        meaning: "A security-relevant component of the derived model differs from the supplied base or transformation claim.",
        why_it_matters: "A derivation claim that cannot be verified means the trust attached to the claimed base model does not transfer to this artifact.",
        remediation: "Verify the claimed transformation and investigate the changed component before treating the derivative as equivalent to its base.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DIFF-EMPTY-RESPONSE",
        rule_version: 1,
        detector_family: "lineage",
        title: "Behavioural comparison received an empty response",
        meaning: "A base-versus-derived behavioural comparison observed an empty response for a probe, preventing a meaningful comparison for that probe.",
        why_it_matters: "An empty response reduces comparison coverage and must not be treated as evidence of either equivalence or a security regression.",
        remediation: "Inspect the runner diagnostics and repeat the comparison with a functioning runtime before relying on the behavioural result.",
        limitations: "This records an incomplete or unusable probe response; it does not establish why the response was empty or attribute intent to either model.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DIFF-INCOMPLETE",
        rule_version: 1,
        detector_family: "lineage",
        title: "Behavioural comparison incomplete",
        meaning: "The base-versus-derived behavioural comparison did not complete over the full probe suite (a probe execution failed, was skipped, or otherwise did not produce a comparable result for both models).",
        why_it_matters: "A comparison that only covers part of the probe suite cannot support the same confidence as a complete one; missing coverage is a gap in assurance, not evidence about either model.",
        remediation: "Re-run the comparison so every probe in the suite executes against both models, and treat the result as informative only once it does.",
        limitations: "This finding describes a limitation of this specific comparison run, not a property of either compared artifact. It must not be treated as evidence of a security regression by itself.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DIFF-LOCALIZED-DIVERGENCE",
        rule_version: 1,
        detector_family: "lineage",
        title: "Localized behavioural divergence",
        meaning: "A deterministic base-versus-derived probe response changed far more than the median response change across the same suite. This is trigger/backdoor evidence, not proof of malicious intent.",
        why_it_matters: "A security-relevant difference between two revisions is where a change of behaviour would be introduced.",
        remediation: "Review the divergent probe, repeat it under the recorded runtime/seed, and broaden nearby trigger mutations before deployment.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DIFF-SAFETY-BOUNDARY-FLIP",
        rule_version: 1,
        detector_family: "lineage",
        title: "Trigger-localized safety boundary regression",
        meaning: "An explicit paired trigger changed a refusal into actionable compliance in the derived model while control behavior remained stable.",
        why_it_matters: "A security-relevant difference between two revisions is where a change of behaviour would be introduced.",
        remediation: "Block the derivative and reproduce the paired probe under the recorded runtime before deployment.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DIFF-SECURITY-REGRESSION",
        rule_version: 1,
        detector_family: "lineage",
        title: "Behavioural security finding",
        meaning: "The bounded probe suite observed a security-relevant behaviour or base-versus-derived regression.",
        why_it_matters: "A security-relevant difference between two revisions is where a change of behaviour would be introduced.",
        remediation: "Do not deploy the derivative until the behaviour is understood and reproduced. A clean run would not prove absence of other hidden triggers.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DIFF-SUSPICIOUS-TRIGGER",
        rule_version: 1,
        detector_family: "lineage",
        title: "Suspicious trigger-localized behaviour",
        meaning: "A trigger-designated probe or output-collapse condition produced a localized, repeatable behavioural divergence relative to the supplied base model.",
        why_it_matters: "A security-relevant difference between two revisions is where a change of behaviour would be introduced.",
        remediation: "Block deployment until the trigger behavior is explained. Reproduce it in the strong sandbox with adjacent mutations and preserve the report as evidence.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DRIFT-EXECUTABLE-ADDED",
        rule_version: 1,
        detector_family: "lineage",
        title: "Model revision drift",
        meaning: "A previously observed model identity changed in a security-relevant component.",
        why_it_matters: "A security-relevant component changed between revisions, so a prior assessment of this identity no longer describes what is on disk.",
        remediation: "Review the exact revision diff and reacquire/re-attest the model if the change was not expected.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DRIFT-TEMPLATE-CHANGED",
        rule_version: 1,
        detector_family: "lineage",
        title: "Model revision drift",
        meaning: "A previously observed model identity changed in a security-relevant component.",
        why_it_matters: "A security-relevant component changed between revisions, so a prior assessment of this identity no longer describes what is on disk.",
        remediation: "Review the exact revision diff and reacquire/re-attest the model if the change was not expected.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DRIFT-TOKENIZER-CHANGED",
        rule_version: 1,
        detector_family: "lineage",
        title: "Model revision drift",
        meaning: "A previously observed model identity changed in a security-relevant component.",
        why_it_matters: "A security-relevant component changed between revisions, so a prior assessment of this identity no longer describes what is on disk.",
        remediation: "Review the exact revision diff and reacquire/re-attest the model if the change was not expected.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-DRIFT-WEIGHTS-CHANGED",
        rule_version: 1,
        detector_family: "lineage",
        title: "Model revision drift",
        meaning: "A previously observed model identity changed in a security-relevant component.",
        why_it_matters: "A security-relevant component changed between revisions, so a prior assessment of this identity no longer describes what is on disk.",
        remediation: "Review the exact revision diff and reacquire/re-attest the model if the change was not expected.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-LINEAGE-ARCH-MISMATCH",
        rule_version: 1,
        detector_family: "lineage",
        title: "Model lineage evidence",
        meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.",
        why_it_matters: "A derivation claim that cannot be verified means the trust attached to the claimed base model does not transfer to this artifact.",
        remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-LINEAGE-CHAIN-BROKEN",
        rule_version: 1,
        detector_family: "lineage",
        title: "Model lineage evidence",
        meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.",
        why_it_matters: "A derivation claim that cannot be verified means the trust attached to the claimed base model does not transfer to this artifact.",
        remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-LINEAGE-CHAIN-CYCLE",
        rule_version: 1,
        detector_family: "lineage",
        title: "Model lineage evidence",
        meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.",
        why_it_matters: "A derivation claim that cannot be verified means the trust attached to the claimed base model does not transfer to this artifact.",
        remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-LINEAGE-CHAIN-SIGNATURE",
        rule_version: 1,
        detector_family: "lineage",
        title: "Model lineage evidence",
        meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.",
        why_it_matters: "A derivation claim that cannot be verified means the trust attached to the claimed base model does not transfer to this artifact.",
        remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-LINEAGE-CHAIN-UNTRUSTED-SIGNER",
        rule_version: 1,
        detector_family: "lineage",
        title: "Model lineage evidence",
        meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.",
        why_it_matters: "A derivation claim that cannot be verified means the trust attached to the claimed base model does not transfer to this artifact.",
        remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-LINEAGE-CLAIM-NO-EVIDENCE",
        rule_version: 1,
        detector_family: "lineage",
        title: "Model lineage evidence",
        meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.",
        why_it_matters: "A derivation claim that cannot be verified means the trust attached to the claimed base model does not transfer to this artifact.",
        remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-LINEAGE-CLAIM-IDENTITY-MISMATCH",
        rule_version: 1,
        detector_family: "lineage",
        title: "Lineage claim identity mismatch",
        meaning: "The parent/child identities named in a lineage claim do not match the identities of the artifacts Layerfault actually compared.",
        why_it_matters: "A claim bound to the wrong artifacts proves nothing about the artifacts actually being assessed; any inherited trust the claim implies does not apply here.",
        remediation: "Recreate the lineage claim against the exact artifacts being compared.",
        limitations: "This finding is about claim/artifact binding only; it does not itself assess whether the claimed relationship, correctly bound, would hold.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-LINEAGE-CLAIM-STRUCTURAL-CONTRADICTION",
        rule_version: 1,
        detector_family: "lineage",
        title: "Lineage claim contradicted by structural comparison",
        meaning: "The observed structural identity relationship between parent and child contradicts the claimed transformation relationship.",
        why_it_matters: "When the structural evidence itself contradicts what was claimed, the claim cannot be relied on to establish that security properties of the parent transfer to the child.",
        remediation: "Investigate why the structural comparison disagrees with the claim; do not treat the child as inheriting the parent's assurance until this is resolved.",
        limitations: "This is a structural (architecture/format-level) comparison; it does not itself re-run behavioural or tensor-level analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-LINEAGE-CLAIM-TOKENIZER-CONTRADICTION",
        rule_version: 1,
        detector_family: "lineage",
        title: "Lineage claim contradicted by tokenizer change",
        meaning: "The tokenizer changed between parent and child in a way inconsistent with the claimed transformation (a repackaging or quantization claim should not change tokenizer identity).",
        why_it_matters: "An unexplained tokenizer change alters prompt-boundary behaviour independently of the claimed transformation, and is exactly the kind of change a repackaging/quantization claim should rule out.",
        remediation: "Confirm whether the tokenizer change was intended; if so, the transformation claim itself should be corrected to reflect it.",
        limitations: "This compares tokenizer identity values only; it does not itself assess what changed within the tokenizer.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-LINEAGE-CLAIM-TRANSFORMATION-CONTRADICTED",
        rule_version: 1,
        detector_family: "lineage",
        title: "Lineage claim contradicted by byte-identical artifacts",
        meaning: "The claimed transformation type (quantization, fine-tuning, adapter merge, or format conversion) necessarily alters model weights, but the compared artifacts are byte-identical.",
        why_it_matters: "Weight-altering transformations that changed nothing did not happen as claimed; accepting the claim on evidence-presence alone, without checking it against what was actually observed, would let an unsupported claim assert inherited security properties.",
        remediation: "Correct the transformation claim to match what was actually observed, or investigate why no change is present despite the claimed operation.",
        limitations: "This checks byte-identity only; a claim describing a transformation that happens to be a no-op in this specific instance (e.g. quantizing to the same precision) is a legitimate edge case this rule cannot distinguish from a false claim.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-LINEAGE-CLAIM-TRANSFORMATION-UNVERIFIED",
        rule_version: 1,
        detector_family: "lineage",
        title: "Lineage claim has no verifiable transformation evidence",
        meaning: "A lineage claim was made without any attached transformation evidence (e.g. a signed transformation chain, adapter artifact reference).",
        why_it_matters: "Without evidence, security properties of the parent are not established to carry over to the child; the claim is an assertion, not a proof.",
        remediation: "Attach verifiable transformation evidence (a signed transformation chain, adapter manifest, or equivalent) to the claim.",
        limitations: "This checks evidence presence, not evidence quality; supplied evidence is still only as trustworthy as its own verification (see the transformation chain signature/trust checks).",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-LINEAGE-MANIFEST-CLAIM",
        rule_version: 1,
        detector_family: "lineage",
        title: "Model lineage evidence",
        meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.",
        why_it_matters: "A derivation claim that cannot be verified means the trust attached to the claimed base model does not transfer to this artifact.",
        remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-LINEAGE-MANIFEST-ENDPOINT",
        rule_version: 1,
        detector_family: "lineage",
        title: "Model lineage evidence",
        meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.",
        why_it_matters: "A derivation claim that cannot be verified means the trust attached to the claimed base model does not transfer to this artifact.",
        remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-LINEAGE-QUANTIZATION-CROSS-FORMAT",
        rule_version: 1,
        detector_family: "lineage",
        title: "Cross-format quantization lineage uncertainty",
        meaning: "A quantization claim crosses serialization formats whose tensor inventories cannot be compared one-for-one.",
        why_it_matters: "A derivation claim that cannot be verified means the trust attached to the claimed base model does not transfer to this artifact.",
        remediation: "Require reproducibility or signed transformation evidence; expected representation drift alone must not cause BLOCK.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-LINEAGE-QUANTIZATION-METADATA-INCOMPARABLE",
        rule_version: 1,
        detector_family: "lineage",
        title: "Cross-format quantization metadata is incomplete",
        meaning: "Tokenizer or chat-template semantics could not be normalized across the two serialization formats; representation-specific byte differences are not treated as proof of tampering.",
        why_it_matters: "A derivation claim that cannot be verified means the trust attached to the claimed base model does not transfer to this artifact.",
        remediation: "Use a converter that preserves comparable metadata or supply signed reproducibility evidence for the exact derivative.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-LINEAGE-QUANTIZATION-TEMPLATE",
        rule_version: 1,
        detector_family: "lineage",
        title: "Model lineage evidence",
        meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.",
        why_it_matters: "A derivation claim that cannot be verified means the trust attached to the claimed base model does not transfer to this artifact.",
        remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-LINEAGE-QUANTIZATION-TOKENIZER",
        rule_version: 1,
        detector_family: "lineage",
        title: "Model lineage evidence",
        meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.",
        why_it_matters: "A derivation claim that cannot be verified means the trust attached to the claimed base model does not transfer to this artifact.",
        remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-LINEAGE-REPACKAGE-CONTENT",
        rule_version: 1,
        detector_family: "lineage",
        title: "Model lineage evidence",
        meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.",
        why_it_matters: "A derivation claim that cannot be verified means the trust attached to the claimed base model does not transfer to this artifact.",
        remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PACKAGE-ARTIFACT",
        rule_version: 1,
        detector_family: "package",
        title: "Model package finding",
        meaning: "The package contains a structural, executable-content, text-limit or integrity condition requiring review.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the exact package member and preserve the package as an immutable unit before loading it.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PACKAGE-CODE",
        rule_version: 1,
        detector_family: "package",
        title: "Model package finding",
        meaning: "The package contains a structural, executable-content, text-limit or integrity condition requiring review.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the exact package member and preserve the package as an immutable unit before loading it.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PACKAGE-FILE",
        rule_version: 1,
        detector_family: "package",
        title: "Model package finding",
        meaning: "The package contains a structural, executable-content, text-limit or integrity condition requiring review.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Review the exact package member and preserve the package as an immutable unit before loading it.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PACKAGE-JSON-INVALID",
        rule_version: 1,
        detector_family: "package",
        title: "Malformed package JSON/config",
        meaning: "A JSON or config member could not be fully parsed by Layerfault's bounded parser.",
        why_it_matters: "Configuration that Layerfault cannot fully parse may still be parsed, differently, by a permissive loader.",
        remediation: "Review the exact parser error and the file's origin before trusting other metadata extracted from it.",
        limitations: "Layerfault reports the observed technical condition. Establishing intent or impact requires review beyond static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PACKAGE-RACE",
        rule_version: 1,
        detector_family: "package",
        title: "Package member changed during scan",
        meaning: "A package file produced a different digest when rehashed after scanning, indicating concurrent mutation or an unstable storage layer.",
        why_it_matters: "Content that changes during a scan means the assessment describes bytes that are no longer the ones on disk.",
        remediation: "Block execution, preserve the artifact for investigation, and rescan from a stable read-only copy.",
        limitations: "Layerfault reports only the values it measured. It does not establish how or why the artifact differs from its declaration.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PACKAGE-MEMBER-ERROR",
        rule_version: 1,
        detector_family: "package",
        title: "Package member inspection error",
        meaning: "A package member produced a structured error during analysis.",
        why_it_matters: "A member that cannot be safely analyzed cannot be guaranteed clean.",
        remediation: "Review the member content and error details to ensure integrity.",
        limitations: "Layerfault reports the technical error encountered during static analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PACKAGE-MEMBER-PANIC",
        rule_version: 1,
        detector_family: "package",
        title: "Package member inspection panic isolated",
        meaning: "A package member parser encountered an isolated internal panic.",
        why_it_matters: "A member that causes a parser failure requires review before admission.",
        remediation: "Review the member and report the panic case for parser improvement.",
        limitations: "Layerfault safely isolated the panic to preserve overall package analysis.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PACKAGE-SYMLINK",
        rule_version: 1,
        detector_family: "package",
        title: "Model package symlink",
        meaning: "A direct model package contains a symlink. Layerfault fingerprints direct packages without following links so a package cannot silently escape its root.",
        why_it_matters: "A symlink lets a package reference content outside its own root, so the fingerprinted package and the loaded bytes can differ.",
        remediation: "Replace the symlink with an explicit regular file, or use the dedicated Hugging Face cache audit path where validated snapshot-to-blob symlinks are resolved safely.",
        limitations: "Layerfault records the declared target without following it. It has not established what the target actually resolves to.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PACKAGE-TEXT-LIMIT",
        rule_version: 1,
        detector_family: "package",
        title: "Legacy package text coverage limit",
        meaning: "Older Layerfault builds emitted this rule when a package text/config member exceeded their bounded full-file text scan. Current builds stream security inspection across the complete member and retain this explanation only for historical evidence compatibility.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Rescan the package with the current build. If the legacy warning persists only in old evidence, replace that evidence after a successful current scan.",
        limitations: "This records what Layerfault did not examine. Unexamined content is neither clean nor harmful; it is unreviewed.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PROV-BINDING",
        rule_version: 1,
        detector_family: "provenance",
        title: "Provenance finding",
        meaning: "The artifact provenance/signature/trust evidence is incomplete, invalid or has a compatibility condition.",
        why_it_matters: "Signature verification did not reach the state the configured trust policy requires.",
        remediation: "Verify the exact artifact identity and signer trust relationship before deployment.",
        limitations: "Trust state reflects the configured trust store and policy. It is a statement about verification, not about the artifact's contents.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PROV-INACTIVE",
        rule_version: 1,
        detector_family: "provenance",
        title: "Inactive trusted key",
        meaning: "The signature is cryptographically valid but the corresponding trusted key is outside its activation window.",
        why_it_matters: "A signature from a key outside its authorized window does not carry the trust the trust store was configured to grant.",
        remediation: "Use a currently active authorized signer or deliberately correct the trust-store activation/expiry window after verification.",
        limitations: "Trust state reflects the configured trust store and policy. It is a statement about verification, not about the artifact's contents.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PROV-LEGACY",
        rule_version: 1,
        detector_family: "provenance",
        title: "Provenance finding",
        meaning: "The artifact provenance/signature/trust evidence is incomplete, invalid or has a compatibility condition.",
        why_it_matters: "Without a trusted attestation there is nothing binding this exact artifact to a publisher you have decided to trust.",
        remediation: "Verify the exact artifact identity and signer trust relationship before deployment.",
        limitations: "Trust state reflects the configured trust store and policy. It is a statement about verification, not about the artifact's contents.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PROV-LOCAL",
        rule_version: 1,
        detector_family: "provenance",
        title: "Provenance finding",
        meaning: "The artifact provenance/signature/trust evidence is incomplete, invalid or has a compatibility condition.",
        why_it_matters: "Without a trusted attestation there is nothing binding this exact artifact to a publisher you have decided to trust.",
        remediation: "Verify the exact artifact identity and signer trust relationship before deployment.",
        limitations: "Trust state reflects the configured trust store and policy. It is a statement about verification, not about the artifact's contents.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PROV-LOCAL-VERIFIED",
        rule_version: 1,
        detector_family: "provenance",
        title: "Legacy local signature verified",
        meaning: "A legacy detached Ed25519 signature verified against the scanned manifest bytes using a supplied public key.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "Trust/identity binding is not established by this alone; use the trust-store attestation path for authorized-signer verification.",
        limitations: "Trust state reflects the configured trust store and policy. It is a statement about verification, not about the artifact's contents.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PROV-MULTI",
        rule_version: 1,
        detector_family: "provenance",
        title: "Provenance finding",
        meaning: "The artifact provenance/signature/trust evidence is incomplete, invalid or has a compatibility condition.",
        why_it_matters: "Signature verification did not reach the state the configured trust policy requires.",
        remediation: "Verify the exact artifact identity and signer trust relationship before deployment.",
        limitations: "Trust state reflects the configured trust store and policy. It is a statement about verification, not about the artifact's contents.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PROV-NAMESPACE",
        rule_version: 1,
        detector_family: "provenance",
        title: "Signer namespace mismatch",
        meaning: "The signature is valid but the signer is not authorized for this model identity.",
        why_it_matters: "A valid signature from a signer not authorized for this identity means the signer is vouching for something outside their remit.",
        remediation: "Correct the trust policy or obtain an attestation from a publisher key authorized for this namespace.",
        limitations: "Trust state reflects the configured trust store and policy. It is a statement about verification, not about the artifact's contents.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PROV-REVOKED",
        rule_version: 1,
        detector_family: "provenance",
        title: "Revoked signer",
        meaning: "An attestation is bound to a trust-store key that has been revoked.",
        why_it_matters: "A signature from a key outside its authorized window does not carry the trust the trust store was configured to grant.",
        remediation: "Do not run the artifact. Re-attest a verified artifact with a currently authorized key after investigating the revoked signer.",
        limitations: "Trust state reflects the configured trust store and policy. It is a statement about verification, not about the artifact's contents.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PROV-SIGNATURE",
        rule_version: 1,
        detector_family: "provenance",
        title: "Provenance finding",
        meaning: "The artifact provenance/signature/trust evidence is incomplete, invalid or has a compatibility condition.",
        why_it_matters: "Signature verification did not reach the state the configured trust policy requires.",
        remediation: "Verify the exact artifact identity and signer trust relationship before deployment.",
        limitations: "Trust state reflects the configured trust store and policy. It is a statement about verification, not about the artifact's contents.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PROV-SIGSTORE",
        rule_version: 1,
        detector_family: "provenance",
        title: "Sigstore bundle verified",
        meaning: "An installed Cosign verifier accepted the supplied offline Sigstore bundle for the expected certificate identity and issuer.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "No action is required; keep the bundle with provenance evidence if the artifact is admitted.",
        limitations: "Trust state reflects the configured trust store and policy. It is a statement about verification, not about the artifact's contents.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PROV-SIGSTORE-INVALID",
        rule_version: 1,
        detector_family: "provenance",
        title: "Invalid Sigstore bundle",
        meaning: "Cosign could not verify the supplied bundle against the expected artifact, certificate identity or issuer.",
        why_it_matters: "Signature verification did not reach the state the configured trust policy requires.",
        remediation: "Block the artifact and investigate provenance. Do not weaken identity or issuer constraints merely to make verification pass.",
        limitations: "Trust state reflects the configured trust store and policy. It is a statement about verification, not about the artifact's contents.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PROV-TRUSTED",
        rule_version: 1,
        detector_family: "provenance",
        title: "Trusted attestation",
        meaning: "The exact model manifest is signed by a currently active key authorized for the model namespace.",
        why_it_matters: "Layerfault observed a condition that affects whether this artifact can be safely admitted.",
        remediation: "No action is required unless a higher signature threshold or another policy condition is configured.",
        limitations: "Trust state reflects the configured trust store and policy. It is a statement about verification, not about the artifact's contents.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PROV-UNSIGNED",
        rule_version: 1,
        detector_family: "provenance",
        title: "Unsigned artifact",
        meaning: "No Layerfault attestation was found for the exact artifact identity.",
        why_it_matters: "Without a trusted attestation there is nothing binding this exact artifact to a publisher you have decided to trust.",
        remediation: "Use workstation policy if unsigned models are acceptable, or obtain/sign an attestation with an authorized key for strict admission.",
        limitations: "Trust state reflects the configured trust store and policy. It is a statement about verification, not about the artifact's contents.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-PROV-UNTRUSTED",
        rule_version: 1,
        detector_family: "provenance",
        title: "Provenance finding",
        meaning: "The artifact provenance/signature/trust evidence is incomplete, invalid or has a compatibility condition.",
        why_it_matters: "Without a trusted attestation there is nothing binding this exact artifact to a publisher you have decided to trust.",
        remediation: "Verify the exact artifact identity and signer trust relationship before deployment.",
        limitations: "Trust state reflects the configured trust store and policy. It is a statement about verification, not about the artifact's contents.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-TOKENIZER-CHANGED",
        rule_version: 1,
        detector_family: "lineage",
        title: "Derived-model integrity change",
        meaning: "A security-relevant component of the derived model differs from the supplied base or transformation claim.",
        why_it_matters: "A security-relevant component changed between revisions, so a prior assessment of this identity no longer describes what is on disk.",
        remediation: "Verify the claimed transformation and investigate the changed component before treating the derivative as equivalent to its base.",
        limitations: "Layerfault reports that the compared artifacts differ. It does not establish that the difference is unauthorised or harmful.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "T13-001",
        rule_version: 1,
        detector_family: "provenance",
        title: "Missing or unverified local attestation",
        meaning: "No detached signature was found for this manifest, or one was found but no public key was supplied to verify it.",
        why_it_matters: "Instruction-shaped text embedded in model data can be interpreted as instructions by a model or an agent that reads it.",
        remediation: "Use workstation policy if unattested models are acceptable, or supply --public-key / obtain a signature for strict admission.",
        limitations: "Pattern matching over text cannot distinguish an attack payload from documentation, test data or discussion of the same technique. Review the excerpt in context.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "T13-002",
        rule_version: 1,
        detector_family: "provenance",
        title: "Invalid local attestation",
        meaning: "A detached signature exists but is malformed, unreadable, or does not verify against the scanned manifest bytes.",
        why_it_matters: "Instruction-shaped text embedded in model data can be interpreted as instructions by a model or an agent that reads it.",
        remediation: "Do not trust this attestation. Investigate the signature's origin and re-sign with a verified key if appropriate.",
        limitations: "Pattern matching over text cannot distinguish an attack payload from documentation, test data or discussion of the same technique. Review the excerpt in context.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-INVENTORY-APPROVAL-STALE",
        rule_version: 1,
        detector_family: "inventory",
        title: "Inventory Approval Stale",
        meaning: "A prior model approval no longer binds to the current artifact, ruleset, intelligence, or receipt state.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-INVENTORY-MODIFIED",
        rule_version: 1,
        detector_family: "inventory",
        title: "Inventory Modified",
        meaning: "A previously observed model artifact changed identity or security-relevant content.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-INVENTORY-NEW-UNAPPROVED",
        rule_version: 1,
        detector_family: "inventory",
        title: "Inventory New Unapproved",
        meaning: "A newly discovered model artifact has no current admission approval.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-INVENTORY-PREVIOUSLY-BLOCKED",
        rule_version: 1,
        detector_family: "inventory",
        title: "Inventory Previously Blocked",
        meaning: "The inventory contains an artifact previously recorded with a blocking security decision.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-LINEAGE-IDENTITY-CONTRADICTION",
        rule_version: 1,
        detector_family: "lineage",
        title: "Lineage Identity Contradiction",
        meaning: "Observed layered identity evidence contradicts the claimed model lineage.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-LINEAGE-TRANSFORMATION-UNVERIFIED",
        rule_version: 1,
        detector_family: "lineage",
        title: "Lineage Transformation Unverified",
        meaning: "A claimed transformation lacks sufficient signed or observable evidence for verification.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
    RuleMetadata {
        rule_id: "LF-LINEAGE-UNEXPLAINED-COMPONENT",
        rule_version: 1,
        detector_family: "lineage",
        title: "Lineage Unexplained Component",
        meaning: "A child model contains a component not explained by the declared parent/transformation chain.",
        why_it_matters: "This condition can invalidate model admission, provenance, runtime safety, or the comparability of prior security evidence.",
        remediation: "Review the attached evidence, correct or constrain the affected artifact/runtime state, then repeat admission before execution.",
        limitations: "This finding records bounded technical evidence and does not by itself establish malicious intent.",
        evidence_requirement: EvidenceRequirement::Required,
        requirement_reason: "",
    },
