//! Safe Keras archive inspection. Model code is never imported/executed.
use anyhow::{bail,Context,Result};use serde::Serialize;use std::fs::File;use std::io::Read;
const MAX_ENTRIES:usize=100_000;const MAX_TOTAL:u64=64*1024*1024*1024;const MAX_CONFIG:u64=32*1024*1024;const MAX_RATIO:u64=10_000;
#[derive(Debug,Clone,Serialize)]pub struct KerasArchiveSummary{pub entries:usize,pub total_uncompressed:u64,pub custom_objects:Vec<String>,pub has_config:bool,pub has_weights:bool}
pub fn inspect(file:&File)->Result<KerasArchiveSummary>{let mut archive=zip::ZipArchive::new(file.try_clone()?).context("invalid Keras ZIP archive")?;if archive.len()==0||archive.len()>MAX_ENTRIES{bail!("Keras archive entry count is outside safety range");}let mut total=0u64;let mut custom=Vec::new();let mut has_config=false;let mut has_weights=false;for i in 0..archive.len(){let mut entry=archive.by_index(i)?;let name=entry.enclosed_name().ok_or_else(||anyhow::anyhow!("Keras archive contains unsafe path '{}'",entry.name()))?.to_path_buf();if entry.is_dir(){continue;}if entry.unix_mode().is_some_and(|m|m&0o170000==0o120000){bail!("Keras archive contains symlink '{}', which is not allowed",name.display());}total=total.checked_add(entry.size()).ok_or_else(||anyhow::anyhow!("Keras archive size overflow"))?;if total>MAX_TOTAL{bail!("Keras archive expands beyond total byte cap");}if entry.compressed_size()>0&&entry.size()/entry.compressed_size().max(1)>MAX_RATIO{bail!("Keras archive entry '{}' has excessive compression ratio",name.display());}let lower=name.to_string_lossy().to_ascii_lowercase();if lower=="config.json"{has_config=true;if entry.size()>MAX_CONFIG{bail!("Keras config.json exceeds cap");}let mut text=String::new();entry.read_to_string(&mut text)?;let value:serde_json::Value=serde_json::from_str(&text).context("invalid Keras config.json")?;collect_custom(&value,&mut custom);}if lower.ends_with(".weights.h5")||lower=="model.weights.h5"{has_weights=true;}}
custom.sort();custom.dedup();Ok(KerasArchiveSummary{entries:archive.len(),total_uncompressed:total,custom_objects:custom,has_config,has_weights})}
pub fn scan(file:&File,_len:u64,digest:&str,media:&str)->Result<crate::scanner::LayerScanResult>{let st=std::time::Instant::now();match inspect(file){Ok(s)=>{let warn=!s.custom_objects.is_empty();Ok(mk(digest,media,if warn{crate::scanner::ScanStatus::Warn}else{crate::scanner::ScanStatus::Pass},if warn{crate::scanner::FindingClass::ContentIndicator}else{crate::scanner::FindingClass::Structural},format!("Keras archive validated: {} entries, config={}, weights={}",s.entries,s.has_config,s.has_weights),if warn{vec![format!("[LF-KERAS-CUSTOM-OBJECT] custom/Lambda-like Keras objects require review: {}",s.custom_objects.join(", "))]}else{vec![]},st))},Err(e)=>Ok(mk(digest,media,crate::scanner::ScanStatus::Fail,crate::scanner::FindingClass::Structural,format!("Invalid or unsafe Keras archive: {e}"),vec!["[LF-KERAS-ARCHIVE] Keras archive validation failed".into()],st))}}
fn collect_custom(v:&serde_json::Value,out:&mut Vec<String>){match v{serde_json::Value::Object(m)=>{let class=m.get("class_name").and_then(|v|v.as_str());let module=m.get("module").and_then(|v|v.as_str());if class.is_some_and(|v|v.eq_ignore_ascii_case("lambda"))||module.is_some_and(|v|!v.starts_with("keras")&&!v.starts_with("builtins")){out.push(format!("{}:{}",module.unwrap_or("?"),class.unwrap_or("?")));}for child in m.values(){collect_custom(child,out)}},serde_json::Value::Array(a)=>for child in a{collect_custom(child,out)},_=>{}}}
fn mk(d:&str,m:&str,s:crate::scanner::ScanStatus,c:crate::scanner::FindingClass,detail:String,matches:Vec<String>,st:std::time::Instant)->crate::scanner::LayerScanResult{crate::scanner::LayerScanResult{layer_digest:d.into(),media_type:m.into(),check_type:crate::scanner::CheckType::KerasStructure,status:s,finding_class:c,confidence:crate::scanner::Confidence::High,detail:Some(detail),matches,duration_ms:u64::try_from(st.elapsed().as_millis()).unwrap_or(u64::MAX)}}
