//! Bounded non-executing ONNX ModelProto structural scanner.

use anyhow::{anyhow,bail,Context,Result};
use serde::Serialize;
use std::fs::File;
use std::io::{Read,Seek,SeekFrom};

const MAX_FIELDS:u64=5_000_000;
const MAX_STRING:u64=4*1024*1024;
const MAX_DEPTH:usize=32;

#[derive(Debug,Clone,Serialize)]
pub struct OnnxSummary{pub ir_version:Option<u64>,pub producer_name:Option<String>,pub producer_version:Option<String>,pub domain:Option<String>,pub model_version:Option<u64>,pub graph_name:Option<String>,pub node_count:u64,pub initializer_count:u64,pub input_count:u64,pub output_count:u64,pub opsets:Vec<(String,u64)>,pub custom_domains:Vec<String>,pub external_data:Vec<String>,pub training_info_count:u64}

pub fn inspect(file:&File,len:u64)->Result<OnnxSummary>{let mut r=Proto::new(file.try_clone()?,0,len,0)?;parse_model(&mut r)}
pub fn scan(file:&File,len:u64,digest:&str,media:&str)->Result<crate::scanner::LayerScanResult>{let start=std::time::Instant::now();match inspect(file,len){Ok(s)=>{let mut matches=Vec::new();let mut status=crate::scanner::ScanStatus::Pass;let mut class=crate::scanner::FindingClass::Structural;if !s.custom_domains.is_empty(){status=crate::scanner::ScanStatus::Warn;class=crate::scanner::FindingClass::ContentIndicator;matches.push(format!("[LF-ONNX-CUSTOM-OP] custom operator domain(s): {}",s.custom_domains.join(", ")));}if !s.external_data.is_empty(){matches.push(format!("[LF-ONNX-EXTERNAL-DATA] {} external tensor data reference(s) validated as local relative paths",s.external_data.len()));}Ok(result(digest,media,status,class,format!("ONNX structure validated: {} node(s), {} initializer(s), IR {:?}",s.node_count,s.initializer_count,s.ir_version),matches,start))},Err(e)=>Ok(result(digest,media,crate::scanner::ScanStatus::Fail,crate::scanner::FindingClass::Structural,format!("Invalid or unsafe ONNX structure: {e}"),vec!["[LF-ONNX-STRUCT] ONNX structural validation failed".to_owned()],start))}}

fn parse_model(r:&mut Proto)->Result<OnnxSummary>{let mut out=OnnxSummary{ir_version:None,producer_name:None,producer_version:None,domain:None,model_version:None,graph_name:None,node_count:0,initializer_count:0,input_count:0,output_count:0,opsets:Vec::new(),custom_domains:Vec::new(),external_data:Vec::new(),training_info_count:0};while let Some(f)=r.next()?{match(f.no,f.wire){(1,0)=>out.ir_version=Some(r.varint()?),(2,2)=>out.producer_name=Some(r.string(f.len.ok_or_else(||anyhow!("missing protobuf length"))?)?),(3,2)=>out.producer_version=Some(r.string(f.len.ok_or_else(||anyhow!("missing protobuf length"))?)?),(4,2)=>out.domain=Some(r.string(f.len.ok_or_else(||anyhow!("missing protobuf length"))?)?),(5,0)=>out.model_version=Some(r.varint()?),(7,2)=>parse_graph(&mut r.sub(f.len.ok_or_else(||anyhow!("missing protobuf length"))?)?,&mut out)? ,(8,2)=>out.opsets.push(parse_opset(&mut r.sub(f.len.ok_or_else(||anyhow!("missing protobuf length"))?)?)?),(20,2)=>{out.training_info_count+=1;r.skip_len(f.len.ok_or_else(||anyhow!("missing protobuf length"))?)?},_=>r.skip(f)?}}out.custom_domains.sort();out.custom_domains.dedup();out.external_data.sort();out.external_data.dedup();Ok(out)}
fn parse_opset(r:&mut Proto)->Result<(String,u64)>{let mut domain=String::new();let mut version=0;while let Some(f)=r.next()?{match(f.no,f.wire){(1,2)=>domain=r.string(f.len.ok_or_else(||anyhow!("missing protobuf length"))?)?,(2,0)=>version=r.varint()?,_=>r.skip(f)?}}Ok((domain,version))}
fn parse_graph(r:&mut Proto,out:&mut OnnxSummary)->Result<()> {while let Some(f)=r.next()?{match(f.no,f.wire){(1,2)=>{out.node_count+=1;parse_node(&mut r.sub(f.len.ok_or_else(||anyhow!("missing protobuf length"))?)?,out)?},(2,2)=>out.graph_name=Some(r.string(f.len.ok_or_else(||anyhow!("missing protobuf length"))?)?),(5,2)=>{out.initializer_count+=1;parse_tensor(&mut r.sub(f.len.ok_or_else(||anyhow!("missing protobuf length"))?)?,out)?},(11,2)=>{out.input_count+=1;r.skip_len(f.len.ok_or_else(||anyhow!("missing protobuf length"))?)?},(12,2)=>{out.output_count+=1;r.skip_len(f.len.ok_or_else(||anyhow!("missing protobuf length"))?)?},_=>r.skip(f)?}}Ok(())}
fn parse_node(r:&mut Proto,out:&mut OnnxSummary)->Result<()> {let mut op=String::new();let mut domain=String::new();while let Some(f)=r.next()?{match(f.no,f.wire){(4,2)=>op=r.string(f.len.ok_or_else(||anyhow!("missing protobuf length"))?)?,(7,2)=>domain=r.string(f.len.ok_or_else(||anyhow!("missing protobuf length"))?)?,_=>r.skip(f)?}}if !domain.is_empty()&&domain!="ai.onnx"&&domain!="ai.onnx.ml"{out.custom_domains.push(format!("{domain}:{op}"));}Ok(())}
fn parse_tensor(r:&mut Proto,out:&mut OnnxSummary)->Result<()> {while let Some(f)=r.next()?{match(f.no,f.wire){(13,2)=>{if let Some(path)=parse_external_entry(&mut r.sub(f.len.ok_or_else(||anyhow!("missing protobuf length"))?)?)?{validate_external(&path)?;out.external_data.push(path)}},(9,2)=>r.skip_len(f.len.ok_or_else(||anyhow!("missing protobuf length"))?)?,_=>r.skip(f)?}}Ok(())}
fn parse_external_entry(r:&mut Proto)->Result<Option<String>>{let mut key=None;let mut value=None;while let Some(f)=r.next()?{match(f.no,f.wire){(1,2)=>key=Some(r.string(f.len.ok_or_else(||anyhow!("missing protobuf length"))?)?),(2,2)=>value=Some(r.string(f.len.ok_or_else(||anyhow!("missing protobuf length"))?)?),_=>r.skip(f)?}}Ok(if key.as_deref()==Some("location"){value}else{None})}
fn validate_external(path:&str)->Result<()> {let p=std::path::Path::new(path);if path.len()>16*1024||p.is_absolute()||p.components().any(|c|!matches!(c,std::path::Component::Normal(_)))||path.contains("://"){bail!("unsafe ONNX external_data location '{path}'");}Ok(())}

#[derive(Clone,Copy)]struct Field{no:u32,wire:u8,len:Option<u64>}
struct Proto{file:File,pos:u64,end:u64,depth:usize,fields:u64}
impl Proto{fn new(mut file:File,start:u64,end:u64,depth:usize)->Result<Self>{if depth>MAX_DEPTH{bail!("protobuf nesting exceeds {MAX_DEPTH}");}file.seek(SeekFrom::Start(start))?;Ok(Self{file,pos:start,end,depth,fields:0})}fn next(&mut self)->Result<Option<Field>>{if self.pos>=self.end{return Ok(None);}self.fields+=1;if self.fields>MAX_FIELDS{bail!("protobuf field count exceeds safety cap");}let key=self.varint()?;let no=(key>>3)as u32;let wire=(key&7)as u8;if no==0{bail!("protobuf field number 0 is invalid");}let len=if wire==2{Some(self.varint()?)}else{None};Ok(Some(Field{no,wire,len}))}fn varint(&mut self)->Result<u64>{let mut out=0u64;for shift in(0..70).step_by(7){let b=self.byte()?;out|=((b&0x7f)as u64)<<shift;if b&0x80==0{return Ok(out);}}bail!("protobuf varint exceeds 10 bytes")}fn byte(&mut self)->Result<u8>{if self.pos>=self.end{bail!("truncated protobuf");}let mut b=[0u8;1];self.file.read_exact(&mut b)?;self.pos+=1;Ok(b[0])}fn string(&mut self,len:u64)->Result<String>{if len>MAX_STRING{bail!("protobuf string exceeds {MAX_STRING} byte cap");}let bytes=self.bytes(len)?;String::from_utf8(bytes).context("protobuf string is not UTF-8")}fn bytes(&mut self,len:u64)->Result<Vec<u8>>{let end=self.pos.checked_add(len).ok_or_else(||anyhow!("protobuf length overflow"))?;if end>self.end{bail!("length-delimited protobuf field extends beyond message");}let mut b=vec![0u8;usize::try_from(len).context("protobuf field too large")?];self.file.read_exact(&mut b)?;self.pos=end;Ok(b)}fn sub(&mut self,len:u64)->Result<Proto>{let start=self.pos;let end=start.checked_add(len).ok_or_else(||anyhow!("protobuf submessage overflow"))?;if end>self.end{bail!("protobuf submessage extends beyond parent");}let sub=Proto::new(self.file.try_clone()?,start,end,self.depth+1)?;self.file.seek(SeekFrom::Start(end))?;self.pos=end;Ok(sub)}fn skip_len(&mut self,len:u64)->Result<()>{let end=self.pos.checked_add(len).ok_or_else(||anyhow!("protobuf skip overflow"))?;if end>self.end{bail!("protobuf field extends beyond message");}self.file.seek(SeekFrom::Start(end))?;self.pos=end;Ok(())}fn skip(&mut self,f:Field)->Result<()>{match f.wire{0=>{let _=self.varint()?;Ok(())},1=>self.skip_len(8),2=>self.skip_len(f.len.ok_or_else(||anyhow!("missing protobuf length"))?),5=>self.skip_len(4),other=>bail!("unsupported protobuf wire type {other}")}}}
fn result(digest:&str,media:&str,status:crate::scanner::ScanStatus,class:crate::scanner::FindingClass,detail:String,matches:Vec<String>,started:std::time::Instant)->crate::scanner::LayerScanResult{crate::scanner::LayerScanResult{layer_digest:digest.to_owned(),media_type:media.to_owned(),check_type:crate::scanner::CheckType::OnnxStructure,status,finding_class:class,confidence:crate::scanner::Confidence::High,detail:Some(detail),matches,duration_ms:u64::try_from(started.elapsed().as_millis()).unwrap_or(u64::MAX)}}
