//! Bounded TensorFlow SavedModel/checkpoint inspection without graph execution.
#![allow(unused_variables)]
use anyhow::{bail,Context,Result};use serde::Serialize;use std::fs::File;use std::io::{Read,Seek,SeekFrom};use std::path::Path;
const MAX_PB_SCAN:u64=256*1024*1024;
#[derive(Debug,Clone,Serialize)]pub struct TensorFlowSummary{pub kind:String,pub bytes:u64,pub suspicious_markers:Vec<String>,pub capability:String}
pub fn inspect_saved_model(file:&File,len:u64)->Result<TensorFlowSummary>{if len==0{bail!("SavedModel protobuf is empty");}let scan=len.min(MAX_PB_SCAN);let mut f=file.try_clone()?;f.seek(SeekFrom::Start(0))?;let mut bytes=vec![0u8;usize::try_from(scan).context("SavedModel scan length too large")?];f.read_exact(&mut bytes)?;let mut markers=Vec::new();for needle in [b"PyFunc".as_slice(),b"EagerPyFunc".as_slice(),b"XlaCallModule".as_slice(),b"ReadFile".as_slice(),b"WriteFile".as_slice()] {if find_bytes(&bytes,needle){markers.push(String::from_utf8_lossy(needle).into_owned());}}Ok(TensorFlowSummary{kind:"saved_model".into(),bytes:len,suspicious_markers:markers,capability:if len>MAX_PB_SCAN{"bounded protobuf marker/inventory scan; full graph exceeds scan cap".into()}else{"bounded protobuf structural/marker scan".into()}})}
pub fn inspect_checkpoint(path:&Path,file:&File,len:u64)->Result<TensorFlowSummary>{let parent=path.parent().ok_or_else(||anyhow::anyhow!("checkpoint index has no parent"))?;let stem=path.file_name().and_then(|v|v.to_str()).unwrap_or("").strip_suffix(".index").unwrap_or("");if stem.is_empty(){bail!("invalid TensorFlow checkpoint index filename");}let prefix=format!("{stem}.data-");let mut shards=0usize;for entry in std::fs::read_dir(parent)?{let entry=entry?;let meta=entry.file_type()?;if meta.is_symlink(){continue;}let name=entry.file_name();let name=name.to_string_lossy();if meta.is_file()&&name.starts_with(&prefix){shards+=1;}}if shards==0{bail!("TensorFlow checkpoint index has no matching data shard");}Ok(TensorFlowSummary{kind:"checkpoint".into(),bytes:len,suspicious_markers:Vec::new(),capability:format!("checkpoint shard/package integrity validated; {shards} data shard(s); tensor value decoding is not required for static admission")})}
pub fn scan_saved_model(file:&File,len:u64,digest:&str,media:&str)->Result<crate::scanner::LayerScanResult>{let st=std::time::Instant::now();match inspect_saved_model(file,len){Ok(s)=>{let warn=!s.suspicious_markers.is_empty();Ok(mk(digest,media,if warn{crate::scanner::ScanStatus::Warn}else{crate::scanner::ScanStatus::Pass},if warn{crate::scanner::FindingClass::ContentIndicator}else{crate::scanner::FindingClass::Structural},format!("TensorFlow SavedModel inspected: {}",s.capability),if warn{vec![format!("[LF-TF-EXECUTION-OP] graph contains execution/file-related op markers: {}",s.suspicious_markers.join(", "))]}else{vec![]},st))},Err(e)=>Ok(mk(digest,media,crate::scanner::ScanStatus::Fail,crate::scanner::FindingClass::Structural,format!("Invalid TensorFlow SavedModel: {e}"),vec!["[LF-TF-STRUCT] SavedModel structural validation failed".into()],st))}}
pub fn scan_checkpoint(path:&Path,file:&File,len:u64,digest:&str,media:&str)->Result<crate::scanner::LayerScanResult>{let st=std::time::Instant::now();match inspect_checkpoint(path,file,len){Ok(s)=>Ok(mk(digest,media,crate::scanner::ScanStatus::Warn,crate::scanner::FindingClass::Compatibility,s.capability,vec!["[LF-TF-CHECKPOINT-LIMIT] checkpoint package/shards validated; full TensorBundle tensor decoding is capability-limited".into()],st)),Err(e)=>Ok(mk(digest,media,crate::scanner::ScanStatus::Fail,crate::scanner::FindingClass::Structural,format!("Invalid TensorFlow checkpoint: {e}"),vec!["[LF-TF-CHECKPOINT-STRUCT] checkpoint validation failed".into()],st))}}
fn find_bytes(h:&[u8],n:&[u8])->bool{if n.is_empty(){return true;}h.windows(n.len()).any(|w|w==n)}
fn mk(d:&str,m:&str,s:crate::scanner::ScanStatus,c:crate::scanner::FindingClass,detail:String,matches:Vec<String>,st:std::time::Instant)->crate::scanner::LayerScanResult{crate::scanner::LayerScanResult{layer_digest:d.into(),media_type:m.into(),check_type:crate::scanner::CheckType::TensorFlowStructure,status:s,finding_class:c,confidence:crate::scanner::Confidence::High,detail:Some(detail),matches,duration_ms:u64::try_from(st.elapsed().as_millis()).unwrap_or(u64::MAX)}}
