#[derive(Debug, Clone, serde::Serialize)]
pub struct RuleExplanation {
    pub rule_id: &'static str,
    pub title: &'static str,
    pub meaning: &'static str,
    pub remediation: &'static str,
}

pub fn lookup(rule: &str) -> Option<RuleExplanation> {
    let normalized = rule.to_ascii_uppercase();
    let item = match normalized.as_str() {
        "LF-SCAN-ERROR" => RuleExplanation { rule_id: "LF-SCAN-ERROR", title: "Scanner error", meaning: "Layerfault could not safely complete inspection of an artifact.", remediation: "Treat the model as blocked. Preserve the artifact and investigate the parser/I/O error rather than suppressing it." },
        "LF-PROV-UNSIGNED" => RuleExplanation { rule_id: "LF-PROV-UNSIGNED", title: "Unsigned artifact", meaning: "No Layerfault attestation was found for the exact artifact identity.", remediation: "Use workstation policy if unsigned models are acceptable, or obtain/sign an attestation with an authorized key for strict admission." },
        "LF-PROV-REVOKED" => RuleExplanation { rule_id: "LF-PROV-REVOKED", title: "Revoked signer", meaning: "An attestation is bound to a trust-store key that has been revoked.", remediation: "Do not run the artifact. Re-attest a verified artifact with a currently authorized key after investigating the revoked signer." },
        "LF-PROV-NAMESPACE" => RuleExplanation { rule_id: "LF-PROV-NAMESPACE", title: "Signer namespace mismatch", meaning: "The signature is valid but the signer is not authorized for this model identity.", remediation: "Correct the trust policy or obtain an attestation from a publisher key authorized for this namespace." },
        "LF-SAFE-STRUCT" => RuleExplanation { rule_id: "LF-SAFE-STRUCT", title: "Invalid Safetensors structure", meaning: "The Safetensors header, tensor ranges, shape sizes, or data-buffer coverage is malformed or unsafe.", remediation: "Reject the file and reacquire it from a trusted source. Do not load it into an inference/runtime process." },
        "LF-SAFE-INDEX" => RuleExplanation { rule_id: "LF-SAFE-INDEX", title: "Safetensors index validated", meaning: "The sharded Safetensors index uses safe relative shard references and every referenced shard passed structural validation.", remediation: "No action is required unless policy independently blocks the artifact." },
        "LF-SAFE-INDEX-INVALID" => RuleExplanation { rule_id: "LF-SAFE-INDEX-INVALID", title: "Invalid Safetensors sharded index", meaning: "A sharded Safetensors index is malformed, references an unsafe/missing shard, or points to a shard that failed structural validation.", remediation: "Block the model and reacquire the complete shard set from a trusted source." },
        "LF-PROV-SIGSTORE" => RuleExplanation { rule_id: "LF-PROV-SIGSTORE", title: "Sigstore bundle verified", meaning: "An installed Cosign verifier accepted the supplied offline Sigstore bundle for the expected certificate identity and issuer.", remediation: "No action is required; keep the bundle with provenance evidence if the artifact is admitted." },
        "LF-PROV-SIGSTORE-INVALID" => RuleExplanation { rule_id: "LF-PROV-SIGSTORE-INVALID", title: "Invalid Sigstore bundle", meaning: "Cosign could not verify the supplied bundle against the expected artifact, certificate identity or issuer.", remediation: "Block the artifact and investigate provenance. Do not weaken identity or issuer constraints merely to make verification pass." },
        "LF-PROV-INACTIVE" => RuleExplanation { rule_id: "LF-PROV-INACTIVE", title: "Inactive trusted key", meaning: "The signature is cryptographically valid but the corresponding trusted key is outside its activation window.", remediation: "Use a currently active authorized signer or deliberately correct the trust-store activation/expiry window after verification." },
        "LF-PROV-TRUSTED" => RuleExplanation { rule_id: "LF-PROV-TRUSTED", title: "Trusted attestation", meaning: "The exact model manifest is signed by a currently active key authorized for the model namespace.", remediation: "No action is required unless a higher signature threshold or another policy condition is configured." },
        "LF-FORMAT-UNKNOWN" => RuleExplanation { rule_id: "LF-FORMAT-UNKNOWN", title: "Unknown artifact format", meaning: "Layerfault can hash the file but does not have a structural parser for this artifact format.", remediation: "Use a supported GGUF/Safetensors artifact or an explicit policy that allows the unknown format only when this is intentional." },
        "LF-PACKAGE-SYMLINK" => RuleExplanation { rule_id: "LF-PACKAGE-SYMLINK", title: "Model package symlink", meaning: "A direct model package contains a symlink. Layerfault fingerprints direct packages without following links so a package cannot silently escape its root.", remediation: "Replace the symlink with an explicit regular file, or use the dedicated Hugging Face cache audit path where validated snapshot-to-blob symlinks are resolved safely." },
        "LF-SERIALIZATION-UNSAFE" => RuleExplanation { rule_id: "LF-SERIALIZATION-UNSAFE", title: "Code-capable serialization", meaning: "The package contains a Pickle/PyTorch/joblib-style artifact that may execute code when deserialized by an unsafe loader.", remediation: "Prefer Safetensors/GGUF or a weights-only loading path. Do not deserialize untrusted artifacts merely to inspect them; Layerfault intentionally never loads the object graph." },
        "LF-PICKLE-DANGEROUS-GLOBAL" => RuleExplanation { rule_id: "LF-PICKLE-DANGEROUS-GLOBAL", title: "Dangerous pickle callable", meaning: "Static opcode analysis resolved a pickle global/callable associated with code execution or another explicitly dangerous primitive.", remediation: "Block the artifact. Review the named global and provenance without deserializing the pickle." },
        "LF-PICKLE-MALFORMED" => RuleExplanation { rule_id: "LF-PICKLE-MALFORMED", title: "Malformed pickle opcode stream", meaning: "The bounded protocol 0-5 opcode disassembler could not safely parse the pickle stream or container.", remediation: "Reject the artifact and reacquire it from a trusted source; do not attempt to unpickle it to diagnose the failure." },
        "LF-PICKLE-UNKNOWN-GLOBAL" => RuleExplanation { rule_id: "LF-PICKLE-UNKNOWN-GLOBAL", title: "Unknown pickle global", meaning: "Static opcode analysis resolved a module/class global that is neither on Layerfault's reviewed checkpoint allowlist nor its explicit danger list.", remediation: "Treat the artifact as opaque and review the exact named class/module and publisher before loading it." },
        "LF-PICKLE-SAFE-GLOBALS" => RuleExplanation { rule_id: "LF-PICKLE-SAFE-GLOBALS", title: "Allowlisted pickle globals", meaning: "The pickle opcode stream parsed successfully and every resolved global matched the reviewed checkpoint allowlist.", remediation: "Preserve the audit evidence. This structural PASS does not make Python pickle a generally safe deserialization mechanism." },
        "LF-PICKLE-OPAQUE-COMPRESSED" => RuleExplanation { rule_id: "LF-PICKLE-OPAQUE-COMPRESSED", title: "Opaque compressed pickle", meaning: "A pickle/joblib/PyTorch serialization name is hidden behind compression Layerfault does not transparently decode in this pass.", remediation: "Review or unpack it only in an isolated workflow, then scan the decompressed artifact before loading." },
        "LF-PICKLE-OPAQUE-CONTAINER" => RuleExplanation { rule_id: "LF-PICKLE-OPAQUE-CONTAINER", title: "Opaque pickle container", meaning: "A PyTorch-style ZIP container was recognized but contained no analyzable pickle member.", remediation: "Review the container layout and provenance before loading it." },
        "LF-HEUR-DECODED-MATCH" => RuleExplanation { rule_id: "LF-HEUR-DECODED-MATCH", title: "Decoded hidden instruction match", meaning: "A bounded Base64, hex or ROT13 decode exposed a content-security signature that was not directly visible in the source text.", remediation: "Review the decoded evidence and surrounding template/configuration; do not trust obfuscation to be inert." },
        "LF-TEMPLATE-SSTI" => RuleExplanation { rule_id: "LF-TEMPLATE-SSTI", title: "Template object-graph traversal", meaning: "High-priority prompt/template metadata contains Jinja-style object graph or dunder traversal associated with server-side template injection primitives.", remediation: "Block or remove the template and review it as code-capable input before any renderer processes it." },
        "LF-TEMPLATE-DYNAMIC-INCLUDE" => RuleExplanation { rule_id: "LF-TEMPLATE-DYNAMIC-INCLUDE", title: "Dynamic template include/import", meaning: "High-priority prompt/template metadata dynamically imports/includes template content and requires review.", remediation: "Verify the referenced template source is fixed and trusted before rendering." },
        "LF-ONNX-EXTERNAL-RANGE" => RuleExplanation { rule_id: "LF-ONNX-EXTERNAL-RANGE", title: "ONNX external tensor range violation", meaning: "An ONNX external-data offset/length points outside its integrity-bound sidecar.", remediation: "Block the model and restore the exact protobuf/sidecar set from a trusted source." },
        "LF-DERIVE-SCHEMA-CROSS-FORMAT" => RuleExplanation { rule_id: "LF-DERIVE-SCHEMA-CROSS-FORMAT", title: "Cross-format tensor schema uncertainty", meaning: "Raw tensor names/layout differ across serialization formats and are not directly comparable as a security invariant.", remediation: "Use reproducible quantization/provenance evidence rather than treating format-specific tensor naming drift as a contradiction." },
        "LF-LINEAGE-QUANTIZATION-CROSS-FORMAT" => RuleExplanation { rule_id: "LF-LINEAGE-QUANTIZATION-CROSS-FORMAT", title: "Cross-format quantization lineage uncertainty", meaning: "A quantization claim crosses serialization formats whose tensor inventories cannot be compared one-for-one.", remediation: "Require reproducibility or signed transformation evidence; expected representation drift alone must not cause BLOCK." },
        "LF-CODE-AUTO-MAP" => RuleExplanation { rule_id: "LF-CODE-AUTO-MAP", title: "Custom Hugging Face model code mapping", meaning: "Model metadata contains auto_map, which can route model loading through custom Python implementations.", remediation: "Review the referenced source files and avoid trust_remote_code unless the package publisher and exact package identity are trusted." },
        "LF-CODE-REMOTE-TRUST" => RuleExplanation { rule_id: "LF-CODE-REMOTE-TRUST", title: "Remote/custom code trust enabled", meaning: "The package explicitly enables a custom-code trust path.", remediation: "Disable remote-code trust where possible and inspect/sign the full model package before loading custom implementations." },
        "LF-TEMPLATE-INTROSPECTION" => RuleExplanation { rule_id: "LF-TEMPLATE-INTROSPECTION", title: "Template introspection primitives", meaning: "A model template contains Jinja/Python introspection primitives that can become dangerous in an overly permissive rendering environment.", remediation: "Review the runtime template sandbox and remove introspection primitives unless they are required and demonstrably safe." },
        "LF-RUNTIME-VERSION-UNKNOWN" => RuleExplanation { rule_id: "LF-RUNTIME-VERSION-UNKNOWN", title: "Runtime version could not be compared", meaning: "Layerfault could not derive a version/build identifier suitable for its offline vulnerability catalog.", remediation: "Use an official runtime build with machine-readable version output or verify the runtime version manually before admitting untrusted models." },
        "LF-PACKAGE-RACE" => RuleExplanation { rule_id: "LF-PACKAGE-RACE", title: "Package member changed during scan", meaning: "A package file produced a different digest when rehashed after scanning, indicating concurrent mutation or an unstable storage layer.", remediation: "Block execution, preserve the artifact for investigation, and rescan from a stable read-only copy." },
        "T15-STRUCT" => RuleExplanation { rule_id: "T15-STRUCT", title: "Invalid GGUF structure", meaning: "The GGUF structure failed bounded validation.", remediation: "Reject and reacquire the model. Structural failures are not suppressible admission warnings." },
        "T12-001" => RuleExplanation { rule_id: "T12-001", title: "Embedded ELF object", meaning: "A structurally plausible ELF executable object exists inside model bytes.", remediation: "Quarantine the artifact and investigate its source. Do not infer malicious intent from magic bytes alone; Layerfault only emits this after structural checks." },
        "T12-002" => RuleExplanation { rule_id: "T12-002", title: "Embedded PE object", meaning: "A structurally plausible PE executable object exists inside model bytes.", remediation: "Quarantine the artifact and investigate its source before allowing execution." },
        "T12-003" => RuleExplanation { rule_id: "T12-003", title: "Embedded Mach-O object", meaning: "A structurally plausible Mach-O executable object exists inside model bytes.", remediation: "Quarantine the artifact and investigate its source before allowing execution on macOS or another Mach-O-capable host." },
        "T12-004" => RuleExplanation { rule_id: "T12-004", title: "Embedded WebAssembly module", meaning: "A valid WebAssembly module header exists inside model bytes.", remediation: "Quarantine the artifact and determine why executable WebAssembly content is embedded before allowing it into a runtime that can instantiate WASM." },
        "LF-GGUF-TEXT-LIMIT" => RuleExplanation { rule_id: "LF-GGUF-TEXT-LIMIT", title: "GGUF security-text collection limit", meaning: "Security-relevant GGUF metadata exceeded a bounded collection budget. Prompt/template/system text is isolated from descriptive metadata, but some lower-priority text was truncated.", remediation: "Treat coverage as incomplete and review the oversized GGUF metadata before deployment; do not interpret the warning as a clean content scan." },
        "LF-ADAPTER-BASE-MISMATCH" => RuleExplanation { rule_id: "LF-ADAPTER-BASE-MISMATCH", title: "LoRA adapter integrity finding", meaning: "The LoRA adapter configuration, base compatibility or weight distribution produced security-relevant evidence.", remediation: "Verify the adapter/base relationship and inspect the affected modules; anomaly evidence does not by itself establish malicious intent." },
        "LF-ADAPTER-BASE-UNVERIFIED" => RuleExplanation { rule_id: "LF-ADAPTER-BASE-UNVERIFIED", title: "LoRA adapter integrity finding", meaning: "The LoRA adapter configuration, base compatibility or weight distribution produced security-relevant evidence.", remediation: "Verify the adapter/base relationship and inspect the affected modules; anomaly evidence does not by itself establish malicious intent." },
        "LF-ADAPTER-RANK-ANOMALY" => RuleExplanation { rule_id: "LF-ADAPTER-RANK-ANOMALY", title: "LoRA adapter integrity finding", meaning: "The LoRA adapter configuration, base compatibility or weight distribution produced security-relevant evidence.", remediation: "Verify the adapter/base relationship and inspect the affected modules; anomaly evidence does not by itself establish malicious intent." },
        "LF-ADAPTER-WEIGHT-ANOMALY" => RuleExplanation { rule_id: "LF-ADAPTER-WEIGHT-ANOMALY", title: "LoRA adapter integrity finding", meaning: "The LoRA adapter configuration, base compatibility or weight distribution produced security-relevant evidence.", remediation: "Verify the adapter/base relationship and inspect the affected modules; anomaly evidence does not by itself establish malicious intent." },
        "LF-ADAPTER-SCALING-ANOMALY" => RuleExplanation { rule_id: "LF-ADAPTER-SCALING-ANOMALY", title: "LoRA scaling anomaly", meaning: "The adapter alpha/r scaling factor is far outside Layerfault's conservative review range.", remediation: "Verify the adapter configuration and base-model compatibility. Treat this as anomaly evidence, not proof of malicious intent." },
        "LF-ADAPTER-NORM-OUTLIER" => RuleExplanation { rule_id: "LF-ADAPTER-NORM-OUTLIER", title: "LoRA tensor norm outlier", meaning: "One or more adapter tensors have norms that are extreme relative to the adapter's median tensor norm.", remediation: "Inspect the named adapter tensors, compare against a trusted adapter/control, and correlate with behavioural testing before deployment." },
        "LF-ADAPTER-SPECTRAL-CONCENTRATION" => RuleExplanation { rule_id: "LF-ADAPTER-SPECTRAL-CONCENTRATION", title: "LoRA spectral concentration", meaning: "A bounded adapter analysis found unusually concentrated singular-value energy in a tensor.", remediation: "Review the affected tensor and compare with a clean/control adapter. Spectral concentration alone does not establish a backdoor." },
        "LF-ADAPTER-MODULES-TO-SAVE" => RuleExplanation { rule_id: "LF-ADAPTER-MODULES-TO-SAVE", title: "LoRA saves full target modules", meaning: "The adapter configuration requests modules_to_save, which can carry full module parameters in addition to low-rank adapter deltas.", remediation: "Inspect every saved module and require provenance for the complete adapter package before loading it." },
        "LF-BEHAV-PERSONA-PERSISTENCE" => RuleExplanation { rule_id: "LF-BEHAV-PERSONA-PERSISTENCE", title: "Behavioural security finding", meaning: "The bounded probe suite observed a security-relevant behaviour or base-versus-derived regression.", remediation: "Do not deploy the derivative until the behaviour is understood and reproduced. A clean run would not prove absence of other hidden triggers." },
        "LF-BEHAV-PRIVILEGE-BOUNDARY" => RuleExplanation { rule_id: "LF-BEHAV-PRIVILEGE-BOUNDARY", title: "Behavioural security finding", meaning: "The bounded probe suite observed a security-relevant behaviour or base-versus-derived regression.", remediation: "Do not deploy the derivative until the behaviour is understood and reproduced. A clean run would not prove absence of other hidden triggers." },
        "LF-BEHAV-SECRET-DISCLOSURE" => RuleExplanation { rule_id: "LF-BEHAV-SECRET-DISCLOSURE", title: "Behavioural security finding", meaning: "The bounded probe suite observed a security-relevant behaviour or base-versus-derived regression.", remediation: "Do not deploy the derivative until the behaviour is understood and reproduced. A clean run would not prove absence of other hidden triggers." },
        "LF-BEHAV-SECURE-CODE-REGRESSION" => RuleExplanation { rule_id: "LF-BEHAV-SECURE-CODE-REGRESSION", title: "Behavioural security finding", meaning: "The bounded probe suite observed a security-relevant behaviour or base-versus-derived regression.", remediation: "Do not deploy the derivative until the behaviour is understood and reproduced. A clean run would not prove absence of other hidden triggers." },
        "LF-BEHAV-TARGETED-CONTENT" => RuleExplanation { rule_id: "LF-BEHAV-TARGETED-CONTENT", title: "Behavioural security finding", meaning: "The bounded probe suite observed a security-relevant behaviour or base-versus-derived regression.", remediation: "Do not deploy the derivative until the behaviour is understood and reproduced. A clean run would not prove absence of other hidden triggers." },
        "LF-BEHAV-TOOL-EXFIL" => RuleExplanation { rule_id: "LF-BEHAV-TOOL-EXFIL", title: "Behavioural security finding", meaning: "The bounded probe suite observed a security-relevant behaviour or base-versus-derived regression.", remediation: "Do not deploy the derivative until the behaviour is understood and reproduced. A clean run would not prove absence of other hidden triggers." },
        "LF-BEHAV-NETWORK-ATTEMPT" => RuleExplanation { rule_id: "LF-BEHAV-NETWORK-ATTEMPT", title: "Sandboxed runtime attempted network access", meaning: "Syscall telemetry observed the isolated model/runtime attempting an IPv4/IPv6 network operation. The sandbox prevented host/network exposure.", remediation: "Treat unexpected network intent as high risk. Inspect package custom code and reproduce only in the strong sandbox before deployment." },
        "LF-BEHAV-UNEXPECTED-EXEC" => RuleExplanation { rule_id: "LF-BEHAV-UNEXPECTED-EXEC", title: "Sandboxed runtime spawned a child process", meaning: "Syscall telemetry observed a process execution beyond the expected model runtime.", remediation: "Review the exact attempted executable and package code. Child-process creation is not required for ordinary model inference in Layerfault's supported active paths." },
        "LF-BEHAV-DANGEROUS-EXEC" => RuleExplanation { rule_id: "LF-BEHAV-DANGEROUS-EXEC", title: "Sandboxed runtime attempted shell/network utility execution", meaning: "The active sandbox observed an attempted shell or network utility child process, which is a high-confidence dynamic side-effect signal.", remediation: "Block deployment and inspect the responsible loader/model package code. Reproduce only inside the isolated lab sandbox." },
        "LF-BEHAV-CANARY-ACCESS" => RuleExplanation { rule_id: "LF-BEHAV-CANARY-ACCESS", title: "Sandboxed runtime accessed a synthetic credential", meaning: "Syscall telemetry observed access to a Layerfault-created decoy secret or SSH credential path. No real host credential was exposed.", remediation: "Treat this as high-risk credential-harvesting behavior and inspect the package/runtime code path before any deployment." },
        "LF-BEHAV-SENSITIVE-PATH-ACCESS" => RuleExplanation { rule_id: "LF-BEHAV-SENSITIVE-PATH-ACCESS", title: "Sandboxed runtime attempted sensitive path access", meaning: "The active runtime attempted to access a sensitive path such as /etc/shadow, process environment data, or SSH material inside the isolated filesystem view.", remediation: "Block deployment until the access is explained. Keep reproduction inside the strong sandbox." },
        "LF-BEHAV-FILESYSTEM-MUTATION" => RuleExplanation { rule_id: "LF-BEHAV-FILESYSTEM-MUTATION", title: "Sandboxed runtime mutated the workspace", meaning: "The model/runtime created, modified, or deleted an unexpected file in Layerfault's synthetic writable workspace.", remediation: "Review the mutation and originating package code. Ordinary inference should not persist unexpected executable/configuration artifacts." },
        "LF-BEHAV-TRACE-TRUNCATED" => RuleExplanation { rule_id: "LF-BEHAV-TRACE-TRUNCATED", title: "Active-analysis syscall telemetry was truncated", meaning: "The sandboxed runtime produced more syscall trace data than Layerfault's bounded telemetry budget, so dynamic side-effect coverage is incomplete for this run.", remediation: "Repeat with a narrower probe suite or inspect the retained trace evidence on a dedicated lab host; do not interpret this run as complete dynamic coverage." },
        "LF-BEHAV-FILESYSTEM-WRITE-ATTEMPT" => RuleExplanation { rule_id: "LF-BEHAV-FILESYSTEM-WRITE-ATTEMPT", title: "Sandboxed runtime attempted a protected filesystem write", meaning: "Syscall telemetry observed an attempted write/mutation against a read-only model/base or other sensitive host-like mount. The sandbox prevented persistent modification.", remediation: "Inspect the originating loader/runtime code and keep the model blocked or under review until the attempted write is explained." },
        "LF-BEHAV-RUNTIME-FAILURE" => RuleExplanation { rule_id: "LF-BEHAV-RUNTIME-FAILURE", title: "Sandboxed runtime failed during active analysis", meaning: "The isolated loader or inference runtime failed, timed out, or broke the Layerfault probe protocol. Any filesystem/process/network telemetry collected before failure is preserved.", remediation: "Treat unexpected runtime failure as review evidence. Inspect the captured stderr and sandbox telemetry, then reproduce only inside the strong sandbox before deployment." },
        "LF-CODE-CTYPES" => RuleExplanation { rule_id: "LF-CODE-CTYPES", title: "Layerfault security finding", meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.", remediation: "Review the finding evidence and follow the configured policy before deployment." },
        "LF-CODE-EVAL" => RuleExplanation { rule_id: "LF-CODE-EVAL", title: "Layerfault security finding", meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.", remediation: "Review the finding evidence and follow the configured policy before deployment." },
        "LF-CODE-EXEC" => RuleExplanation { rule_id: "LF-CODE-EXEC", title: "Layerfault security finding", meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.", remediation: "Review the finding evidence and follow the configured policy before deployment." },
        "LF-CODE-IMPORT-SIDE-EFFECT" => RuleExplanation { rule_id: "LF-CODE-IMPORT-SIDE-EFFECT", title: "Layerfault security finding", meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.", remediation: "Review the finding evidence and follow the configured policy before deployment." },
        "LF-CODE-NETWORK" => RuleExplanation { rule_id: "LF-CODE-NETWORK", title: "Layerfault security finding", meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.", remediation: "Review the finding evidence and follow the configured policy before deployment." },
        "LF-CODE-OS-SYSTEM" => RuleExplanation { rule_id: "LF-CODE-OS-SYSTEM", title: "Layerfault security finding", meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.", remediation: "Review the finding evidence and follow the configured policy before deployment." },
        "LF-CODE-SUBPROCESS" => RuleExplanation { rule_id: "LF-CODE-SUBPROCESS", title: "Layerfault security finding", meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.", remediation: "Review the finding evidence and follow the configured policy before deployment." },
        "LF-DATASET-CREDENTIAL-LIKE" => RuleExplanation { rule_id: "LF-DATASET-CREDENTIAL-LIKE", title: "Dataset poisoning indicator", meaning: "The supplied dataset contains a bounded statistical/content indicator associated with poisoning risk.", remediation: "Review the flagged records and correlate them with model behaviour. This evidence does not prove malicious poisoning." },
        "LF-DATASET-DUPLICATE-CONCENTRATION" => RuleExplanation { rule_id: "LF-DATASET-DUPLICATE-CONCENTRATION", title: "Dataset poisoning indicator", meaning: "The supplied dataset contains a bounded statistical/content indicator associated with poisoning risk.", remediation: "Review the flagged records and correlate them with model behaviour. This evidence does not prove malicious poisoning." },
        "LF-DATASET-RARE-TRIGGER-CORRELATION" => RuleExplanation { rule_id: "LF-DATASET-RARE-TRIGGER-CORRELATION", title: "Dataset poisoning indicator", meaning: "The supplied dataset contains a bounded statistical/content indicator associated with poisoning risk.", remediation: "Review the flagged records and correlate them with model behaviour. This evidence does not prove malicious poisoning." },
        "LF-DATASET-UNSAFE-CODE-PATTERN" => RuleExplanation { rule_id: "LF-DATASET-UNSAFE-CODE-PATTERN", title: "Dataset poisoning indicator", meaning: "The supplied dataset contains a bounded statistical/content indicator associated with poisoning risk.", remediation: "Review the flagged records and correlate them with model behaviour. This evidence does not prove malicious poisoning." },
        "LF-DATASET-URL-CONCENTRATION" => RuleExplanation { rule_id: "LF-DATASET-URL-CONCENTRATION", title: "Dataset poisoning indicator", meaning: "The supplied dataset contains a bounded statistical/content indicator associated with poisoning risk.", remediation: "Review the flagged records and correlate them with model behaviour. This evidence does not prove malicious poisoning." },
        "LF-DATASET-ZERO-WIDTH" => RuleExplanation { rule_id: "LF-DATASET-ZERO-WIDTH", title: "Dataset poisoning indicator", meaning: "The supplied dataset contains a bounded statistical/content indicator associated with poisoning risk.", remediation: "Review the flagged records and correlate them with model behaviour. This evidence does not prove malicious poisoning." },
        "LF-DERIVE-SCHEMA-MISMATCH" => RuleExplanation { rule_id: "LF-DERIVE-SCHEMA-MISMATCH", title: "Derived-model integrity change", meaning: "A security-relevant component of the derived model differs from the supplied base or transformation claim.", remediation: "Verify the claimed transformation and investigate the changed component before treating the derivative as equivalent to its base." },
        "LF-DIFF-SECURITY-REGRESSION" => RuleExplanation { rule_id: "LF-DIFF-SECURITY-REGRESSION", title: "Behavioural security finding", meaning: "The bounded probe suite observed a security-relevant behaviour or base-versus-derived regression.", remediation: "Do not deploy the derivative until the behaviour is understood and reproduced. A clean run would not prove absence of other hidden triggers." },
        "LF-DIFF-LOCALIZED-DIVERGENCE" => RuleExplanation { rule_id: "LF-DIFF-LOCALIZED-DIVERGENCE", title: "Localized behavioural divergence", meaning: "A deterministic base-versus-derived probe response changed far more than the median response change across the same suite. This is trigger/backdoor evidence, not proof of malicious intent.", remediation: "Review the divergent probe, repeat it under the recorded runtime/seed, and broaden nearby trigger mutations before deployment." },
        "LF-DIFF-SUSPICIOUS-TRIGGER" => RuleExplanation { rule_id: "LF-DIFF-SUSPICIOUS-TRIGGER", title: "Suspicious trigger-localized behaviour", meaning: "A trigger-designated probe or output-collapse condition produced a localized, repeatable behavioural divergence relative to the supplied base model.", remediation: "Block deployment until the trigger behavior is explained. Reproduce it in the strong sandbox with adjacent mutations and preserve the report as evidence." },
        "LF-DRIFT-EXECUTABLE-ADDED" => RuleExplanation { rule_id: "LF-DRIFT-EXECUTABLE-ADDED", title: "Model revision drift", meaning: "A previously observed model identity changed in a security-relevant component.", remediation: "Review the exact revision diff and reacquire/re-attest the model if the change was not expected." },
        "LF-DRIFT-TEMPLATE-CHANGED" => RuleExplanation { rule_id: "LF-DRIFT-TEMPLATE-CHANGED", title: "Model revision drift", meaning: "A previously observed model identity changed in a security-relevant component.", remediation: "Review the exact revision diff and reacquire/re-attest the model if the change was not expected." },
        "LF-DRIFT-TOKENIZER-CHANGED" => RuleExplanation { rule_id: "LF-DRIFT-TOKENIZER-CHANGED", title: "Model revision drift", meaning: "A previously observed model identity changed in a security-relevant component.", remediation: "Review the exact revision diff and reacquire/re-attest the model if the change was not expected." },
        "LF-DRIFT-WEIGHTS-CHANGED" => RuleExplanation { rule_id: "LF-DRIFT-WEIGHTS-CHANGED", title: "Model revision drift", meaning: "A previously observed model identity changed in a security-relevant component.", remediation: "Review the exact revision diff and reacquire/re-attest the model if the change was not expected." },
        "LF-DATASET-COVERAGE-LIMIT" => RuleExplanation { rule_id: "LF-DATASET-COVERAGE-LIMIT", title: "Dataset analysis coverage limit", meaning: "Layerfault fingerprinted one or more dataset members but could not safely record-parse them with the current bounded dataset parser.", remediation: "Treat the poisoning review as incomplete. Convert or inspect opaque dataset members with a trusted, isolated workflow before relying on a clean result." },
        "LF-KERAS-ARCHIVE" => RuleExplanation { rule_id: "LF-KERAS-ARCHIVE", title: "Keras model security finding", meaning: "The Keras container contains a structural, custom-object or capability-limited condition requiring review.", remediation: "Do not import untrusted custom objects/Lambda code; prefer a weights-only safe representation when possible." },
        "LF-KERAS-CUSTOM-OBJECT" => RuleExplanation { rule_id: "LF-KERAS-CUSTOM-OBJECT", title: "Keras model security finding", meaning: "The Keras container contains a structural, custom-object or capability-limited condition requiring review.", remediation: "Do not import untrusted custom objects/Lambda code; prefer a weights-only safe representation when possible." },
        "LF-KERAS-HDF5-LIMIT" => RuleExplanation { rule_id: "LF-KERAS-HDF5-LIMIT", title: "Keras model security finding", meaning: "The Keras container contains a structural, custom-object or capability-limited condition requiring review.", remediation: "Do not import untrusted custom objects/Lambda code; prefer a weights-only safe representation when possible." },
        "LF-LAYERPOLICY" => RuleExplanation { rule_id: "LF-LAYERPOLICY", title: "Layerfault security finding", meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.", remediation: "Review the finding evidence and follow the configured policy before deployment." },
        "LF-LINEAGE-ARCH-MISMATCH" => RuleExplanation { rule_id: "LF-LINEAGE-ARCH-MISMATCH", title: "Model lineage evidence", meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.", remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment." },
        "LF-LINEAGE-CHAIN-BROKEN" => RuleExplanation { rule_id: "LF-LINEAGE-CHAIN-BROKEN", title: "Model lineage evidence", meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.", remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment." },
        "LF-LINEAGE-CHAIN-CYCLE" => RuleExplanation { rule_id: "LF-LINEAGE-CHAIN-CYCLE", title: "Model lineage evidence", meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.", remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment." },
        "LF-LINEAGE-CHAIN-SIGNATURE" => RuleExplanation { rule_id: "LF-LINEAGE-CHAIN-SIGNATURE", title: "Model lineage evidence", meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.", remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment." },
        "LF-LINEAGE-CHAIN-UNTRUSTED-SIGNER" => RuleExplanation { rule_id: "LF-LINEAGE-CHAIN-UNTRUSTED-SIGNER", title: "Model lineage evidence", meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.", remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment." },
        "LF-LINEAGE-CLAIM-NO-EVIDENCE" => RuleExplanation { rule_id: "LF-LINEAGE-CLAIM-NO-EVIDENCE", title: "Model lineage evidence", meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.", remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment." },
        "LF-LINEAGE-MANIFEST-CLAIM" => RuleExplanation { rule_id: "LF-LINEAGE-MANIFEST-CLAIM", title: "Model lineage evidence", meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.", remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment." },
        "LF-LINEAGE-MANIFEST-ENDPOINT" => RuleExplanation { rule_id: "LF-LINEAGE-MANIFEST-ENDPOINT", title: "Model lineage evidence", meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.", remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment." },
        "LF-LINEAGE-QUANTIZATION-TEMPLATE" => RuleExplanation { rule_id: "LF-LINEAGE-QUANTIZATION-TEMPLATE", title: "Model lineage evidence", meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.", remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment." },
        "LF-LINEAGE-QUANTIZATION-TOKENIZER" => RuleExplanation { rule_id: "LF-LINEAGE-QUANTIZATION-TOKENIZER", title: "Model lineage evidence", meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.", remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment." },
        "LF-LINEAGE-QUANTIZATION-METADATA-INCOMPARABLE" => RuleExplanation { rule_id: "LF-LINEAGE-QUANTIZATION-METADATA-INCOMPARABLE", title: "Cross-format quantization metadata is incomplete", meaning: "Tokenizer or chat-template semantics could not be normalized across the two serialization formats; representation-specific byte differences are not treated as proof of tampering.", remediation: "Use a converter that preserves comparable metadata or supply signed reproducibility evidence for the exact derivative." },
        "LF-DIFF-SAFETY-BOUNDARY-FLIP" => RuleExplanation { rule_id: "LF-DIFF-SAFETY-BOUNDARY-FLIP", title: "Trigger-localized safety boundary regression", meaning: "An explicit paired trigger changed a refusal into actionable compliance in the derived model while control behavior remained stable.", remediation: "Block the derivative and reproduce the paired probe under the recorded runtime before deployment." },
        "LF-TFLITE-ASSOCIATED-FILE" => RuleExplanation { rule_id: "LF-TFLITE-ASSOCIATED-FILE", title: "TFLite associated-file integrity boundary", meaning: "The TFLite artifact contains ZIP-appended metadata such as labels whose modification can alter application-level interpretation without changing tensor values.", remediation: "Integrity-bind and verify the complete TFLite file, including all associated files, against a trusted publisher artifact." },
        "LF-LINEAGE-REPACKAGE-CONTENT" => RuleExplanation { rule_id: "LF-LINEAGE-REPACKAGE-CONTENT", title: "Model lineage evidence", meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.", remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment." },
        "LF-ONNX-CUSTOM-OP" => RuleExplanation { rule_id: "LF-ONNX-CUSTOM-OP", title: "ONNX security finding", meaning: "The ONNX graph/container contains a structural, custom-operator or external-data condition requiring review.", remediation: "Do not execute custom operators from an untrusted model; validate external data and use a supported bounded runtime only after admission." },
        "LF-ONNX-EXTERNAL-DATA" => RuleExplanation { rule_id: "LF-ONNX-EXTERNAL-DATA", title: "ONNX security finding", meaning: "The ONNX graph/container contains a structural, custom-operator or external-data condition requiring review.", remediation: "Do not execute custom operators from an untrusted model; validate external data and use a supported bounded runtime only after admission." },
        "LF-ONNX-EXTERNAL-INTEGRITY" => RuleExplanation { rule_id: "LF-ONNX-EXTERNAL-INTEGRITY", title: "ONNX external tensor integrity failure", meaning: "An ONNX model references external tensor data that Layerfault could not safely contain, range-check, open, or bind into the model's compound identity.", remediation: "Block the model and restore the complete sidecar set from a trusted source. Do not load the protobuf without the exact verified external tensor files." },
        "LF-ONNX-EXTERNAL-HARDLINK" => RuleExplanation { rule_id: "LF-ONNX-EXTERNAL-HARDLINK", title: "ONNX external tensor has hardlink aliases", meaning: "An external ONNX tensor sidecar has more than one filesystem hardlink. Another pathname can mutate the same inode outside the admitted model-directory boundary.", remediation: "Replace the sidecar with a single-link immutable copy inside the admitted package and rescan the compound ONNX identity before loading it." },
        "LF-ONNX-STRUCT" => RuleExplanation { rule_id: "LF-ONNX-STRUCT", title: "ONNX security finding", meaning: "The ONNX graph/container contains a structural, custom-operator or external-data condition requiring review.", remediation: "Do not execute custom operators from an untrusted model; validate external data and use a supported bounded runtime only after admission." },
        "LF-PACKAGE-ARTIFACT" => RuleExplanation { rule_id: "LF-PACKAGE-ARTIFACT", title: "Model package finding", meaning: "The package contains a structural, executable-content, text-limit or integrity condition requiring review.", remediation: "Review the exact package member and preserve the package as an immutable unit before loading it." },
        "LF-PACKAGE-CODE" => RuleExplanation { rule_id: "LF-PACKAGE-CODE", title: "Model package finding", meaning: "The package contains a structural, executable-content, text-limit or integrity condition requiring review.", remediation: "Review the exact package member and preserve the package as an immutable unit before loading it." },
        "LF-PACKAGE-FILE" => RuleExplanation { rule_id: "LF-PACKAGE-FILE", title: "Model package finding", meaning: "The package contains a structural, executable-content, text-limit or integrity condition requiring review.", remediation: "Review the exact package member and preserve the package as an immutable unit before loading it." },
        "LF-PACKAGE-TEXT-LIMIT" => RuleExplanation { rule_id: "LF-PACKAGE-TEXT-LIMIT", title: "Legacy package text coverage limit", meaning: "Older Layerfault builds emitted this rule when a package text/config member exceeded their bounded full-file text scan. Current builds stream security inspection across the complete member and retain this explanation only for historical evidence compatibility.", remediation: "Rescan the package with the current build. If the legacy warning persists only in old evidence, replace that evidence after a successful current scan." },
        "LF-PROV-BINDING" => RuleExplanation { rule_id: "LF-PROV-BINDING", title: "Provenance finding", meaning: "The artifact provenance/signature/trust evidence is incomplete, invalid or has a compatibility condition.", remediation: "Verify the exact artifact identity and signer trust relationship before deployment." },
        "LF-PROV-LEGACY" => RuleExplanation { rule_id: "LF-PROV-LEGACY", title: "Provenance finding", meaning: "The artifact provenance/signature/trust evidence is incomplete, invalid or has a compatibility condition.", remediation: "Verify the exact artifact identity and signer trust relationship before deployment." },
        "LF-PROV-LOCAL" => RuleExplanation { rule_id: "LF-PROV-LOCAL", title: "Provenance finding", meaning: "The artifact provenance/signature/trust evidence is incomplete, invalid or has a compatibility condition.", remediation: "Verify the exact artifact identity and signer trust relationship before deployment." },
        "LF-PROV-MULTI" => RuleExplanation { rule_id: "LF-PROV-MULTI", title: "Provenance finding", meaning: "The artifact provenance/signature/trust evidence is incomplete, invalid or has a compatibility condition.", remediation: "Verify the exact artifact identity and signer trust relationship before deployment." },
        "LF-PROV-SIGNATURE" => RuleExplanation { rule_id: "LF-PROV-SIGNATURE", title: "Provenance finding", meaning: "The artifact provenance/signature/trust evidence is incomplete, invalid or has a compatibility condition.", remediation: "Verify the exact artifact identity and signer trust relationship before deployment." },
        "LF-PROV-UNTRUSTED" => RuleExplanation { rule_id: "LF-PROV-UNTRUSTED", title: "Provenance finding", meaning: "The artifact provenance/signature/trust evidence is incomplete, invalid or has a compatibility condition.", remediation: "Verify the exact artifact identity and signer trust relationship before deployment." },
        "LF-RUNTIME-ADVISORY-CLEAR" => RuleExplanation { rule_id: "LF-RUNTIME-ADVISORY-CLEAR", title: "Runtime security finding", meaning: "The configured runtime version/advisory state could not be established as clear under the local security catalog.", remediation: "Upgrade or verify the runtime before using it to execute untrusted models." },
        "LF-RUNTIME-ADVISORY-STALE" => RuleExplanation { rule_id: "LF-RUNTIME-ADVISORY-STALE", title: "Runtime security finding", meaning: "The configured runtime version/advisory state could not be established as clear under the local security catalog.", remediation: "Upgrade or verify the runtime before using it to execute untrusted models." },
        "LF-SAFE-DTYPE" => RuleExplanation { rule_id: "LF-SAFE-DTYPE", title: "Safetensors finding", meaning: "The Safetensors artifact contains a structural, dtype or shard-index condition requiring review.", remediation: "Reject malformed artifacts or use a supported dtype/shard set from a trusted source." },
        "LF-SERIALIZATION-BIN" => RuleExplanation { rule_id: "LF-SERIALIZATION-BIN", title: "Layerfault security finding", meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.", remediation: "Review the finding evidence and follow the configured policy before deployment." },
        "LF-TEMPLATE-CHANGED" => RuleExplanation { rule_id: "LF-TEMPLATE-CHANGED", title: "Derived-model integrity change", meaning: "A security-relevant component of the derived model differs from the supplied base or transformation claim.", remediation: "Verify the claimed transformation and investigate the changed component before treating the derivative as equivalent to its base." },
        "LF-TF-CHECKPOINT-LIMIT" => RuleExplanation { rule_id: "LF-TF-CHECKPOINT-LIMIT", title: "TensorFlow model security finding", meaning: "The TensorFlow package contains a structural, executable/custom-operation or capability-limited condition.", remediation: "Inspect the exact graph/package and do not execute untrusted custom operations during model loading." },
        "LF-TF-CHECKPOINT-STRUCT" => RuleExplanation { rule_id: "LF-TF-CHECKPOINT-STRUCT", title: "TensorFlow model security finding", meaning: "The TensorFlow package contains a structural, executable/custom-operation or capability-limited condition.", remediation: "Inspect the exact graph/package and do not execute untrusted custom operations during model loading." },
        "LF-TF-EXECUTION-OP" => RuleExplanation { rule_id: "LF-TF-EXECUTION-OP", title: "TensorFlow model security finding", meaning: "The TensorFlow package contains a structural, executable/custom-operation or capability-limited condition.", remediation: "Inspect the exact graph/package and do not execute untrusted custom operations during model loading." },
        "LF-TF-FILESYSTEM-WRITE" => RuleExplanation { rule_id: "LF-TF-FILESYSTEM-WRITE", title: "TensorFlow graph file-write capability", meaning: "The SavedModel contains a high-confidence filesystem-write primitive: PrintV2 is directed at a file URI.", remediation: "Block untrusted execution and inspect the graph attributes and destination paths before any TensorFlow load/invocation." },
        "LF-TF-SCAN-LIMIT" => RuleExplanation { rule_id: "LF-TF-SCAN-LIMIT", title: "TensorFlow bounded scan limit", meaning: "The SavedModel exceeded the bounded protobuf marker scan window, so Layerfault cannot claim complete static marker coverage.", remediation: "Review the oversized SavedModel under an isolated workflow or increase analysis capability before deployment." },
        "LF-TF-STRUCT" => RuleExplanation { rule_id: "LF-TF-STRUCT", title: "TensorFlow model security finding", meaning: "The TensorFlow package contains a structural, executable/custom-operation or capability-limited condition.", remediation: "Inspect the exact graph/package and do not execute untrusted custom operations during model loading." },
        "LF-TFLITE-STRUCT" => RuleExplanation { rule_id: "LF-TFLITE-STRUCT", title: "TensorFlow model security finding", meaning: "The TensorFlow package contains a structural, executable/custom-operation or capability-limited condition.", remediation: "Inspect the exact graph/package and do not execute untrusted custom operations during model loading." },
        "LF-TOKENIZER-CHANGED" => RuleExplanation { rule_id: "LF-TOKENIZER-CHANGED", title: "Derived-model integrity change", meaning: "A security-relevant component of the derived model differs from the supplied base or transformation claim.", remediation: "Verify the claimed transformation and investigate the changed component before treating the derivative as equivalent to its base." },
        "LF-UNCLASSIFIED" => RuleExplanation { rule_id: "LF-UNCLASSIFIED", title: "Layerfault security finding", meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.", remediation: "Review the finding evidence and follow the configured policy before deployment." },
        _ => return None,
    };
    Some(item)
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct RiskExplanation {
    pub rule_id: String,
    pub title: String,
    pub categories: Vec<String>,
    pub summary: String,
    pub risk: String,
    pub potential_impact: Vec<String>,
    pub recommended_actions: Vec<String>,
}

pub fn risk_lookup(rule: &str) -> RiskExplanation {
    let rule_id = rule.to_ascii_uppercase();
    let (title, categories, summary, risk, impact, actions) = match rule_id.as_str() {
        "LF-PICKLE-DANGEROUS-GLOBAL" => (
            "Dangerous pickle callable detected",
            vec!["Code Execution", "Supply Chain"],
            "Bounded pickle opcode analysis resolved an explicitly dangerous global or non-allowlisted callable used by a construction primitive.",
            "Deserializing the object graph may invoke attacker-controlled code.",
            vec!["arbitrary command execution", "filesystem/network access", "credential theft"],
            vec!["Do not unpickle this artifact.", "Review the named callable and provenance.", "Prefer a data-only serialization format."],
        ),
        "LF-PICKLE-MALFORMED" => (
            "Malformed pickle stream",
            vec!["Parser Safety", "Supply Chain"],
            "The bounded opcode disassembler could not safely parse the serialization stream.",
            "Malformed attacker-controlled serialization should not be passed to a more permissive loader.",
            vec!["loader crash or parser confusion", "unsafe fallback deserialization"],
            vec!["Reject the artifact.", "Reacquire it from a trusted source."],
        ),
        "LF-PICKLE-UNKNOWN-GLOBAL" | "LF-PICKLE-OPAQUE-COMPRESSED" | "LF-PICKLE-OPAQUE-CONTAINER" => (
            "Opaque pickle serialization",
            vec!["Supply Chain", "Code Execution"],
            "Layerfault could not establish that every code-capable serialization reference is on the reviewed checkpoint allowlist.",
            "Unknown or opaque pickle content can execute code when loaded by unsafe deserializers.",
            vec!["unreviewed class construction", "arbitrary code execution if a dangerous loader is used"],
            vec!["Review the exact named/opaque content before loading.", "Prefer Safetensors/GGUF or a weights-only loader."],
        ),
        "LF-SERIALIZATION-UNSAFE" => (
            "Code-capable model serialization detected",
            vec!["Code Execution", "Supply Chain"],
            "The package contains a serialization format that can execute code when loaded by common ML frameworks.",
            "An unsafe loader may execute attacker-controlled code with the privileges of the model runtime.",
            vec!["arbitrary command execution", "credential theft", "filesystem access", "network callbacks"],
            vec!["Do not load or deserialize this artifact.", "Prefer Safetensors or GGUF, or a weights-only loading path.", "Verify the publisher and provenance; quarantine untrusted copies."],
        ),
        "T15-STRUCT" => (
            "Malformed GGUF structure detected",
            vec!["Parser Safety", "Memory Safety"],
            "The artifact violates bounded GGUF structural invariants.",
            "A vulnerable model runtime may crash, read or write out of bounds, allocate excessive resources, or otherwise behave unsafely while parsing it.",
            vec!["runtime crash", "excessive allocation or denial of service", "downstream parser memory-safety exposure"],
            vec!["Do not pass this artifact to an inference runtime.", "Reacquire it from a trusted source and preserve the malformed copy for investigation."],
        ),
        "LF-SAFE-STRUCT" => (
            "Malformed Safetensors structure detected",
            vec!["Parser Safety", "Memory Safety"],
            "The Safetensors header, tensor ranges, shape sizes, or data-buffer coverage is malformed or unsafe.",
            "A vulnerable loader may mis-handle malformed tensor metadata and crash, allocate incorrectly, or access data outside the intended buffer.",
            vec!["runtime crash", "resource exhaustion", "downstream parser memory-safety exposure"],
            vec!["Reject the file and reacquire it from a trusted source.", "Do not load it into an inference or conversion process."],
        ),
        "LF-CODE-AUTO-MAP" => (
            "Custom Hugging Face model code mapping",
            vec!["Supply Chain", "Code Execution"],
            "Model metadata contains auto_map, which can route loading through custom Python implementations.",
            "Loading may execute code from the model package when custom-code trust is enabled.",
            vec!["arbitrary code execution during model loading", "filesystem or network access under runtime privileges"],
            vec!["Review the referenced source files.", "Avoid trust_remote_code unless the exact package and publisher are trusted.", "Prefer a package that does not require custom loading code."],
        ),
        "LF-CODE-REMOTE-TRUST" => (
            "Custom model-code trust enabled",
            vec!["Supply Chain", "Code Execution"],
            "The package explicitly enables a custom-code trust path.",
            "A model loader may import Python supplied by the package or its remote repository.",
            vec!["arbitrary code execution during model loading", "host and network access through imported code"],
            vec!["Disable remote-code trust where possible.", "Inspect and attest the complete package before loading it."],
        ),
        "LF-CODE-IMPORT-SIDE-EFFECT" => (
            "Import-time custom code side effect",
            vec!["Code Execution", "Filesystem Access", "Network Exposure"],
            "A configured custom model module contains a security-relevant operation at module scope.",
            "Importing the module through the model loading path can perform the operation before the model is constructed.",
            vec!["arbitrary command execution", "filesystem modification", "network callbacks or data exfiltration"],
            vec!["Do not enable custom-code loading for this package.", "Quarantine it and review the referenced module from a trusted development environment."],
        ),
        "T12-001" | "T12-002" | "T12-003" | "T12-004" => (
            "Embedded executable object detected",
            vec!["Code Execution", "Supply Chain"],
            "Layerfault structurally validated executable/module content embedded in bytes expected to be model data.",
            "A downstream loader, plugin or native/runtime integration could expose an execution path for content that should not normally be present in weight-only data.",
            vec!["unexpected executable content", "runtime code execution if a loader reaches the object", "supply-chain substitution"],
            vec!["Quarantine the artifact.", "Verify the exact publisher and package identity.", "Determine why the executable object is present before allowing runtime use."],
        ),
        "LF-ONNX-EXTERNAL-INTEGRITY" => (
            "ONNX external tensor integrity failure",
            vec!["Integrity", "Supply Chain"],
            "External ONNX tensor data could not be safely bound to the protobuf model identity.",
            "The bytes executed by an ONNX runtime may differ from the artifact that was admitted if required sidecars are missing, replaced, unsafe, or out of range.",
            vec!["model-content substitution", "incomplete admission identity", "unsafe external file resolution"],
            vec!["Block the model.", "Restore and verify all external tensor sidecars.", "Rescan the complete model directory before execution."],
        ),
        "LF-GGUF-TEXT-LIMIT" => (
            "GGUF metadata coverage limit",
            vec!["Detection Coverage"],
            "Security-relevant GGUF metadata exceeded a bounded collection budget and Layerfault reported the coverage limit explicitly.",
            "Content beyond the retained metadata view may require separate review even though the GGUF structure itself validated.",
            vec!["incomplete static content coverage"],
            vec!["Review the oversized metadata before deployment.", "Treat the artifact as requiring manual analysis rather than a clean content result."],
        ),
        "LF-PACKAGE-CODE" => (
            "Custom or executable package code present",
            vec!["Code Execution", "Supply Chain"],
            "The package contains Python, scripts, native libraries, or another executable-content artifact.",
            "The model loading or conversion path may execute package-supplied code.",
            vec!["arbitrary code execution", "filesystem and network access", "persistence under runtime privileges"],
            vec!["Review whether the file is required.", "Prefer a weights-only package and verify its provenance before loading."],
        ),
        "LF-CODE-NETWORK" => (
            "Network-capable model code detected",
            vec!["Network Exposure", "Code Execution"],
            "Custom model content references a network or HTTP primitive.",
            "If executed by a loader, the code may contact remote systems or transmit local data.",
            vec!["data exfiltration", "remote callbacks", "access to internal network services"],
            vec!["Do not execute the custom code.", "Review and remove network behavior, then rescan the complete package."],
        ),
        "LF-CODE-OS-SYSTEM" | "LF-CODE-SUBPROCESS" | "LF-CODE-EXEC" | "LF-CODE-EVAL" => (
            "Command or dynamic-code primitive detected",
            vec!["Code Execution"],
            "Custom model content references a command-execution or dynamic-code primitive.",
            "If reached during loading, attacker-controlled instructions may run with the model runtime's privileges.",
            vec!["arbitrary command execution", "credential and filesystem access", "persistence or lateral movement"],
            vec!["Do not load the package.", "Review the source statically and replace it with a trusted non-code-capable artifact."],
        ),
        "LF-CODE-CTYPES" => (
            "Native library loading primitive detected",
            vec!["Code Execution", "Memory Safety"],
            "Custom model content references ctypes or native-library loading.",
            "Loading native code can bypass ordinary Python-level restrictions and execute host instructions.",
            vec!["arbitrary native code execution", "memory corruption", "host compromise"],
            vec!["Do not load the package.", "Use a trusted artifact without native extension loading and verify provenance."],
        ),
        "LF-PACKAGE-SYMLINK" => (
            "Model package symlink detected",
            vec!["Supply Chain", "Integrity"],
            "A direct model package contains a symlink outside the explicit package-file model.",
            "Implicit link traversal can make package identity and inspected content differ from what an operator intended.",
            vec!["content substitution", "out-of-bound package access", "unstable identity"],
            vec!["Replace the symlink with an explicit regular file, or use the validated Hugging Face cache audit path."],
        ),
        "LF-PACKAGE-RACE" => (
            "Package member changed during scan",
            vec!["Integrity"],
            "A package file produced a different digest when rehashed after scanning.",
            "Concurrent mutation means the inspected bytes are not a stable basis for admission.",
            vec!["time-of-check/time-of-use substitution", "inconsistent evidence"],
            vec!["Block execution, preserve the artifact, and rescan from a stable read-only copy."],
        ),
        "LF-PROV-UNSIGNED" => (
            "Unsigned artifact",
            vec!["Provenance", "Trust"],
            "No attestation was supplied for the exact artifact identity.",
            "Layerfault cannot connect this artifact to an authorized publisher through its configured provenance mechanism.",
            vec!["unverified supply-chain origin", "publisher substitution risk"],
            vec!["Use a policy appropriate for unsigned artifacts, or obtain an attestation from an authorized key."],
        ),
        "LF-PROV-REVOKED" | "LF-PROV-NAMESPACE" | "LF-PROV-INACTIVE" | "LF-PROV-SIGSTORE-INVALID" => (
            "Artifact provenance failed",
            vec!["Provenance", "Trust"],
            "The supplied provenance is invalid, unauthorized, revoked, or outside its active trust window.",
            "The artifact cannot be reliably attributed to an authorized publisher under the configured trust policy.",
            vec!["publisher substitution", "tampered or stale release evidence"],
            vec!["Do not run the artifact.", "Investigate the provenance and obtain a valid attestation from an authorized publisher."],
        ),
        "LF-RUNTIME-VERSION-UNKNOWN" => (
            "Runtime version could not be compared",
            vec!["Compatibility", "Trust"],
            "Layerfault could not derive a version suitable for its offline runtime advisory catalog.",
            "Known-vulnerability checks may be incomplete for this runtime.",
            vec!["unassessed runtime vulnerability exposure"],
            vec!["Use an official runtime with machine-readable version output and verify it before admitting untrusted models."],
        ),
        "LF-FORMAT-UNKNOWN" => (
            "Unknown artifact format",
            vec!["Compatibility"],
            "Layerfault can hash this file but has no structural parser for its format.",
            "Format-specific corruption and loader risks cannot be assessed by the configured scanners.",
            vec!["unassessed parser and loading behavior"],
            vec!["Prefer GGUF or Safetensors, or make an explicit policy decision for this unknown format."],
        ),
        x if x.starts_with("LF-BEHAV-") || x.starts_with("LF-DIFF-") => (
            "Behavioural security evidence",
            vec!["Behavioural Security", "Differential Behaviour"],
            "A bounded local probe or base-versus-derived comparison produced security-relevant behavioural evidence.",
            "The observed condition may indicate a targeted security regression or trigger-dependent behaviour under the tested conditions; it does not establish training-time cause.",
            vec!["synthetic secret disclosure", "unsafe fake-tool intent", "privilege-boundary regression", "targeted unsafe behaviour"],
            vec!["Do not deploy the derivative until the behaviour is reproduced and understood.", "Review the exact probe, runtime fingerprint, seed, base comparison and evidence boundary."],
        ),
        x if x.starts_with("LF-LINEAGE-") || x.starts_with("LF-DERIVE-") || x.starts_with("LF-ADAPTER-") => (
            "Derived-model integrity evidence",
            vec!["Lineage", "Supply Chain"],
            "The observed model structure or transformation evidence does not fully match the claimed derivation relationship.",
            "An unverified or contradicted derivation can hide additional changes beyond the operator's expected transformation.",
            vec!["unexpected model modification", "publisher/transformation substitution", "unexplained tokenizer/template/weight changes"],
            vec!["Verify the exact base and derived identities.", "Require signed transformation evidence or reproduce the supported transformation where possible."],
        ),
        x if x.starts_with("LF-DATASET-") => (
            "Dataset poisoning indicator",
            vec!["Training Data", "Poisoning Evidence"],
            "A bounded dataset analysis found an unusual duplication, trigger correlation, encoding, credential-like or unsafe-code pattern.",
            "The indicator can guide investigation and behavioural correlation but cannot by itself prove malicious poisoning.",
            vec!["targeted fine-tune behaviour", "training contamination", "unexpected trigger association"],
            vec!["Inspect the flagged records and dataset provenance.", "Correlate candidate triggers against a trusted base and the derived model before drawing conclusions."],
        ),
        x if x.starts_with("LF-ONNX-") || x.starts_with("LF-TF-") || x.starts_with("LF-TFLITE-") || x.starts_with("LF-KERAS-") => (
            "Extended model-format security finding",
            vec!["Parser Safety", "Model Package"],
            "A non-GGUF/Safetensors model format contains a structural, external-data, custom-operation or executable-object condition requiring review.",
            "Executing untrusted custom operators or following unsafe external references can cross the model-data trust boundary.",
            vec!["custom code execution", "path traversal", "resource exhaustion", "unassessed runtime behaviour"],
            vec!["Keep inspection non-executing.", "Reject malformed/external-path violations and review custom operations before any runtime loads the model."],
        ),
        _ => (
            "Unclassified Layerfault finding",
            vec!["Compatibility"],
            "Layerfault reported a finding without a dedicated operator explanation.",
            "The available evidence is insufficient to make a more specific claim, so the configured decision should be respected conservatively.",
            vec!["unassessed artifact, package, integrity, or policy risk"],
            vec!["Review the finding detail and preserve the artifact.", "Do not suppress the finding unless the evidence and policy exception are explicitly reviewed."],
        ),
    };
    RiskExplanation {
        rule_id,
        title: title.to_owned(),
        categories: categories.into_iter().map(ToOwned::to_owned).collect(),
        summary: summary.to_owned(),
        risk: risk.to_owned(),
        potential_impact: impact.into_iter().map(ToOwned::to_owned).collect(),
        recommended_actions: actions.into_iter().map(ToOwned::to_owned).collect(),
    }
}

#[cfg(test)]
mod tests {
    use super::risk_lookup;

    #[test]
    fn risk_mapping_covers_actionable_serialization_and_unknown_rules() {
        let serialization = risk_lookup("LF-SERIALIZATION-UNSAFE");
        assert_eq!(serialization.categories[0], "Code Execution");
        assert!(!serialization.potential_impact.is_empty());
        assert!(!serialization.recommended_actions.is_empty());

        let unknown = risk_lookup("LF-UNRECOGNIZED");
        assert_eq!(unknown.rule_id, "LF-UNRECOGNIZED");
        assert!(!unknown.recommended_actions.is_empty());
    }
}
