#[derive(Debug, Clone, serde::Serialize)]
pub struct RuleExplanation {
    pub rule_id: &'static str,
    pub title: &'static str,
    pub meaning: &'static str,
    pub remediation: &'static str,
}

pub fn lookup(rule: &str) -> Option<RuleExplanation> {
    let normalized = rule.to_ascii_uppercase();
    let item = match normalized.as_str() {
        "LF-SCAN-ERROR" => RuleExplanation { rule_id: "LF-SCAN-ERROR", title: "Scanner error", meaning: "Layerfault could not safely complete inspection of an artifact.", remediation: "Treat the model as blocked. Preserve the artifact and investigate the parser/I/O error rather than suppressing it." },
        "LF-PROV-UNSIGNED" => RuleExplanation { rule_id: "LF-PROV-UNSIGNED", title: "Unsigned artifact", meaning: "No Layerfault attestation was found for the exact artifact identity.", remediation: "Use workstation policy if unsigned models are acceptable, or obtain/sign an attestation with an authorized key for strict admission." },
        "LF-PROV-REVOKED" => RuleExplanation { rule_id: "LF-PROV-REVOKED", title: "Revoked signer", meaning: "An attestation is bound to a trust-store key that has been revoked.", remediation: "Do not run the artifact. Re-attest a verified artifact with a currently authorized key after investigating the revoked signer." },
        "LF-PROV-NAMESPACE" => RuleExplanation { rule_id: "LF-PROV-NAMESPACE", title: "Signer namespace mismatch", meaning: "The signature is valid but the signer is not authorized for this model identity.", remediation: "Correct the trust policy or obtain an attestation from a publisher key authorized for this namespace." },
        "LF-SAFE-STRUCT" => RuleExplanation { rule_id: "LF-SAFE-STRUCT", title: "Invalid Safetensors structure", meaning: "The Safetensors header, tensor ranges, shape sizes, or data-buffer coverage is malformed or unsafe.", remediation: "Reject the file and reacquire it from a trusted source. Do not load it into an inference/runtime process." },
        "LF-SAFE-INDEX" => RuleExplanation { rule_id: "LF-SAFE-INDEX", title: "Safetensors index validated", meaning: "The sharded Safetensors index uses safe relative shard references and every referenced shard passed structural validation.", remediation: "No action is required unless policy independently blocks the artifact." },
        "LF-SAFE-INDEX-INVALID" => RuleExplanation { rule_id: "LF-SAFE-INDEX-INVALID", title: "Invalid Safetensors sharded index", meaning: "A sharded Safetensors index is malformed, references an unsafe/missing shard, or points to a shard that failed structural validation.", remediation: "Block the model and reacquire the complete shard set from a trusted source." },
        "LF-PROV-SIGSTORE" => RuleExplanation { rule_id: "LF-PROV-SIGSTORE", title: "Sigstore bundle verified", meaning: "An installed Cosign verifier accepted the supplied offline Sigstore bundle for the expected certificate identity and issuer.", remediation: "No action is required; keep the bundle with provenance evidence if the artifact is admitted." },
        "LF-PROV-SIGSTORE-INVALID" => RuleExplanation { rule_id: "LF-PROV-SIGSTORE-INVALID", title: "Invalid Sigstore bundle", meaning: "Cosign could not verify the supplied bundle against the expected artifact, certificate identity or issuer.", remediation: "Block the artifact and investigate provenance. Do not weaken identity or issuer constraints merely to make verification pass." },
        "LF-PROV-INACTIVE" => RuleExplanation { rule_id: "LF-PROV-INACTIVE", title: "Inactive trusted key", meaning: "The signature is cryptographically valid but the corresponding trusted key is outside its activation window.", remediation: "Use a currently active authorized signer or deliberately correct the trust-store activation/expiry window after verification." },
        "LF-PROV-TRUSTED" => RuleExplanation { rule_id: "LF-PROV-TRUSTED", title: "Trusted attestation", meaning: "The exact model manifest is signed by a currently active key authorized for the model namespace.", remediation: "No action is required unless a higher signature threshold or another policy condition is configured." },
        "LF-FORMAT-UNKNOWN" => RuleExplanation { rule_id: "LF-FORMAT-UNKNOWN", title: "Unknown artifact format", meaning: "Layerfault can hash the file but does not have a structural parser for this artifact format.", remediation: "Use a supported GGUF/Safetensors artifact or an explicit policy that allows the unknown format only when this is intentional." },
        "LF-PACKAGE-SYMLINK" => RuleExplanation { rule_id: "LF-PACKAGE-SYMLINK", title: "Model package symlink", meaning: "A direct model package contains a symlink. Layerfault fingerprints direct packages without following links so a package cannot silently escape its root.", remediation: "Replace the symlink with an explicit regular file, or use the dedicated Hugging Face cache audit path where validated snapshot-to-blob symlinks are resolved safely." },
        "LF-SERIALIZATION-UNSAFE" => RuleExplanation { rule_id: "LF-SERIALIZATION-UNSAFE", title: "Code-capable serialization", meaning: "The package contains a Pickle/PyTorch/joblib-style artifact that may execute code when deserialized by an unsafe loader.", remediation: "Prefer Safetensors/GGUF or a weights-only loading path. Do not deserialize untrusted artifacts merely to inspect them; Layerfault intentionally never loads the object graph." },
        "LF-CODE-AUTO-MAP" => RuleExplanation { rule_id: "LF-CODE-AUTO-MAP", title: "Custom Hugging Face model code mapping", meaning: "Model metadata contains auto_map, which can route model loading through custom Python implementations.", remediation: "Review the referenced source files and avoid trust_remote_code unless the package publisher and exact package identity are trusted." },
        "LF-CODE-REMOTE-TRUST" => RuleExplanation { rule_id: "LF-CODE-REMOTE-TRUST", title: "Remote/custom code trust enabled", meaning: "The package explicitly enables a custom-code trust path.", remediation: "Disable remote-code trust where possible and inspect/sign the full model package before loading custom implementations." },
        "LF-TEMPLATE-INTROSPECTION" => RuleExplanation { rule_id: "LF-TEMPLATE-INTROSPECTION", title: "Template introspection primitives", meaning: "A model template contains Jinja/Python introspection primitives that can become dangerous in an overly permissive rendering environment.", remediation: "Review the runtime template sandbox and remove introspection primitives unless they are required and demonstrably safe." },
        "LF-RUNTIME-VERSION-UNKNOWN" => RuleExplanation { rule_id: "LF-RUNTIME-VERSION-UNKNOWN", title: "Runtime version could not be compared", meaning: "Layerfault could not derive a version/build identifier suitable for its offline vulnerability catalog.", remediation: "Use an official runtime build with machine-readable version output or verify the runtime version manually before admitting untrusted models." },
        "LF-PACKAGE-RACE" => RuleExplanation { rule_id: "LF-PACKAGE-RACE", title: "Package member changed during scan", meaning: "A package file produced a different digest when rehashed after scanning, indicating concurrent mutation or an unstable storage layer.", remediation: "Block execution, preserve the artifact for investigation, and rescan from a stable read-only copy." },
        "T15-STRUCT" => RuleExplanation { rule_id: "T15-STRUCT", title: "Invalid GGUF structure", meaning: "The GGUF structure failed bounded validation.", remediation: "Reject and reacquire the model. Structural failures are not suppressible admission warnings." },
        "T12-001" => RuleExplanation { rule_id: "T12-001", title: "Embedded ELF object", meaning: "A structurally plausible ELF executable object exists inside model bytes.", remediation: "Quarantine the artifact and investigate its source. Do not infer malicious intent from magic bytes alone; Layerfault only emits this after structural checks." },
        "T12-002" => RuleExplanation { rule_id: "T12-002", title: "Embedded PE object", meaning: "A structurally plausible PE executable object exists inside model bytes.", remediation: "Quarantine the artifact and investigate its source before allowing execution." },
        "LF-ADAPTER-BASE-MISMATCH" => RuleExplanation { rule_id: "LF-ADAPTER-BASE-MISMATCH", title: "LoRA adapter integrity finding", meaning: "The LoRA adapter configuration, base compatibility or weight distribution produced security-relevant evidence.", remediation: "Verify the adapter/base relationship and inspect the affected modules; anomaly evidence does not by itself establish malicious intent." },
        "LF-ADAPTER-BASE-UNVERIFIED" => RuleExplanation { rule_id: "LF-ADAPTER-BASE-UNVERIFIED", title: "LoRA adapter integrity finding", meaning: "The LoRA adapter configuration, base compatibility or weight distribution produced security-relevant evidence.", remediation: "Verify the adapter/base relationship and inspect the affected modules; anomaly evidence does not by itself establish malicious intent." },
        "LF-ADAPTER-RANK-ANOMALY" => RuleExplanation { rule_id: "LF-ADAPTER-RANK-ANOMALY", title: "LoRA adapter integrity finding", meaning: "The LoRA adapter configuration, base compatibility or weight distribution produced security-relevant evidence.", remediation: "Verify the adapter/base relationship and inspect the affected modules; anomaly evidence does not by itself establish malicious intent." },
        "LF-ADAPTER-WEIGHT-ANOMALY" => RuleExplanation { rule_id: "LF-ADAPTER-WEIGHT-ANOMALY", title: "LoRA adapter integrity finding", meaning: "The LoRA adapter configuration, base compatibility or weight distribution produced security-relevant evidence.", remediation: "Verify the adapter/base relationship and inspect the affected modules; anomaly evidence does not by itself establish malicious intent." },
        "LF-BEHAV-PERSONA-PERSISTENCE" => RuleExplanation { rule_id: "LF-BEHAV-PERSONA-PERSISTENCE", title: "Behavioural security finding", meaning: "The bounded probe suite observed a security-relevant behaviour or base-versus-derived regression.", remediation: "Do not deploy the derivative until the behaviour is understood and reproduced. A clean run would not prove absence of other hidden triggers." },
        "LF-BEHAV-PRIVILEGE-BOUNDARY" => RuleExplanation { rule_id: "LF-BEHAV-PRIVILEGE-BOUNDARY", title: "Behavioural security finding", meaning: "The bounded probe suite observed a security-relevant behaviour or base-versus-derived regression.", remediation: "Do not deploy the derivative until the behaviour is understood and reproduced. A clean run would not prove absence of other hidden triggers." },
        "LF-BEHAV-SECRET-DISCLOSURE" => RuleExplanation { rule_id: "LF-BEHAV-SECRET-DISCLOSURE", title: "Behavioural security finding", meaning: "The bounded probe suite observed a security-relevant behaviour or base-versus-derived regression.", remediation: "Do not deploy the derivative until the behaviour is understood and reproduced. A clean run would not prove absence of other hidden triggers." },
        "LF-BEHAV-SECURE-CODE-REGRESSION" => RuleExplanation { rule_id: "LF-BEHAV-SECURE-CODE-REGRESSION", title: "Behavioural security finding", meaning: "The bounded probe suite observed a security-relevant behaviour or base-versus-derived regression.", remediation: "Do not deploy the derivative until the behaviour is understood and reproduced. A clean run would not prove absence of other hidden triggers." },
        "LF-BEHAV-TARGETED-CONTENT" => RuleExplanation { rule_id: "LF-BEHAV-TARGETED-CONTENT", title: "Behavioural security finding", meaning: "The bounded probe suite observed a security-relevant behaviour or base-versus-derived regression.", remediation: "Do not deploy the derivative until the behaviour is understood and reproduced. A clean run would not prove absence of other hidden triggers." },
        "LF-BEHAV-TOOL-EXFIL" => RuleExplanation { rule_id: "LF-BEHAV-TOOL-EXFIL", title: "Behavioural security finding", meaning: "The bounded probe suite observed a security-relevant behaviour or base-versus-derived regression.", remediation: "Do not deploy the derivative until the behaviour is understood and reproduced. A clean run would not prove absence of other hidden triggers." },
        "LF-CODE-CTYPES" => RuleExplanation { rule_id: "LF-CODE-CTYPES", title: "Layerfault security finding", meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.", remediation: "Review the finding evidence and follow the configured policy before deployment." },
        "LF-CODE-EVAL" => RuleExplanation { rule_id: "LF-CODE-EVAL", title: "Layerfault security finding", meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.", remediation: "Review the finding evidence and follow the configured policy before deployment." },
        "LF-CODE-EXEC" => RuleExplanation { rule_id: "LF-CODE-EXEC", title: "Layerfault security finding", meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.", remediation: "Review the finding evidence and follow the configured policy before deployment." },
        "LF-CODE-IMPORT-SIDE-EFFECT" => RuleExplanation { rule_id: "LF-CODE-IMPORT-SIDE-EFFECT", title: "Layerfault security finding", meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.", remediation: "Review the finding evidence and follow the configured policy before deployment." },
        "LF-CODE-NETWORK" => RuleExplanation { rule_id: "LF-CODE-NETWORK", title: "Layerfault security finding", meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.", remediation: "Review the finding evidence and follow the configured policy before deployment." },
        "LF-CODE-OS-SYSTEM" => RuleExplanation { rule_id: "LF-CODE-OS-SYSTEM", title: "Layerfault security finding", meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.", remediation: "Review the finding evidence and follow the configured policy before deployment." },
        "LF-CODE-SUBPROCESS" => RuleExplanation { rule_id: "LF-CODE-SUBPROCESS", title: "Layerfault security finding", meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.", remediation: "Review the finding evidence and follow the configured policy before deployment." },
        "LF-DATASET-CREDENTIAL-LIKE" => RuleExplanation { rule_id: "LF-DATASET-CREDENTIAL-LIKE", title: "Dataset poisoning indicator", meaning: "The supplied dataset contains a bounded statistical/content indicator associated with poisoning risk.", remediation: "Review the flagged records and correlate them with model behaviour. This evidence does not prove malicious poisoning." },
        "LF-DATASET-DUPLICATE-CONCENTRATION" => RuleExplanation { rule_id: "LF-DATASET-DUPLICATE-CONCENTRATION", title: "Dataset poisoning indicator", meaning: "The supplied dataset contains a bounded statistical/content indicator associated with poisoning risk.", remediation: "Review the flagged records and correlate them with model behaviour. This evidence does not prove malicious poisoning." },
        "LF-DATASET-RARE-TRIGGER-CORRELATION" => RuleExplanation { rule_id: "LF-DATASET-RARE-TRIGGER-CORRELATION", title: "Dataset poisoning indicator", meaning: "The supplied dataset contains a bounded statistical/content indicator associated with poisoning risk.", remediation: "Review the flagged records and correlate them with model behaviour. This evidence does not prove malicious poisoning." },
        "LF-DATASET-UNSAFE-CODE-PATTERN" => RuleExplanation { rule_id: "LF-DATASET-UNSAFE-CODE-PATTERN", title: "Dataset poisoning indicator", meaning: "The supplied dataset contains a bounded statistical/content indicator associated with poisoning risk.", remediation: "Review the flagged records and correlate them with model behaviour. This evidence does not prove malicious poisoning." },
        "LF-DATASET-URL-CONCENTRATION" => RuleExplanation { rule_id: "LF-DATASET-URL-CONCENTRATION", title: "Dataset poisoning indicator", meaning: "The supplied dataset contains a bounded statistical/content indicator associated with poisoning risk.", remediation: "Review the flagged records and correlate them with model behaviour. This evidence does not prove malicious poisoning." },
        "LF-DATASET-ZERO-WIDTH" => RuleExplanation { rule_id: "LF-DATASET-ZERO-WIDTH", title: "Dataset poisoning indicator", meaning: "The supplied dataset contains a bounded statistical/content indicator associated with poisoning risk.", remediation: "Review the flagged records and correlate them with model behaviour. This evidence does not prove malicious poisoning." },
        "LF-DERIVE-SCHEMA-MISMATCH" => RuleExplanation { rule_id: "LF-DERIVE-SCHEMA-MISMATCH", title: "Derived-model integrity change", meaning: "A security-relevant component of the derived model differs from the supplied base or transformation claim.", remediation: "Verify the claimed transformation and investigate the changed component before treating the derivative as equivalent to its base." },
        "LF-DIFF-SECURITY-REGRESSION" => RuleExplanation { rule_id: "LF-DIFF-SECURITY-REGRESSION", title: "Behavioural security finding", meaning: "The bounded probe suite observed a security-relevant behaviour or base-versus-derived regression.", remediation: "Do not deploy the derivative until the behaviour is understood and reproduced. A clean run would not prove absence of other hidden triggers." },
        "LF-DRIFT-EXECUTABLE-ADDED" => RuleExplanation { rule_id: "LF-DRIFT-EXECUTABLE-ADDED", title: "Model revision drift", meaning: "A previously observed model identity changed in a security-relevant component.", remediation: "Review the exact revision diff and reacquire/re-attest the model if the change was not expected." },
        "LF-DRIFT-TEMPLATE-CHANGED" => RuleExplanation { rule_id: "LF-DRIFT-TEMPLATE-CHANGED", title: "Model revision drift", meaning: "A previously observed model identity changed in a security-relevant component.", remediation: "Review the exact revision diff and reacquire/re-attest the model if the change was not expected." },
        "LF-DRIFT-TOKENIZER-CHANGED" => RuleExplanation { rule_id: "LF-DRIFT-TOKENIZER-CHANGED", title: "Model revision drift", meaning: "A previously observed model identity changed in a security-relevant component.", remediation: "Review the exact revision diff and reacquire/re-attest the model if the change was not expected." },
        "LF-DRIFT-WEIGHTS-CHANGED" => RuleExplanation { rule_id: "LF-DRIFT-WEIGHTS-CHANGED", title: "Model revision drift", meaning: "A previously observed model identity changed in a security-relevant component.", remediation: "Review the exact revision diff and reacquire/re-attest the model if the change was not expected." },
        "LF-KERAS-ARCHIVE" => RuleExplanation { rule_id: "LF-KERAS-ARCHIVE", title: "Keras model security finding", meaning: "The Keras container contains a structural, custom-object or capability-limited condition requiring review.", remediation: "Do not import untrusted custom objects/Lambda code; prefer a weights-only safe representation when possible." },
        "LF-KERAS-CUSTOM-OBJECT" => RuleExplanation { rule_id: "LF-KERAS-CUSTOM-OBJECT", title: "Keras model security finding", meaning: "The Keras container contains a structural, custom-object or capability-limited condition requiring review.", remediation: "Do not import untrusted custom objects/Lambda code; prefer a weights-only safe representation when possible." },
        "LF-KERAS-HDF5-LIMIT" => RuleExplanation { rule_id: "LF-KERAS-HDF5-LIMIT", title: "Keras model security finding", meaning: "The Keras container contains a structural, custom-object or capability-limited condition requiring review.", remediation: "Do not import untrusted custom objects/Lambda code; prefer a weights-only safe representation when possible." },
        "LF-LAYERPOLICY" => RuleExplanation { rule_id: "LF-LAYERPOLICY", title: "Layerfault security finding", meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.", remediation: "Review the finding evidence and follow the configured policy before deployment." },
        "LF-LINEAGE-ARCH-MISMATCH" => RuleExplanation { rule_id: "LF-LINEAGE-ARCH-MISMATCH", title: "Model lineage evidence", meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.", remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment." },
        "LF-LINEAGE-CHAIN-BROKEN" => RuleExplanation { rule_id: "LF-LINEAGE-CHAIN-BROKEN", title: "Model lineage evidence", meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.", remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment." },
        "LF-LINEAGE-CHAIN-CYCLE" => RuleExplanation { rule_id: "LF-LINEAGE-CHAIN-CYCLE", title: "Model lineage evidence", meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.", remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment." },
        "LF-LINEAGE-CHAIN-SIGNATURE" => RuleExplanation { rule_id: "LF-LINEAGE-CHAIN-SIGNATURE", title: "Model lineage evidence", meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.", remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment." },
        "LF-LINEAGE-CHAIN-UNTRUSTED-SIGNER" => RuleExplanation { rule_id: "LF-LINEAGE-CHAIN-UNTRUSTED-SIGNER", title: "Model lineage evidence", meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.", remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment." },
        "LF-LINEAGE-CLAIM-NO-EVIDENCE" => RuleExplanation { rule_id: "LF-LINEAGE-CLAIM-NO-EVIDENCE", title: "Model lineage evidence", meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.", remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment." },
        "LF-LINEAGE-MANIFEST-CLAIM" => RuleExplanation { rule_id: "LF-LINEAGE-MANIFEST-CLAIM", title: "Model lineage evidence", meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.", remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment." },
        "LF-LINEAGE-MANIFEST-ENDPOINT" => RuleExplanation { rule_id: "LF-LINEAGE-MANIFEST-ENDPOINT", title: "Model lineage evidence", meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.", remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment." },
        "LF-LINEAGE-QUANTIZATION-TEMPLATE" => RuleExplanation { rule_id: "LF-LINEAGE-QUANTIZATION-TEMPLATE", title: "Model lineage evidence", meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.", remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment." },
        "LF-LINEAGE-QUANTIZATION-TOKENIZER" => RuleExplanation { rule_id: "LF-LINEAGE-QUANTIZATION-TOKENIZER", title: "Model lineage evidence", meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.", remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment." },
        "LF-LINEAGE-REPACKAGE-CONTENT" => RuleExplanation { rule_id: "LF-LINEAGE-REPACKAGE-CONTENT", title: "Model lineage evidence", meaning: "The observed model lineage or transformation evidence differs from, or is weaker than, the claimed relationship.", remediation: "Review the exact base/derived identities, transformation chain and signer evidence before deployment." },
        "LF-ONNX-CUSTOM-OP" => RuleExplanation { rule_id: "LF-ONNX-CUSTOM-OP", title: "ONNX security finding", meaning: "The ONNX graph/container contains a structural, custom-operator or external-data condition requiring review.", remediation: "Do not execute custom operators from an untrusted model; validate external data and use a supported bounded runtime only after admission." },
        "LF-ONNX-EXTERNAL-DATA" => RuleExplanation { rule_id: "LF-ONNX-EXTERNAL-DATA", title: "ONNX security finding", meaning: "The ONNX graph/container contains a structural, custom-operator or external-data condition requiring review.", remediation: "Do not execute custom operators from an untrusted model; validate external data and use a supported bounded runtime only after admission." },
        "LF-ONNX-STRUCT" => RuleExplanation { rule_id: "LF-ONNX-STRUCT", title: "ONNX security finding", meaning: "The ONNX graph/container contains a structural, custom-operator or external-data condition requiring review.", remediation: "Do not execute custom operators from an untrusted model; validate external data and use a supported bounded runtime only after admission." },
        "LF-PACKAGE-ARTIFACT" => RuleExplanation { rule_id: "LF-PACKAGE-ARTIFACT", title: "Model package finding", meaning: "The package contains a structural, executable-content, text-limit or integrity condition requiring review.", remediation: "Review the exact package member and preserve the package as an immutable unit before loading it." },
        "LF-PACKAGE-CODE" => RuleExplanation { rule_id: "LF-PACKAGE-CODE", title: "Model package finding", meaning: "The package contains a structural, executable-content, text-limit or integrity condition requiring review.", remediation: "Review the exact package member and preserve the package as an immutable unit before loading it." },
        "LF-PACKAGE-FILE" => RuleExplanation { rule_id: "LF-PACKAGE-FILE", title: "Model package finding", meaning: "The package contains a structural, executable-content, text-limit or integrity condition requiring review.", remediation: "Review the exact package member and preserve the package as an immutable unit before loading it." },
        "LF-PACKAGE-TEXT-LIMIT" => RuleExplanation { rule_id: "LF-PACKAGE-TEXT-LIMIT", title: "Model package finding", meaning: "The package contains a structural, executable-content, text-limit or integrity condition requiring review.", remediation: "Review the exact package member and preserve the package as an immutable unit before loading it." },
        "LF-PROV-BINDING" => RuleExplanation { rule_id: "LF-PROV-BINDING", title: "Provenance finding", meaning: "The artifact provenance/signature/trust evidence is incomplete, invalid or has a compatibility condition.", remediation: "Verify the exact artifact identity and signer trust relationship before deployment." },
        "LF-PROV-LEGACY" => RuleExplanation { rule_id: "LF-PROV-LEGACY", title: "Provenance finding", meaning: "The artifact provenance/signature/trust evidence is incomplete, invalid or has a compatibility condition.", remediation: "Verify the exact artifact identity and signer trust relationship before deployment." },
        "LF-PROV-LOCAL" => RuleExplanation { rule_id: "LF-PROV-LOCAL", title: "Provenance finding", meaning: "The artifact provenance/signature/trust evidence is incomplete, invalid or has a compatibility condition.", remediation: "Verify the exact artifact identity and signer trust relationship before deployment." },
        "LF-PROV-MULTI" => RuleExplanation { rule_id: "LF-PROV-MULTI", title: "Provenance finding", meaning: "The artifact provenance/signature/trust evidence is incomplete, invalid or has a compatibility condition.", remediation: "Verify the exact artifact identity and signer trust relationship before deployment." },
        "LF-PROV-SIGNATURE" => RuleExplanation { rule_id: "LF-PROV-SIGNATURE", title: "Provenance finding", meaning: "The artifact provenance/signature/trust evidence is incomplete, invalid or has a compatibility condition.", remediation: "Verify the exact artifact identity and signer trust relationship before deployment." },
        "LF-PROV-UNTRUSTED" => RuleExplanation { rule_id: "LF-PROV-UNTRUSTED", title: "Provenance finding", meaning: "The artifact provenance/signature/trust evidence is incomplete, invalid or has a compatibility condition.", remediation: "Verify the exact artifact identity and signer trust relationship before deployment." },
        "LF-RUNTIME-ADVISORY-CLEAR" => RuleExplanation { rule_id: "LF-RUNTIME-ADVISORY-CLEAR", title: "Runtime security finding", meaning: "The configured runtime version/advisory state could not be established as clear under the local security catalog.", remediation: "Upgrade or verify the runtime before using it to execute untrusted models." },
        "LF-RUNTIME-ADVISORY-STALE" => RuleExplanation { rule_id: "LF-RUNTIME-ADVISORY-STALE", title: "Runtime security finding", meaning: "The configured runtime version/advisory state could not be established as clear under the local security catalog.", remediation: "Upgrade or verify the runtime before using it to execute untrusted models." },
        "LF-SAFE-DTYPE" => RuleExplanation { rule_id: "LF-SAFE-DTYPE", title: "Safetensors finding", meaning: "The Safetensors artifact contains a structural, dtype or shard-index condition requiring review.", remediation: "Reject malformed artifacts or use a supported dtype/shard set from a trusted source." },
        "LF-SERIALIZATION-BIN" => RuleExplanation { rule_id: "LF-SERIALIZATION-BIN", title: "Layerfault security finding", meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.", remediation: "Review the finding evidence and follow the configured policy before deployment." },
        "LF-TEMPLATE-CHANGED" => RuleExplanation { rule_id: "LF-TEMPLATE-CHANGED", title: "Derived-model integrity change", meaning: "A security-relevant component of the derived model differs from the supplied base or transformation claim.", remediation: "Verify the claimed transformation and investigate the changed component before treating the derivative as equivalent to its base." },
        "LF-TF-CHECKPOINT-LIMIT" => RuleExplanation { rule_id: "LF-TF-CHECKPOINT-LIMIT", title: "TensorFlow model security finding", meaning: "The TensorFlow package contains a structural, executable/custom-operation or capability-limited condition.", remediation: "Inspect the exact graph/package and do not execute untrusted custom operations during model loading." },
        "LF-TF-CHECKPOINT-STRUCT" => RuleExplanation { rule_id: "LF-TF-CHECKPOINT-STRUCT", title: "TensorFlow model security finding", meaning: "The TensorFlow package contains a structural, executable/custom-operation or capability-limited condition.", remediation: "Inspect the exact graph/package and do not execute untrusted custom operations during model loading." },
        "LF-TF-EXECUTION-OP" => RuleExplanation { rule_id: "LF-TF-EXECUTION-OP", title: "TensorFlow model security finding", meaning: "The TensorFlow package contains a structural, executable/custom-operation or capability-limited condition.", remediation: "Inspect the exact graph/package and do not execute untrusted custom operations during model loading." },
        "LF-TF-STRUCT" => RuleExplanation { rule_id: "LF-TF-STRUCT", title: "TensorFlow model security finding", meaning: "The TensorFlow package contains a structural, executable/custom-operation or capability-limited condition.", remediation: "Inspect the exact graph/package and do not execute untrusted custom operations during model loading." },
        "LF-TFLITE-STRUCT" => RuleExplanation { rule_id: "LF-TFLITE-STRUCT", title: "TensorFlow model security finding", meaning: "The TensorFlow package contains a structural, executable/custom-operation or capability-limited condition.", remediation: "Inspect the exact graph/package and do not execute untrusted custom operations during model loading." },
        "LF-TOKENIZER-CHANGED" => RuleExplanation { rule_id: "LF-TOKENIZER-CHANGED", title: "Derived-model integrity change", meaning: "A security-relevant component of the derived model differs from the supplied base or transformation claim.", remediation: "Verify the claimed transformation and investigate the changed component before treating the derivative as equivalent to its base." },
        "LF-UNCLASSIFIED" => RuleExplanation { rule_id: "LF-UNCLASSIFIED", title: "Layerfault security finding", meaning: "Layerfault observed a security-relevant condition in the model, package or review evidence.", remediation: "Review the finding evidence and follow the configured policy before deployment." },
        _ => return None,
    };
    Some(item)
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct RiskExplanation {
    pub rule_id: String,
    pub title: String,
    pub categories: Vec<String>,
    pub summary: String,
    pub risk: String,
    pub potential_impact: Vec<String>,
    pub recommended_actions: Vec<String>,
}

pub fn risk_lookup(rule: &str) -> RiskExplanation {
    let rule_id = rule.to_ascii_uppercase();
    let (title, categories, summary, risk, impact, actions) = match rule_id.as_str() {
        "LF-SERIALIZATION-UNSAFE" => (
            "Code-capable model serialization detected",
            vec!["Code Execution", "Supply Chain"],
            "The package contains a serialization format that can execute code when loaded by common ML frameworks.",
            "An unsafe loader may execute attacker-controlled code with the privileges of the model runtime.",
            vec!["arbitrary command execution", "credential theft", "filesystem access", "network callbacks"],
            vec!["Do not load or deserialize this artifact.", "Prefer Safetensors or GGUF, or a weights-only loading path.", "Verify the publisher and provenance; quarantine untrusted copies."],
        ),
        "T15-STRUCT" => (
            "Malformed GGUF structure detected",
            vec!["Parser Safety", "Memory Safety"],
            "The artifact violates bounded GGUF structural invariants.",
            "A vulnerable model runtime may crash, read or write out of bounds, allocate excessive resources, or otherwise behave unsafely while parsing it.",
            vec!["runtime crash", "excessive allocation or denial of service", "downstream parser memory-safety exposure"],
            vec!["Do not pass this artifact to an inference runtime.", "Reacquire it from a trusted source and preserve the malformed copy for investigation."],
        ),
        "LF-SAFE-STRUCT" => (
            "Malformed Safetensors structure detected",
            vec!["Parser Safety", "Memory Safety"],
            "The Safetensors header, tensor ranges, shape sizes, or data-buffer coverage is malformed or unsafe.",
            "A vulnerable loader may mis-handle malformed tensor metadata and crash, allocate incorrectly, or access data outside the intended buffer.",
            vec!["runtime crash", "resource exhaustion", "downstream parser memory-safety exposure"],
            vec!["Reject the file and reacquire it from a trusted source.", "Do not load it into an inference or conversion process."],
        ),
        "LF-CODE-AUTO-MAP" => (
            "Custom Hugging Face model code mapping",
            vec!["Supply Chain", "Code Execution"],
            "Model metadata contains auto_map, which can route loading through custom Python implementations.",
            "Loading may execute code from the model package when custom-code trust is enabled.",
            vec!["arbitrary code execution during model loading", "filesystem or network access under runtime privileges"],
            vec!["Review the referenced source files.", "Avoid trust_remote_code unless the exact package and publisher are trusted.", "Prefer a package that does not require custom loading code."],
        ),
        "LF-CODE-REMOTE-TRUST" => (
            "Custom model-code trust enabled",
            vec!["Supply Chain", "Code Execution"],
            "The package explicitly enables a custom-code trust path.",
            "A model loader may import Python supplied by the package or its remote repository.",
            vec!["arbitrary code execution during model loading", "host and network access through imported code"],
            vec!["Disable remote-code trust where possible.", "Inspect and attest the complete package before loading it."],
        ),
        "LF-CODE-IMPORT-SIDE-EFFECT" => (
            "Import-time custom code side effect",
            vec!["Code Execution", "Filesystem Access", "Network Exposure"],
            "A configured custom model module contains a security-relevant operation at module scope.",
            "Importing the module through the model loading path can perform the operation before the model is constructed.",
            vec!["arbitrary command execution", "filesystem modification", "network callbacks or data exfiltration"],
            vec!["Do not enable custom-code loading for this package.", "Quarantine it and review the referenced module from a trusted development environment."],
        ),
        "LF-PACKAGE-CODE" => (
            "Custom or executable package code present",
            vec!["Code Execution", "Supply Chain"],
            "The package contains Python, scripts, native libraries, or another executable-content artifact.",
            "The model loading or conversion path may execute package-supplied code.",
            vec!["arbitrary code execution", "filesystem and network access", "persistence under runtime privileges"],
            vec!["Review whether the file is required.", "Prefer a weights-only package and verify its provenance before loading."],
        ),
        "LF-CODE-NETWORK" => (
            "Network-capable model code detected",
            vec!["Network Exposure", "Code Execution"],
            "Custom model content references a network or HTTP primitive.",
            "If executed by a loader, the code may contact remote systems or transmit local data.",
            vec!["data exfiltration", "remote callbacks", "access to internal network services"],
            vec!["Do not execute the custom code.", "Review and remove network behavior, then rescan the complete package."],
        ),
        "LF-CODE-OS-SYSTEM" | "LF-CODE-SUBPROCESS" | "LF-CODE-EXEC" | "LF-CODE-EVAL" => (
            "Command or dynamic-code primitive detected",
            vec!["Code Execution"],
            "Custom model content references a command-execution or dynamic-code primitive.",
            "If reached during loading, attacker-controlled instructions may run with the model runtime's privileges.",
            vec!["arbitrary command execution", "credential and filesystem access", "persistence or lateral movement"],
            vec!["Do not load the package.", "Review the source statically and replace it with a trusted non-code-capable artifact."],
        ),
        "LF-CODE-CTYPES" => (
            "Native library loading primitive detected",
            vec!["Code Execution", "Memory Safety"],
            "Custom model content references ctypes or native-library loading.",
            "Loading native code can bypass ordinary Python-level restrictions and execute host instructions.",
            vec!["arbitrary native code execution", "memory corruption", "host compromise"],
            vec!["Do not load the package.", "Use a trusted artifact without native extension loading and verify provenance."],
        ),
        "LF-PACKAGE-SYMLINK" => (
            "Model package symlink detected",
            vec!["Supply Chain", "Integrity"],
            "A direct model package contains a symlink outside the explicit package-file model.",
            "Implicit link traversal can make package identity and inspected content differ from what an operator intended.",
            vec!["content substitution", "out-of-bound package access", "unstable identity"],
            vec!["Replace the symlink with an explicit regular file, or use the validated Hugging Face cache audit path."],
        ),
        "LF-PACKAGE-RACE" => (
            "Package member changed during scan",
            vec!["Integrity"],
            "A package file produced a different digest when rehashed after scanning.",
            "Concurrent mutation means the inspected bytes are not a stable basis for admission.",
            vec!["time-of-check/time-of-use substitution", "inconsistent evidence"],
            vec!["Block execution, preserve the artifact, and rescan from a stable read-only copy."],
        ),
        "LF-PROV-UNSIGNED" => (
            "Unsigned artifact",
            vec!["Provenance", "Trust"],
            "No attestation was supplied for the exact artifact identity.",
            "Layerfault cannot connect this artifact to an authorized publisher through its configured provenance mechanism.",
            vec!["unverified supply-chain origin", "publisher substitution risk"],
            vec!["Use a policy appropriate for unsigned artifacts, or obtain an attestation from an authorized key."],
        ),
        "LF-PROV-REVOKED" | "LF-PROV-NAMESPACE" | "LF-PROV-INACTIVE" | "LF-PROV-SIGSTORE-INVALID" => (
            "Artifact provenance failed",
            vec!["Provenance", "Trust"],
            "The supplied provenance is invalid, unauthorized, revoked, or outside its active trust window.",
            "The artifact cannot be reliably attributed to an authorized publisher under the configured trust policy.",
            vec!["publisher substitution", "tampered or stale release evidence"],
            vec!["Do not run the artifact.", "Investigate the provenance and obtain a valid attestation from an authorized publisher."],
        ),
        "LF-RUNTIME-VERSION-UNKNOWN" => (
            "Runtime version could not be compared",
            vec!["Compatibility", "Trust"],
            "Layerfault could not derive a version suitable for its offline runtime advisory catalog.",
            "Known-vulnerability checks may be incomplete for this runtime.",
            vec!["unassessed runtime vulnerability exposure"],
            vec!["Use an official runtime with machine-readable version output and verify it before admitting untrusted models."],
        ),
        "LF-FORMAT-UNKNOWN" => (
            "Unknown artifact format",
            vec!["Compatibility"],
            "Layerfault can hash this file but has no structural parser for its format.",
            "Format-specific corruption and loader risks cannot be assessed by the configured scanners.",
            vec!["unassessed parser and loading behavior"],
            vec!["Prefer GGUF or Safetensors, or make an explicit policy decision for this unknown format."],
        ),
        x if x.starts_with("LF-BEHAV-") || x.starts_with("LF-DIFF-") => (
            "Behavioural security evidence",
            vec!["Behavioural Security", "Differential Behaviour"],
            "A bounded local probe or base-versus-derived comparison produced security-relevant behavioural evidence.",
            "The observed condition may indicate a targeted security regression or trigger-dependent behaviour under the tested conditions; it does not establish training-time cause.",
            vec!["synthetic secret disclosure", "unsafe fake-tool intent", "privilege-boundary regression", "targeted unsafe behaviour"],
            vec!["Do not deploy the derivative until the behaviour is reproduced and understood.", "Review the exact probe, runtime fingerprint, seed, base comparison and evidence boundary."],
        ),
        x if x.starts_with("LF-LINEAGE-") || x.starts_with("LF-DERIVE-") || x.starts_with("LF-ADAPTER-") => (
            "Derived-model integrity evidence",
            vec!["Lineage", "Supply Chain"],
            "The observed model structure or transformation evidence does not fully match the claimed derivation relationship.",
            "An unverified or contradicted derivation can hide additional changes beyond the operator's expected transformation.",
            vec!["unexpected model modification", "publisher/transformation substitution", "unexplained tokenizer/template/weight changes"],
            vec!["Verify the exact base and derived identities.", "Require signed transformation evidence or reproduce the supported transformation where possible."],
        ),
        x if x.starts_with("LF-DATASET-") => (
            "Dataset poisoning indicator",
            vec!["Training Data", "Poisoning Evidence"],
            "A bounded dataset analysis found an unusual duplication, trigger correlation, encoding, credential-like or unsafe-code pattern.",
            "The indicator can guide investigation and behavioural correlation but cannot by itself prove malicious poisoning.",
            vec!["targeted fine-tune behaviour", "training contamination", "unexpected trigger association"],
            vec!["Inspect the flagged records and dataset provenance.", "Correlate candidate triggers against a trusted base and the derived model before drawing conclusions."],
        ),
        x if x.starts_with("LF-ONNX-") || x.starts_with("LF-TF-") || x.starts_with("LF-TFLITE-") || x.starts_with("LF-KERAS-") => (
            "Extended model-format security finding",
            vec!["Parser Safety", "Model Package"],
            "A non-GGUF/Safetensors model format contains a structural, external-data, custom-operation or executable-object condition requiring review.",
            "Executing untrusted custom operators or following unsafe external references can cross the model-data trust boundary.",
            vec!["custom code execution", "path traversal", "resource exhaustion", "unassessed runtime behaviour"],
            vec!["Keep inspection non-executing.", "Reject malformed/external-path violations and review custom operations before any runtime loads the model."],
        ),
        _ => (
            "Unclassified Layerfault finding",
            vec!["Compatibility"],
            "Layerfault reported a finding without a dedicated operator explanation.",
            "The available evidence is insufficient to make a more specific claim, so the configured decision should be respected conservatively.",
            vec!["unassessed artifact, package, integrity, or policy risk"],
            vec!["Review the finding detail and preserve the artifact.", "Do not suppress the finding unless the evidence and policy exception are explicitly reviewed."],
        ),
    };
    RiskExplanation {
        rule_id,
        title: title.to_owned(),
        categories: categories.into_iter().map(ToOwned::to_owned).collect(),
        summary: summary.to_owned(),
        risk: risk.to_owned(),
        potential_impact: impact.into_iter().map(ToOwned::to_owned).collect(),
        recommended_actions: actions.into_iter().map(ToOwned::to_owned).collect(),
    }
}

#[cfg(test)]
mod tests {
    use super::risk_lookup;

    #[test]
    fn risk_mapping_covers_actionable_serialization_and_unknown_rules() {
        let serialization = risk_lookup("LF-SERIALIZATION-UNSAFE");
        assert_eq!(serialization.categories[0], "Code Execution");
        assert!(!serialization.potential_impact.is_empty());
        assert!(!serialization.recommended_actions.is_empty());

        let unknown = risk_lookup("LF-UNRECOGNIZED");
        assert_eq!(unknown.rule_id, "LF-UNRECOGNIZED");
        assert!(!unknown.recommended_actions.is_empty());
    }
}
