#[derive(Debug, Clone, serde::Serialize)]
pub struct RuleExplanation {
    pub rule_id: &'static str,
    pub title: &'static str,
    pub meaning: &'static str,
    pub remediation: &'static str,
}

pub fn lookup(rule: &str) -> Option<RuleExplanation> {
    let normalized = rule.to_ascii_uppercase();
    let item = match normalized.as_str() {
        "LF-SCAN-ERROR" => RuleExplanation { rule_id: "LF-SCAN-ERROR", title: "Scanner error", meaning: "Layerfault could not safely complete inspection of an artifact.", remediation: "Treat the model as blocked. Preserve the artifact and investigate the parser/I/O error rather than suppressing it." },
        "LF-PROV-UNSIGNED" => RuleExplanation { rule_id: "LF-PROV-UNSIGNED", title: "Unsigned artifact", meaning: "No Layerfault attestation was found for the exact artifact identity.", remediation: "Use workstation policy if unsigned models are acceptable, or obtain/sign an attestation with an authorized key for strict admission." },
        "LF-PROV-REVOKED" => RuleExplanation { rule_id: "LF-PROV-REVOKED", title: "Revoked signer", meaning: "An attestation is bound to a trust-store key that has been revoked.", remediation: "Do not run the artifact. Re-attest a verified artifact with a currently authorized key after investigating the revoked signer." },
        "LF-PROV-NAMESPACE" => RuleExplanation { rule_id: "LF-PROV-NAMESPACE", title: "Signer namespace mismatch", meaning: "The signature is valid but the signer is not authorized for this model identity.", remediation: "Correct the trust policy or obtain an attestation from a publisher key authorized for this namespace." },
        "LF-SAFE-STRUCT" => RuleExplanation { rule_id: "LF-SAFE-STRUCT", title: "Invalid Safetensors structure", meaning: "The Safetensors header, tensor ranges, shape sizes, or data-buffer coverage is malformed or unsafe.", remediation: "Reject the file and reacquire it from a trusted source. Do not load it into an inference/runtime process." },
        "LF-SAFE-INDEX" => RuleExplanation { rule_id: "LF-SAFE-INDEX", title: "Safetensors index validated", meaning: "The sharded Safetensors index uses safe relative shard references and every referenced shard passed structural validation.", remediation: "No action is required unless policy independently blocks the artifact." },
        "LF-SAFE-INDEX-INVALID" => RuleExplanation { rule_id: "LF-SAFE-INDEX-INVALID", title: "Invalid Safetensors sharded index", meaning: "A sharded Safetensors index is malformed, references an unsafe/missing shard, or points to a shard that failed structural validation.", remediation: "Block the model and reacquire the complete shard set from a trusted source." },
        "LF-PROV-SIGSTORE" => RuleExplanation { rule_id: "LF-PROV-SIGSTORE", title: "Sigstore bundle verified", meaning: "An installed Cosign verifier accepted the supplied offline Sigstore bundle for the expected certificate identity and issuer.", remediation: "No action is required; keep the bundle with provenance evidence if the artifact is admitted." },
        "LF-PROV-SIGSTORE-INVALID" => RuleExplanation { rule_id: "LF-PROV-SIGSTORE-INVALID", title: "Invalid Sigstore bundle", meaning: "Cosign could not verify the supplied bundle against the expected artifact, certificate identity or issuer.", remediation: "Block the artifact and investigate provenance. Do not weaken identity or issuer constraints merely to make verification pass." },
        "LF-PROV-INACTIVE" => RuleExplanation { rule_id: "LF-PROV-INACTIVE", title: "Inactive trusted key", meaning: "The signature is cryptographically valid but the corresponding trusted key is outside its activation window.", remediation: "Use a currently active authorized signer or deliberately correct the trust-store activation/expiry window after verification." },
        "LF-PROV-TRUSTED" => RuleExplanation { rule_id: "LF-PROV-TRUSTED", title: "Trusted attestation", meaning: "The exact model manifest is signed by a currently active key authorized for the model namespace.", remediation: "No action is required unless a higher signature threshold or another policy condition is configured." },
        "LF-FORMAT-UNKNOWN" => RuleExplanation { rule_id: "LF-FORMAT-UNKNOWN", title: "Unknown artifact format", meaning: "Layerfault can hash the file but does not have a structural parser for this artifact format.", remediation: "Use a supported GGUF/Safetensors artifact or an explicit policy that allows the unknown format only when this is intentional." },
        "LF-PACKAGE-SYMLINK" => RuleExplanation { rule_id: "LF-PACKAGE-SYMLINK", title: "Model package symlink", meaning: "A direct model package contains a symlink. Layerfault fingerprints direct packages without following links so a package cannot silently escape its root.", remediation: "Replace the symlink with an explicit regular file, or use the dedicated Hugging Face cache audit path where validated snapshot-to-blob symlinks are resolved safely." },
        "LF-SERIALIZATION-UNSAFE" => RuleExplanation { rule_id: "LF-SERIALIZATION-UNSAFE", title: "Code-capable serialization", meaning: "The package contains a Pickle/PyTorch/joblib-style artifact that may execute code when deserialized by an unsafe loader.", remediation: "Prefer Safetensors/GGUF or a weights-only loading path. Do not deserialize untrusted artifacts merely to inspect them; Layerfault intentionally never loads the object graph." },
        "LF-CODE-AUTO-MAP" => RuleExplanation { rule_id: "LF-CODE-AUTO-MAP", title: "Custom Hugging Face model code mapping", meaning: "Model metadata contains auto_map, which can route model loading through custom Python implementations.", remediation: "Review the referenced source files and avoid trust_remote_code unless the package publisher and exact package identity are trusted." },
        "LF-CODE-REMOTE-TRUST" => RuleExplanation { rule_id: "LF-CODE-REMOTE-TRUST", title: "Remote/custom code trust enabled", meaning: "The package explicitly enables a custom-code trust path.", remediation: "Disable remote-code trust where possible and inspect/sign the full model package before loading custom implementations." },
        "LF-TEMPLATE-INTROSPECTION" => RuleExplanation { rule_id: "LF-TEMPLATE-INTROSPECTION", title: "Template introspection primitives", meaning: "A model template contains Jinja/Python introspection primitives that can become dangerous in an overly permissive rendering environment.", remediation: "Review the runtime template sandbox and remove introspection primitives unless they are required and demonstrably safe." },
        "LF-RUNTIME-VERSION-UNKNOWN" => RuleExplanation { rule_id: "LF-RUNTIME-VERSION-UNKNOWN", title: "Runtime version could not be compared", meaning: "Layerfault could not derive a version/build identifier suitable for its offline vulnerability catalog.", remediation: "Use an official runtime build with machine-readable version output or verify the runtime version manually before admitting untrusted models." },
        "LF-PACKAGE-RACE" => RuleExplanation { rule_id: "LF-PACKAGE-RACE", title: "Package member changed during scan", meaning: "A package file produced a different digest when rehashed after scanning, indicating concurrent mutation or an unstable storage layer.", remediation: "Block execution, preserve the artifact for investigation, and rescan from a stable read-only copy." },
        "T15-STRUCT" => RuleExplanation { rule_id: "T15-STRUCT", title: "Invalid GGUF structure", meaning: "The GGUF structure failed bounded validation.", remediation: "Reject and reacquire the model. Structural failures are not suppressible admission warnings." },
        "T12-001" => RuleExplanation { rule_id: "T12-001", title: "Embedded ELF object", meaning: "A structurally plausible ELF executable object exists inside model bytes.", remediation: "Quarantine the artifact and investigate its source. Do not infer malicious intent from magic bytes alone; Layerfault only emits this after structural checks." },
        "T12-002" => RuleExplanation { rule_id: "T12-002", title: "Embedded PE object", meaning: "A structurally plausible PE executable object exists inside model bytes.", remediation: "Quarantine the artifact and investigate its source before allowing execution." },
        _ => return None,
    };
    Some(item)
}
